### ISSUE TITLE
Document font usage

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#10]
Add documentation to the typography section for fonts and font stacks.

Notably, if Typekit able to be used, we use Quatro Slab for headings and Myriad Pro for body copy. If Google Fonts is used, we use Open Sans for all text.

**Comment by RCopeland** [comment]
I wonder if we should define the google fonts option, shouldnt it either be typekit fonts or the fallbacks?
@philrinke thoughts?

**Comment by yodasw16** [comment]
This came form a specific situation where a vendor or internal team or something didn't have access to typekit for some reason and needed to know what the alternative would be. Marketing said Open Sans. I don't remember the exact circumstance of why this came up.

**Comment by RCopeland** [comment]
Closing for now on the opinion that sites should use the typekit fonts or the fallbacks. Can revisit in the future.

https://github.com/sparkdesignsystem/spark-design-system/pull/77
