### ISSUE TITLE
[DOCUMENTATION] Button Content Guidelines

### ISSUE THREAD

**Issue by philrinke** [sparkdesignsystem/spark-design-system#1004]
## Proposal Title
Update Guidelines for Buttons

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [ ] **Component** (Modifying the functionality of a component)
* [x] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

## Description
_Capitalization Page Entry_
Use title case for primary and secondary buttons.
Use all caps for tertiary buttons.
See our web guidelines for button copy guidelines and information on when each button style is appropriate.
See the button styles on Spark.
 
Web Guidelines Entry
When writing button copy,
Use active verbs like “create”, “join”, or “discover” to entice a client. Avoid vague labels like “learn more” or “get started.”
Use consistent phrases throughout the experience.
Clearly communicate what will happen when clients click the button.
There are three button styles available on Spark. Here’s when to use each:
 
Use a primary button for the main action we want the user to take.
Avoid using more than one primary button per page.
Use secondary buttons for all other actions.
Use tertiary buttons to give users the option to navigate to a new page.
Please note that in many cases, a link is preferable to a tertiary button when guiding users to another page.

The character limit of the button copy depends on where it’s placed in the design:
If the button(s) are not in a modal or dialogue box, each button can have up to approximately 20 characters.
If the button(s) are in a modal or dialogue box, the character limit depends on the number of buttons. The modal design requires the buttons to be displayed side-by-side; therefore, the character limit for the entire line of buttons within the modal is approximately 20 characters. This means each button should be no more than six to eight characters depending on the number of each button and the length of the copy on the other buttons.

## Rationale
The folks in content strategy have taken a look over the buttons and have provided some guidelines around the button content and would like to see it in Spark to help provide some clarity around what words we use within buttons.

## Live Examples
n/a

**Comment by afebbraro** [comment]
@philrinke  is gonna follow up with content on the all caps for tertiary buttons since it would be a new design change. Right now they are not caps. Moving forward with adding all the other info from this and we can make a follow up issue for what comes of the tertiary design change conversation.

**Comment by philrinke** [comment]
Content Team is re-evaluating this story. I will put a new story in when the guidelines around the buttons content is updated
