### ISSUE TITLE
Differing heights between select box and rest of input elements

### ISSUE THREAD

**Issue by kkwiedacz** [sparkdesignsystem/spark-design-system#1022]
## Describe The Bug
Select Box height differs from the rest of the spark input heights

## To Reproduce
1. Go to 'https://sparkdesignsystem.com/patterns/components/inputs#select-box'
2. Inspect the select box element, note that the height of the element is 44px
3. Go to 'https://sparkdesignsystem.com/patterns/components/inputs#text-input'
4. Inspect the input field element, note that the height of the element is 48px

## Expected Behavior
I would expect that all input fields should be of the same height as when used side by side in forms it would become obvious that one field height differs from the other and would require custom CSS to over-ride this behavior.

## Screenshots
![screen shot 2019-01-08 at 9 57 59 am](https://user-images.githubusercontent.com/8762118/50838403-f0717680-132b-11e9-9ad7-a193689093de.png)
![screen shot 2019-01-08 at 9 57 48 am](https://user-images.githubusercontent.com/8762118/50838411-f2d3d080-132b-11e9-9761-79acffe6a46b.png)

## Desktop (please complete the following information):
 - OS: Mac OS Sierra v 10.12.6
 - Browser: Chrome
 - Version: 71.0.3578.98

## Smartphone (please complete the following information):
N/A

## Additional Context
N/A

**Comment by kkwiedacz** [comment]
I can follow up with a fix for this, if it is determined that this is a bug and not a design decision.

**Comment by RCopeland** [comment]
Hey @kkwiedacz, that is definitely a bug, thanks! If you want to open a PR, that would be appreciated, you can open it against the staging branch. If not, no worries, we should have it fixed for our next release. Thanks!
