### ISSUE TITLE
[BUILD] Tabbed Navigation reskin

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#1032]
Design task is #1003

**Comment by yodasw16** [comment]
@afebbraro did you do this as part of your React tabs? Just making sure the issue doesn't get left behind when your stuff gets merged.

**Comment by afebbraro** [comment]
@yodasw16 No, I didn't do it as part of React Tabs. Brendan said the changes weren't ready yet. I directed him towards Steph for when he has all the info.

**Comment by ssabo1** [comment]
@afebbraro I chatted with Brendan - The changes are not ready. Brendan said if we want it to be on brand the easiest is to change red to black however he thinks we could make it a smoother transition but needs the time to play with what the smoother transition would look like.
