### ISSUE TITLE
[BUILD] Modals Component - React

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1078]
**User Story:**
As a Spark User I want to be able to use React Components so that I have multiple options.

**AC:**
- Build Modals Component - React
- Write Unit Test
- Complete Full Regression Test

**Comment by 13protons** [comment]
Tracking this work with the branch [1078-react-modal](https://github.com/sparkdesignsystem/spark-design-system/tree/1078-react-modal)
