### ISSUE TITLE
[Bug] Angular Inputs: Monetary Input doesnt show the $ icon

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#1100]
<img width="532" alt="screen shot 2019-01-28 at 1 33 05 pm" src="https://user-images.githubusercontent.com/412903/51857841-43be5f80-2301-11e9-9e94-c7b31e434a58.png">

**Comment by afebbraro** [comment]
I added a comment to this PR yesterday morning, marked it needs changes so we could talk about the comment and am moving this back to in progress for now.

**Comment by RVMendoza** [comment]
https://github.com/sparkdesignsystem/spark-design-system/pull/1202
