### ISSUE TITLE
[BUG] Angular Select Box does not render with chevron by default.

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/spark-design-system#1105]
The Angular example for the Select Box component does not include the chevron in the code example. We need to either modify the angular component to inject the chevron icon if needed, or modify the documentation to make it clear that the icon must be added manually.

## To Reproduce
1. Add an Angular Select Box to a page using the sample code.

```
<sprk-input-container>
  <label sprkLabel>Select Box Label</label>
  <select class="sprk-b-Select" id="select-normal" aria-describedby="select-normal--error-container" data-id="select-1" sprkInput>
    <option value="none">Make a selection...</option>
    <option value="1">Option 1</option>
    <option value="2">Option 2</option>
    <option value="3">Option 3</option>
    <optgroup label="Grouped Options">
      <option value="g1">Grouped Option 1</option>
      <option value="g2">Grouped Option 2</option>
      <option value="g3">Grouped Option 3</option>
    </optgroup>
  </select>
</sprk-input-container>
```
2. You should not see a chevron.

![image](https://user-images.githubusercontent.com/1424560/52010225-fe399800-24a2-11e9-80f4-0a4fef78dc01.png)

3. Add the chevron manually (like in the Angular test page)
```
<sprk-icon
     iconType="chevron-down"
     additionalClasses="sprk-c-Icon--stroke-current-color sprk-b-SelectContainer__icon"
     prk-select-icon></sprk-icon>
```

4. You should see a chevron.

![image](https://user-images.githubusercontent.com/1424560/52010015-5cb24680-24a2-11e9-9dc2-df3e1d718060.png)

## Expected Behavior
Copy/pasting the documentation code should render a component identical to what appears in the documentation.

**Comment by bobwise** [comment]
Note - this component is live, so users have gotten into the habit of manually adding the chevron already.

**Comment by asketes** [comment]
I'd definitely want to change the habits of the few in order to correct the future habits of the many. I'm glad this is going to be addressed! 👍
