### ISSUE TITLE
[bug] Fix duplicate icons

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1109]
Update either "recurring-update" or "update" because they are visually the same. One of them might need to be updated to the circle with the $ in it.

**Comment by afebbraro** [comment]
![screen shot 2019-03-07 at 9 42 25 am](https://user-images.githubusercontent.com/2117593/53964430-5de81c00-40bd-11e9-8a42-10aed86212c3.png)
![screen shot 2019-03-07 at 9 42 31 am](https://user-images.githubusercontent.com/2117593/53964433-5fb1df80-40bd-11e9-8e7b-1986c18d6e8f.png)

**Comment by yodasw16** [comment]
Closing this out. Icons will be updated from Brand this Quarter.
