### ISSUE TITLE
Spark One Pager

### ISSUE THREAD

**Issue by philrinke** [sparkdesignsystem/spark-design-system#111]
It has been asked of the spark team to provide a one pager that we can pass out during UXL or when other areas of our business want a brief explanation of what spark is and how it can benefit them. 

I'll be designing a pamphlet that we can give to folks to start getting the word out about spark.

**Comment by afebbraro** [comment]
Half of an 8 1/2 by 11

**Comment by afebbraro** [comment]
I created this for review!
![handout](https://user-images.githubusercontent.com/2117593/40742665-384c4336-641d-11e8-9354-3b1525ff801d.jpg)

**Comment by afebbraro** [comment]
Ready for print!
