### ISSUE TITLE
[BUILD] Stepper Component with Carousel Variant

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1112]
**User Story:**
As a user I want to see a Stepper component with a Carousel Variant so that I see liner progress in a process.

**Notes:**
Stepper Is a component that shows linear progress in a process

**AC**
- I will see a Stepper with carousel variant.
- I will see Hover State to the stepper 
- Hover State Styles will be different than Active State Styles.
- Only 1 item/step will be active at a time
- Styles will be the same on mobile and desktop
- Min of 3 Steps/Items
- Max???
- Stepper will auto play when stepper is in user view - (Work with Brendon timing trial and error)
- Auto play will have an accessibility requirement for a PAUSE option - (Brendan talking with Nathan)

**Comment by afebbraro** [comment]
Items needing research:
- Should the "step bar" be it's own component and the carousel be it's own component?
- What are the expected keyboard interactions on the carousel and the "step bar" (arrow keys to advance images)?
- Do we need an option for auto-play? If so, we might need a pause button.
- Accessibility requirements and necessary ARIA attributes such as aria-pressed="true", ETC.
