### ISSUE TITLE
Accordions Design / Documentation

### ISSUE THREAD

**Issue by philrinke** [sparkdesignsystem/spark-design-system#113]
Develop a component design for Accordions / Drawers to figure out how we want to handle show/hide content and if accordions / drawers are the same or different components

**Comment by philrinke** [comment]
○ Descriptive Component Name: Accordion
	○ Brief Description: An Accordion is a simple way of showing, hiding and breaking down content. It helps make content easier to find as well as since it allows the content to be broken up.
	○ Core/Base Elements (things that cant be altered):
		○ Both interactions & aesthetics
	○ Style
		○ Both styles of accordion need to have a collapsed, hover and expanded state
		○ Desktop & mobile will look & function the same
		○ Accordions can be anywhere from 100% width or 50% width on desktop and 100% width on mobile
	○ Usage: The length of the content
	○ Sizing & Padding: Sizing should be dependent on type size, but should remain large enough to be tapable on a mobile device
Notes: Content length inside the accordion does not have a limit. Title content of the accordion can wrap, but it is recommended that it is short and to the point

**Comment by philrinke** [comment]
<img width="791" alt="screen shot 2018-03-14 at 2 07 18 pm" src="https://user-images.githubusercontent.com/8290964/37428323-3ea6832a-27a2-11e8-9f62-f67fd85c013b.png">

**Comment by philrinke** [comment]
<img width="782" alt="screen shot 2018-03-14 at 2 08 42 pm" src="https://user-images.githubusercontent.com/8290964/37428326-42fdfe9e-27a2-11e8-9526-d1a2d6f948ca.png">

**Comment by philrinke** [comment]
<img width="590" alt="screen shot 2018-03-14 at 2 17 58 pm" src="https://user-images.githubusercontent.com/8290964/37428330-46cbfc74-27a2-11e8-9c84-adc7e5da8463.png">

**Comment by yodasw16** [comment]
Are these 3 different styles that we will support or 3 possibilities? Also wondering if we need this for v1. The original thought was needing something to cover the disclaimer in JDP. I'm not sure this is the same pattern as what is in the JDP wireframes.

**Comment by philrinke** [comment]
After doing some digging it came to light that Accordion, Drawer, Toggle are all used interchangeably to refer to different components by not only our team but other teams as well. This was the first one I came across. Toggle (what we would need for JDP) is what I will tackle next

**Comment by philrinke** [comment]
These are 2 different styles of accordions the second ones show a selected state of just the lined accordion
