### ISSUE TITLE
[Research] Possible Bug: Errors with Angular Date Picker with --prod build flag

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1132]
Noticing that the date picker pops up fine in local development, but when they build the Angular project for production (--prod flag) the date picker is no longer popping up.

**Comment by umeshbapat** [comment]
Is any other team able to get the calendar control working in production?
**Team RMS (Slingshot, TigerSharks)
Team Captain America** 
Are the teams facing this issue currently

**Comment by RCopeland** [comment]
this should be fixed in spark-angular@9.4.0
