### ISSUE TITLE
Set up Snyk for security monitoring

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#1134]
We need to get Synk set up to monitor our packages for security vulnerabilities. We have an enterprise account that we can use.

See @yodasw16 for details.

**AC:**
- Set up in Travis

**Comment by 13protons** [comment]
I have access to this now and we should work it into our build refactor @RCopeland

**Comment by 13protons** [comment]
Also see docs here, and myself or @yodasw16 for API keys https://snyk.io/docs/ci/
