### ISSUE TITLE
Paragraph element top cut off

### ISSUE THREAD

**Issue by shametim** [sparkdesignsystem/spark-design-system#1139]
## Describe The Bug
Paragraph element gets cut off at top of page when inside of flag body.

## To Reproduce
1. Go to [Flag Object - Layout](https://sparkdesignsystem.com/patterns/fundamentals/layout#flag-object)
2. Use code in standalone page.

## Expected Behavior
I expected the paragraph element to display appropriately within the bounds of the flag element.

Project is a brand new Angular project generated with CLI. No styles have been applied anywhere in the app yet.

## Screenshots
![image](https://user-images.githubusercontent.com/9932250/53020077-32f69a80-3424-11e9-8dd9-a9bd0b768673.png)

Another example: 
[Page Title - Typography](https://sparkdesignsystem.com/patterns/fundamentals/typography#page-title)

![image](https://user-images.githubusercontent.com/9932250/53020868-e0b67900-3425-11e9-80b5-cd958cba853c.png)

## Desktop (please complete the following information):
 - OS: Win10
 - Browser: Chrome (Microsoft Edge as well)
 - Chrome Version 72.0.3626.81 

## Additional Context
Angular 7.

**Comment by afebbraro** [comment]
I looked into this and verified it. We need to rewrite the Flag component using Flex, that will fix this one.

**Comment by shametim** [comment]
Thank you for looking into this @afebbraro!

**Comment by yodasw16** [comment]
https://github.com/sparkdesignsystem/spark-design-system/issues/1169
