### ISSUE TITLE
[Documentation] Improve docs around using our Github to submit issues

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1140]
**User Story:**
As a user I want to see clear documentation for Submitting Issues in Github so that the issues can be understood by the engineer looking into the Issue.

**Note:** 
- Needs to be clear that this is about posting private information to a public github.
- This could be added In our docs site, in the wiki, and possibly a bold section at the top of our main readme.

**AC:**
- Add information for teams about posting issues in our public github.

**Comment by ssabo1** [comment]
This will be Review and updated with #2209
