### ISSUE TITLE
[BUG] React spinner component does not render in modal

### ISSUE THREAD

**Issue by 13protons** [sparkdesignsystem/spark-design-system#1150]
Importing and using the react spinner component results in an empty DOM node (no content) without error. This component may be incomplete as it is not currently part of the `Spark Core React` test app. 

https://github.com/sparkdesignsystem/spark-design-system/blob/1078-react-modal/src/react/projects/spark-core-react/src/SprkModal/SprkModal.js#L113

<img width="667" alt="screen shot 2019-02-27 at 10 02 26 am" src="https://user-images.githubusercontent.com/1456258/53499680-d5db9400-3a76-11e9-9f28-91157c4dcb29.png">

**Comment by bobwise** [comment]
The Spinner is rendering in the `light` variant by default, which is white text on modal's white background. Switching to the `dark` variant fixes this issue.

**Comment by bobwise** [comment]
fixed by https://github.com/sparkdesignsystem/spark-design-system/pull/1151/commits/932d5ea58c7b3433f7b7130d42f5d0d54624a468

**Comment by afebbraro** [comment]
Closing as this is fixed by @bobwise 's Modal PR.
