### ISSUE TITLE
Angular documentation for dismissible alerts is incorrect

### ISSUE THREAD

**Issue by waterskier2007** [sparkdesignsystem/spark-design-system#1153]
## Describe The Bug
Angular documentation for dismissible alerts is incorrect. dismissible should be bound to using [dismissible]

## To Reproduce
1. Per the documentation, create an alert with the following snippet
```
<sprk-alert alertType="success" dismissible="false" idString="alert-success-2" analyticsString="object.action.event">
  This is an Alert
</sprk-alert>
```
2. The alert that is rendered will still have the close button (x) on the right side

## Expected Behavior
The alert should not have a close button (x) on the right side

## Screenshots
The alert should appear like
![image](https://user-images.githubusercontent.com/2089840/53597558-81b4da80-3b70-11e9-9e92-26a91feb69fd.png)
however it instead appears like
![image](https://user-images.githubusercontent.com/2089840/53597584-8d080600-3b70-11e9-874a-c31a2ddf4314.png)
(ignoring the text, the important part is the close button)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: chrome
 - Version: 71

## Additional Context
The issue is just that the docs are incorrect. When using dismissible="false" the literal value "false" is being interpreted as truthy, whereas when binding with [dismissible]="false" the boolean value false is interpreted as falsy, which is the correct intent.

**Comment by afebbraro** [comment]
This is ready for review and merge.
