### ISSUE TITLE
[Bug] Problem with Date regex

### ISSUE THREAD

**Issue by hoanglam-quickenloans** [sparkdesignsystem/spark-design-system#1154]
## Describe The Bug
07201969 **does not** pass as a date
02001969 **does** pass

## To Reproduce
1. Go to https://sparkdesignsystem.com/
2. Find the input of type date
3. Try the patterns above

**Comment by hoanglam-quickenloans** [comment]
The modified regex should probably be this: `^(((0[13578]|1[02])([\/-]?)(0[1-9]|[12]\d|3[01])|(0[469]|11)([\/-]?)(0[1-9]|[12]\d|30)|02([\/-]?)((0[1-9])|[12]\d))(\4|\7|\9)[12]\d{3})$`

**Comment by ssabo1** [comment]
Will be resolved in #1141
