### ISSUE TITLE
Display Code Examples for React Tab in Code Switch

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1164]
**User Story:**
As a user looking at Spark Components, i want to see React code Switch so that i can build my component using React.

**AC:**
- I will see React Code Switch on all components

**Comment by RVMendoza** [comment]
To clarify, at the moment, we can access the react tab on some components on dev, but not currently on public facing.

Had a convo with @ssabo1 @yodasw16 and @13protons, and this task would be done after all the of the react components are implemented.
