### ISSUE TITLE
[BUILD] Spark Stepper Component 

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1193]
**User Story:**
As a user I want to see a Stepper Component with in Spark Design System so that I can show linear progress in a process. 

**Notes:**
- Stepper Is a component that shows linear progress in a process.
- at this time, this will be for vanilla only.

**AC:**
- I will see a Default Stepper Component in Spark.
- I will see a Default Stepper Variant in Spark
- Styles will be the same on mobile and desktop

**Default Stepper Component:**
Default Stepper will include Steps with a one line title.
- I will see Default Stepper (title) in Spark
- I will see Hover State to the stepper
- Hover State Styles will be different than Active State Styles.
- Only 1 item/step will be active at a time
- Min of 3 Steps/Items
- Max???

**Stepper Variant**
Stepper Variant will include Steps with a multi line description.
- I will see Variant Stepper with Item description
- I will see Hover State to the stepper
- Hover State Styles will be different than Active State Styles.
- Only 1 item/step will be active at a time
- Min of 3 Steps/Items
- Max???

**Comment by 13protons** [comment]
@ssabo1 when items include descriptions, does the variant control whether those descriptions are visible before an item becomes active? And is there some rule to not mix items with or without descriptions. 

For example, if I include 3 items (mockup): 

```
Item title 1
Item description for item 1

Item title 2
Item description for item 2

Item title 3
Item description for item 3
```

Would I need to explicitly have the 'stepper' variant or else the descriptions are hidden? It seem like whether or not a description is supplied would control the variant for an item and that 'variant' in the sense we usually use the term is not quite the right concept.

**Comment by afebbraro** [comment]
Closing because we have another task open that encompasses this with the carousel included.
