### ISSUE TITLE
Documentation review

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#12]
We need to review each page and make sure we have documented everything correctly and fully.

**Comment by yodasw16** [comment]
Here are some notes from Phil:

* Introduction
  * What is the design system
  * Why use the design system
  * Design System Principles
  * How to use the design system
    * design specific
    * engineering specific
* Style/Layout
  * Color Contrast Notes
* Components
  * Definition of Component
  * Do’s
  * Dont’s
  * Example
  * Implementation Notes
    * Design/Engineering
  * Accessibility Guidelines
* Interactions
  * Definition of Interaction
  * Do’s
  * Dont’s
  * Example
  * Implementation Notes
    * Design/Engineering
  * Accessibility Guidelines
* Documentation
  * What browsers are supported
  * Accessibility
  * Brand Styleguide
  * Voice & Tone Guide
* Downloads
  * Github
  * Toolkits

**Comment by RCopeland** [comment]
moved the comments to the wiki, closing this for now as I added it to an issue for each pattern.
