### ISSUE TITLE
[Build] Additional Form Field Input Variant - Vanilla

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1210]
**User Story:**
As a Vanilla Spark User I want to see a Larger form field variant so that it could be used on single question page/form.  

**Notes:**
- This is for Vanilla
- See PO for Invision
- JUMBO Class? 3 separate classes?

**AC:**
- i will see a BIG form field variant
- i will see a shadow input variation  
- Content will be center in Big button

**Comment by RVMendoza** [comment]
Edit from designers: placeholder and input text will be left aligned.
Reference: Tommy F. and Matt R.

**Comment by afebbraro** [comment]
Moved this issue back to in progress. Has some additional work needed following the code review.
