### ISSUE TITLE
[Build] Additional Form Field Input Variant - Angular

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1226]
**User Story:**
As an Angular Spark User I want to see a Larger form field variant so that it could be used on single question page/form.

There were some design changes. This input will only be available without a visible label. It exists in markup for accessibility. This also updates react and vanilla accordingly.

![image](https://user-images.githubusercontent.com/4342363/57709923-e644e900-7639-11e9-8e9d-6fa942701570.png)

**Notes:**
- This is for Angular
- See PO for Invision

**AC:**
- Work was completed in Vanilla
- Docs will be updated

**Comment by afebbraro** [comment]
I wonder if we could mark this to have a dependency on the vanilla version?
