### ISSUE TITLE
[Build] Additional Form Field Input Variant - React

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1227]
**User Story:**
As a React Spark User I want to see a Larger form field variant so that it could be used on single question page/form.  

**Notes:**
- This is for React
- See PO for Invision

**AC:**
- Work was completed in vanilla
- update React docs.

**Comment by afebbraro** [comment]
I wonder if we could mark this to have a dependency on the vanilla version?
