### ISSUE TITLE
Allow Cards to expand the with of the page

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1241]
**User Story:**
As a Spark User i want the ability to expand a card the width of the page so that a card can be used in multiple variants.

**AC:**
- I will be able to expand card the full width of the page

**Comment by 13protons** [comment]
Here's an example of full width cards from the Rocket Rebrand. I've interpreted this to mean "the width of it's container" and no "the width of the page" specifically. 

<img width="540" alt="Screen Shot 2019-04-01 at 2 16 12 PM" src="https://user-images.githubusercontent.com/1456258/55434338-64a36b00-5565-11e9-982a-fa4a2e0a6d19.png">
