### ISSUE TITLE
[Documentation] Update React Docs

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1245]
**User Story:**
As a Spark React user when I am reading the docs I want to understand that spark react is an all-in-one package and does not combine both spark-core and spark-extras

**Notes:**
- This is for the Getting Started page https://staging.sparkdesignsystem.com/gettingstarted/react 
- Make sure aware this package is different than the other two.

**AC:**
- React Doc will inform users that Spark React is an all-in-one package

**Comment by ssabo1** [comment]
The way extra styles are imported spark react is in fact NOT an All in One package.
