### ISSUE TITLE
[Bug] Button href does not cause <a> tag to render

### ISSUE THREAD

**Issue by 13protons** [sparkdesignsystem/spark-design-system#1252]
## Describe The Bug
The docs clearly state that adding an `href` to a `<SprkButton>` in react will cause an anchor tag to render. Here's a DOM snapshot contrary to that (also the links don't work): 

Source jsx: 

```jsx
<SprkButton href="#customize" variant="secondary">Customize</SprkButton>
```

Resulting DOM: 

<img width="474" alt="Screen Shot 2019-04-04 at 3 05 53 PM" src="https://user-images.githubusercontent.com/1456258/55581596-3c457900-56eb-11e9-96f9-39402d8b8036.png">

Reference from docs: 

https://staging.sparkdesignsystem.com/patterns/components/buttons#primary

<img width="1032" alt="Screen Shot 2019-04-04 at 3 07 02 PM" src="https://user-images.githubusercontent.com/1456258/55581634-567f5700-56eb-11e9-91ec-196978119486.png">

**Comment by afebbraro** [comment]
Moved back to in progress after my review. Katie is working on a few touch ups.
