### ISSUE TITLE
[Build] Vanilla: write npm publish scripts

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1259]
**User Story:**
As Spark we want to Build the Vanilla npm Package for the Code Restructure so that we split the three nmp packages. 

**Notes:**

**AC:**
- Will have new Vanilla nmp package
- will be able to publish npm when needed.

**Comment by afebbraro** [comment]
Is this the task for combining extras into core?

**Comment by ssabo1** [comment]
This has already been completed.
