### ISSUE TITLE
Storybook for Spark Angular

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1269]
This is for Epic: Spark Code Restructure

**User Story:**
As Spark we want to Get Gatsby, Storybook and Nitlyfy Running for Spark Angular so that ...

**Notes:**

**AC:**
- Gatsby will be running for Spark Angular
- Storybook will be running for Spark Angular
- Nitlyfy will be running for Spark Angular

**Comment by afebbraro** [comment]
Storybook for Angular is installed but not running quite just yet. A few things to work through.

**Comment by afebbraro** [comment]
setup!
