### ISSUE TITLE
Storybook for Spark React

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1270]
This is for Epic: Spark Code Restructure

**User Story:**
As Spark we want to Get Gatsby, Storybook and Nitlyfy Running for Spark React so that ...

**Notes:**

**AC:**
- Gatsby will be running for Spark React
- Storybook will be running for Spark React
- Nitlyfy will be running for Spark React

**Comment by afebbraro** [comment]
Just a few stories left to flesh out for this. The react storybook is up and running.
