### ISSUE TITLE
Port over 3 Components/Create base folder structure for Vanilla

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1271]
This is for Epic: Spark Code Restructure

**User Story:**
As Spark we want to port over Vanillas top three components so that ...

**Notes:**
What are our top 3 components for Spark Vanilla?

**AC:**
- Create base folder structure for Gatsby 
- 'Component' will be ported over
- 'Component' will be ported over
- 'Component' will be ported over

**Comment by afebbraro** [comment]
Complete! Pushed up this work in a new branch on the team repo called "new-docs-site".
