### ISSUE TITLE
Port over Top 3 Components/Create base folder for React

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1273]
This is for Epic: Spark Code Restructure

**User Story:**
As Spark we want to port over Reacts top three components so that ...

**Notes:**
What are our top 3 components for Spark React?

**AC:**
- 'Component' will be ported over
- 'Component' will be ported over
- 'Component' will be ported over

**Comment by afebbraro** [comment]
done
