### ISSUE TITLE
[Enhancement] Angular Masthead Experience

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1293]
**User Story:**
As a Angular Spark user, when I scroll down on a mobile device I want the Masthead to go away and when i scroll back up on the device I want the Masthead to appear again so that it's not taking up as much of the screen when the Help Center Mobile is displayed.

**Notes:**
This is for Angular
https://netbasal.com/reactive-sticky-header-in-angular-12dbffb3f1d3

@guern1kn did this for vanilla here: https://github.com/sparkdesignsystem/spark-design-system/pull/1382

Strategy is to detect page scroll, derive directionality (up vs. down) and then add class to masthead based on that directionality. 

**AC:**
- This will be Default
- Masthead will go away and when i scroll down on a device
- Masthead will appear when i scroll back up on the device

**Comment by guern1kn** [comment]
Merged into Staging.
