### ISSUE TITLE
[Research] Angular 7 / Animations / IE11 & MS Edge

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1320]
* Last to look at, might not be needed needed after upgrade??

**User Story:**
In IE11, animations using @angular/platform-browser/animations arent working correctly This affects Toggle, Masthead, Accordion.

**Notes:**
- Requestor: Rob/Servicing/ Jason Neal (MS Edge)
- https://angular.io/guide/browser-support#suggested-polyfills 

**AC:**
- In IE11, animations using @angular/platform-browser/animations will be working.
- Toggle will be working 
- Masthead will be working 
- Accordion will be working

**Comment by olikari87** [comment]
Having same issues. Animations trigger not working in IE11 and Edge. Think it broke after update from Angular 6 - 7. Using "@angular/animations": "7.2.14"

**Comment by ssabo1** [comment]
@olikari87 Thank you for the feedback we will get this Issue prioritized so that we can get the fix in place!
