### ISSUE TITLE
Card Improvements - React

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1348]
**User Story:**
As a React Spark we want to make React Card improvements 

**Notes:**
Requestor: RV
https://staging.sparkdesignsystem.com/patterns/components/card 

**AC:**
- Bring content div into component so sparkCard base doesn’t REQUIRE that div inside of it
- Investigate how angular does it, and make it match (Either create a proptype for additional classes, or use stack component)
- Nested proptypes in documentation will be consistent
- Card docs will follow documentation like Tables
- Remove empty default props

**Comment by afebbraro** [comment]
@RVMendoza  There are some console.errors when running React tests for Cards. Can you take a look at them in this PR?  They pass the tests, but these are thrown.

PASS src/SprkCard/components/SprkCardTeaser/SprkCardTeaser.test.js (13.944s)
  ● Console

    console.error ../../node_modules/react-dom/cjs/react-dom.development.js:506
      Warning: <Link /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
          in Link (created by Media)
          in Media (created by GetTeaserContentOrder)
          in GetTeaserContentOrder (created by SprkCardTeaser)
          in SprkCardTeaser
          in Router (created by BrowserRouter)
          in BrowserRouter (created by WrapperComponent)
          in WrapperComponent
    console.error ../../node_modules/react-dom/cjs/react-dom.development.js:506
      Warning: <Link /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
          in Link (created by Media)
          in Media (created by GetTeaserContentOrder)
          in div (created by GetTeaserContentOrder)
          in GetTeaserContentOrder (created by SprkCardTeaser)
          in SprkCardTeaser (created by WrapperComponent)
          in WrapperComponent
    console.error ../../node_modules/react-dom/cjs/react-dom.development.js:506
      Warning: <Link /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
          in Link (created by CtaLink)
          in CtaLink (created by CallToAction)
          in div (created by CallToAction)
          in CallToAction (created by GetTeaserContentOrder)
          in div (created by GetTeaserContentOrder)
          in GetTeaserContentOrder (created by SprkCardTeaser)
          in SprkCardTeaser (created by WrapperComponent)
          in WrapperComponent
    console.error ../../node_modules/react-dom/cjs/react-dom.development.js:506
      Warning: <Link /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
          in Link (created by CtaLink)
          in CtaLink (created by CallToAction)
          in div (created by CallToAction)
          in CallToAction (created by GetTeaserContentOrder)
          in div (created by GetTeaserContentOrder)
          in GetTeaserContentOrder (created by SprkCardTeaser)
          in SprkCardTeaser (created by WrapperComponent)
          in WrapperComponent
    console.error ../../node_modules/react-dom/cjs/react-dom.development.js:506
      Warning: <Link /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
          in Link (created by CtaButton)
          in CtaButton (created by CallToAction)
          in div (created by CallToAction)
          in CallToAction (created by GetTeaserContentOrder)
          in div (created by GetTeaserContentOrder)
          in GetTeaserContentOrder (created by SprkCardTeaser)
          in SprkCardTeaser (created by WrapperComponent)
          in WrapperComponent
