### ISSUE TITLE
Combine spark-extras with spark-core

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1356]
**User Story:**
As Spark we want to combine our spark-extras with spark-core so that they are one package.

**Notes:**
- once completed Spark-extras will live in spark-angular
- Spark-extras will exist no more
- Card https://staging.sparkdesignsystem.com/patterns/components/card 
- Dictionary  https://staging.sparkdesignsystem.com/patterns/components/dictionary
- Highlight Board https://staging.sparkdesignsystem.com/patterns/components/highlight-board 
- Awards https://staging.sparkdesignsystem.com/patterns/components/awards

**AC:**
- spark-core and spark-extras will be combined into one
- Card will be spark-angular
- Dictionary will be spark-angular
- Highlight Board will be spark-angular
- Awards will be spark-angular
- Docs will be update https://staging.sparkdesignsystem.com/ 
- SPARK-CORE angular will be named Spark Angular

**Comment by afebbraro** [comment]
Merged
