### ISSUE TITLE
[BUG] sprk-masthead narrow nav dropdown selector has the dropdown footer link hardcoded to "Go Elsewhere"

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1366]
**User Story:**
As a Spark Angular User, I want to be able to edit the "Go Elsewhere" dropdown footer link in sprk-masthead so that it's flexible for users to edit.

**AC:**
- Users will have the ability to choose if they want a footer link
- Users will have the ability to  choose text and href ETC should be.

**Comment by ssabo1** [comment]
merged.
