### ISSUE TITLE
Font size applied incorrectly to html elements

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#1374]
## Describe The Bug
`<strong>` and `<small>` are being tied to specific font sizes.

## To Reproduce
1. Apply the `<strong>` or `<small>` elements to text within an element that has a font size set, for instance, a heading.
2. The font size of the heading will be overridden by the explicit font size of the `<strong>` or `<small>`

## Expected Behavior
`<strong>` and `<small>` shouldn't be linked to specific Spark type levels

**Comment by ssabo1** [comment]
Pushed. https://github.com/sparkdesignsystem/spark-design-system/releases/tag/may-3-2019
