### ISSUE TITLE
spark-react: Port over remaining components

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1398]
**User Story:**
As Spark we want to reproduce what we currently have on the doc pages into Story book pages so that we port over all components.  

**Notes:**
This is for React

**AC:**
- reproduce what is in the doc pages into Story book pages.

**Comment by afebbraro** [comment]
This just needs modals, pagination, icons, stepper (still in development) and some of the layout objects from the Layout page.

**Comment by afebbraro** [comment]
And then, we can add in storybook actions and storybook knobs as we like.

**Comment by ssabo1** [comment]
Broke into smaller Issues.
