### ISSUE TITLE
research + implement for Angular: can we make a CLI tool that will update all old angular module imports

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1408]
Can we make a CLI package that could be installed by dev teams that will go through the codebase and automatically update all refs to SparkModal (for example) to the new SprkModal import naming?

it would need to:
1. search entire repo for mentions of SparkComponentName and replace it with SprkComponentName

thoughts:
- would this be a bad idea?
- is this worth creating vs. having dev teams do it on their own?
- could this have harmful side effects?

**Comment by 13protons** [comment]
This could work...but it also might make sense just to warn people. Could be structured as a CLI, or possibly as an ESLint plugin

**Comment by ssabo1** [comment]
Too Late to complete.
