### ISSUE TITLE
[Bug] Links or Components with Links - Angular 

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1430]
**User Story:**
As Spark we want to Require NG router and or figure out how to fail gracefully so that we do not break links in the code. 

**Notes:**
As Spark, when we released angular NEW the code breaks when users do not have NG router installed
This will effect any Links or Components that use links.
-  Alan talked to Jack and Moshe and they're saying they can't upgrade to spark 12 because of the ng router bug in our link component.

**AC:**
Suggestion: 1. Require NG router or 2. Figure out how to gracefully handle NG router not there.

**Comment by 13protons** [comment]
@RCopeland  and @13protons  to break down further. The rabbit hole is deeper than we throught.

**Comment by ssabo1** [comment]
Wont fix with this component but Spark will provide a new directive that will solve this bug. #2825 and #2832
