### ISSUE TITLE
research how to pull variable documentation out of sass

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1439]
JSDocs was mentioned

**Comment by 13protons** [comment]
http://sassdoc.com/

**Comment by 13protons** [comment]
Not too shabby - sassdoc can be run in "parse" mode, which scans comments and pulls them out into a JSON file, with output like this: 

```
{
    "description": "\n",
    "commentRange": {
      "start": 225,
      "end": 225
    },
    "context": {
      "type": "css",
      "name": ".sprk-b-TableHighlight",
      "value": "background-color: $sprk-table-highlight-color !important;\n  color: $sprk-table-highlight-text-color !important;",
      "line": {
        "start": 226,
        "end": 234
      }
    },
    "access": "public",
    "group": [
      "undefined"
    ],
    "file": {
      "path": "_tables.scss",
      "name": "_tables.scss"
    }
  },
```

The task to make this useful would be to 1) put useful docs in our sass comments and 2) write a gatsby component that could render them by path

**Comment by 13protons** [comment]
Future work would be figuring out how we want to use these annotations to describe our stylesheets: 

<img width="979" alt="Screen Shot 2019-07-01 at 4 54 09 PM" src="https://user-images.githubusercontent.com/1456258/60466166-f41df000-9c20-11e9-8acd-6909055aa100.png">
<img width="941" alt="Screen Shot 2019-07-01 at 4 53 11 PM" src="https://user-images.githubusercontent.com/1456258/60466167-f41df000-9c20-11e9-941b-cf5afd3ab12c.png">
<img width="970" alt="Screen Shot 2019-07-01 at 4 53 07 PM" src="https://user-images.githubusercontent.com/1456258/60466169-f41df000-9c20-11e9-9502-3303b16a8e18.png">

**Comment by 13protons** [comment]
> Not too shabby - sassdoc can be run in "parse" mode, which scans comments and pulls them out into a JSON file, with output like this:
> 
> ```
> {
>     "description": "\n",
>     "commentRange": {
>       "start": 225,
>       "end": 225
>     },
>     "context": {
>       "type": "css",
>       "name": ".sprk-b-TableHighlight",
>       "value": "background-color: $sprk-table-highlight-color !important;\n  color: $sprk-table-highlight-text-color !important;",
>       "line": {
>         "start": 226,
>         "end": 234
>       }
>     },
>     "access": "public",
>     "group": [
>       "undefined"
>     ],
>     "file": {
>       "path": "_tables.scss",
>       "name": "_tables.scss"
>     }
>   },
> ```
> 
> The task to make this useful would be to 1) put useful docs in our sass comments and 2) write a gatsby component that could render them by path

@RCopeland @afebbraro do you see any issues with consuming the JSON file qutoted above in Gatsby?

**Comment by 13protons** [comment]
...actually even better!
http://sassdoc.com/node/#using-raw-data

<img width="955" alt="Screen Shot 2019-07-02 at 11 50 00 AM" src="https://user-images.githubusercontent.com/1456258/60527084-912f6600-9cbf-11e9-992a-83e85ae6e989.png">

**Comment by ssabo1** [comment]
Follow up to this: https://github.com/sparkdesignsystem/spark-design-system/issues/1549
