### ISSUE TITLE
[Enhancement] Update Mobile Masthead - React

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1461]
**User Story:**
As a Spark React User, when on a mobile device I want to see Sign In and Sign Out in the Masthead to the right of the logo.

**Notes:**
- This is for Mobile
- This is for React
- Request comes from Design and Brand on 6/7

**AC:**
Mobile:
- Pre-sign In: Sign in will appear to the right of the logo when you open the hamburger menu.
- Post-sign in: Sign out will appear to the right of the logo when you open the hamburger menu 
- I will still see Sign In button at the bottom of the hamburger menu.

**Comment by guern1kn** [comment]
Completed with pull request #1464 being merged into staging.
