### ISSUE TITLE
Test Spark with Angular 7 and Upgrade 

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1474]
**User Story:**
Upgrade Spark to Angular 7

**Notes:**
 * ~~New Issues will come out of this~~
 * All manual testing stories for upgrading to Angular 7 are dependent on this, so do it first!
- Pair with @13protons when working on this Issue.

AC:
* Create a new branch of spark that uses Angular 7
   - Try to follow the angular 6-8 upgrade guide https://update.angular.io/#6.0:8.0
   - possibly upgrade to 7 first (will be discovered in research)
* Verity that angular test app loads (or doesn't)
* Get test app into a usable state even if individual component are broken
    - fix build time errors, but not run time errors at this stage
* Push branch up for others to test against

**Comment by 13protons** [comment]
One upgrade guide - not definitive but a useful input
https://medium.com/@sendilkumarn/how-to-migrate-from-angular-6-to-7-1efc0da86d4f

**Comment by afebbraro** [comment]
I talked with Jack who has done upgrades before and he said we can go from 6 -> 8 and use this upgrade guide and it should be fairly easy https://update.angular.io/#6.1:8.0
