### ISSUE TITLE
Create Manual Testing Plan for Buttons Component

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1477]
**User Story:**
As Spark we want to create a Manual Testing Plan for our Components so that we can follow it when testing Support for Angular 7 and Angular 8.

**Notes:**
- Katie and Alan have started a spread sheet

**AC:**
- create a structure for a testing plan for Buttons

**Comment by guern1kn** [comment]
@13protons The button section is ready to be reviewed. Let me know if there's anything we should add. I had @ssabo1 create a story to add measurable click functionality and add the expected action to the test plan. If we think it's good, we can close this issue.
