### ISSUE TITLE
[Build] Floating Label for HUGE Input - Vanilla  

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1500]
**User Story:**
As Spark, we want to have a floating label for Sparks Huge Input so that the placeholder text as well as the label are both with in the Huge Input.

**Notes:**
- This is for Vanilla
- This Request is coming from Brendon 
- This is coming from the RMA UI Kit
- VALUES NEED TO MATCH CURRENT SPARK  
- this is a varient of Default 

**Design Q&As:**
Q: Animation requirements? Brendan working with Alan
Q: Do we still want a version without the label? YES
Q: Monetary/Percentage, Label is optional? visually Yes. but should always be in the back for accessibility. 

**AC:**
- I will see floating Labels on Spark Huge Input. 
- Update docs in reference to the label display or hide.
- BASE, I will see Label/Placeholder text Align Left, inside Huge Input. (Values need to Match current Spark.) (Fill: #FFFFFF 100% Boarder: 1px inside, #CFCFCF Radius: 4px)
- On FOCUS, Field will have Highlighted State. 
- On FOCUS, Text will Align left. 
- On FOCUS as cursor is placed inside input. Label will display inside Huge Input, top left corner.
- On FOCUS, Padding: Align left with 24px padding from left of the Input to the Text. 8px from the top of the Input to the Label and 12px from the placeholder text/text to the bottom of the input.
- User will be able to type into input.
- On ERROR validation, Input will have a highlighted state
- On ERROR validation, Error Messaging will display 12px below HUGE input. (Fill: #FFFFFF 100% Boarder: 2px inside, #EDA302 Radius: 4px)  
- CURRENCY, will display placeholder text, align left.
- CURRENCY, Visual label is optional to the display but label will always be in the background for a screen reader
- CURRENCY, as cursor is placed inside input. Label will display inside Huge Input, top left corner.

![image](https://user-images.githubusercontent.com/46761151/60536185-b5953d80-9cd3-11e9-84c4-00b5b41fa6d2.png)

**Comment by 13protons** [comment]
Here's a CSS only mockup to build upon: 

https://codepen.io/alanguir/pen/mZLXjN

This pen has known issues in Edge. See this compatibility chart: https://caniuse.com/#feat=css-placeholder-shown
