### ISSUE TITLE
[BUG] SprkLink doesn't work with Gatsby Link

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1503]
**User Story:**
A failed proptype warning comes up when you pass a Gatsby Link to the React SprkLink component. It has to do with the propType set for 'element' in the SprkLink component.

**Notes:**
Requestor: Amber

**AC:**
- i will not get a proptype warning when passing a Gatsby Link to the React SprkLink component

**Comment by ssabo1** [comment]
this has been fixed.
