### ISSUE TITLE
Drizzle Docs Code Show/Hide 

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#153]
Create a component for drizzle docs only to show and hide the code.

Would be nice to have for v1.

**Comment by afebbraro** [comment]
We should talk about if we still want to do this in addition to the "copy code" feature that I added. This is different than that.

**Comment by yodasw16** [comment]
The purpose of this was supposed to be to prevent super long pages that are hard to browse. I think our primary use case should be factored in here, which is devs. The use case for show/hide on each component would be to have them closed by default and openable one at a time as needed. Would a better experience be to leave them open by default and add a single show/hide switch up top that collapses everything at once?

**Comment by RCopeland** [comment]
My gut feeling is that everyone would want all the code hidden by default. Then it'll usually only be devs that will want to expand a specific code section. Even devs wouldn't want to have it all open with a single toggle probably.

**Comment by yodasw16** [comment]
I can see that. My only concern is for people to come to the site and assume they are just looking at a style guide and missing that there is code here as well.

**Comment by afebbraro** [comment]
I vote we leave the code as is - with no show or hide. If it becomes a burden for people and we get feedback on it then lets add it. Don't want to add something we might not need. I haven't heard anyone say anything about it the past few months.

**Comment by afebbraro** [comment]
closing, decided its not necessary.
