### ISSUE TITLE
[research] Modify the StepperStep component - Stepper React

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1538]
**User Story:**
As Spark, we want to modify the StepperStep component so that it can render any children that are passed in 

**Notes:**
- Spark React Stepper had been merged for the July 1st Release, but there is some outstanding work needed to complete the component.

**AC:**
- talk to design
- Follow up with PO if follow up issue is needed.
- Modify the StepperStep component so that it can render any children that are passed in 
Example, a `SprkButton` Right now it looks for text and throws an error if it finds anything else.

**Comment by 13protons** [comment]
I talked to the design team and we do not need to support additional content types within the stepper. Even if we (eventually) want to, there are bigger fish to fry
