### ISSUE TITLE
[research] Allow for stepper steps to be reordered? - Stepper React

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1540]
**User Story:**
As Spark, our React Stepper is currently using index as the `key` for the StepperSteps. This could cause the Steps to render incorrectly in situations where users are dynamically changing the number or order of steps. There is an example of this on the React test page. 

**Notes:**
- Spark React Stepper had been merged for the July 1st Release, but there is some outstanding work needed to complete the component.

**AC:**
If this is functionality we want to support
- Talk to Design.
- come back to PO, if follow up issue is needed
- need to have a required id property on StepperSteps.

---

After speaking with the Design team, we couldn't come up with any use cases in which this functionality would be required for the Stepper. As such, we have decided not to add this functionality at this time.

**Comment by bobwise** [comment]
After speaking with the Design team, we couldn't come up with any use cases in which this functionality would be required for the Stepper. As such, we have decided not to add this functionality at this time.
