### ISSUE TITLE
Build a template for showing component modifiers

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#156]
Show like a little table with modifier classes and a desc of what they do, optional for each component.

**Comment by yodasw16** [comment]
Does the table I built for utilities do this? Would still need another issue to actually put the table on components that need it, but can this one be closed?

**Comment by RCopeland** [comment]
i think that the table styles you made are probably fine for this, we could close this and make a new issue to actually go through and add it for each component that needs it.
