### ISSUE TITLE
📝 Document icon usage

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#158]
The icons page has Lorem Ipsum text as a placeholder. This should be replaced by a short description of usage.

**Comment by philrinke** [comment]
Here is the content I wrote for recommended usage for all the icons. Feel free to clean it up in any way. I also added in an introduction paragraph to help contextualize the usage of all the icons. 

**Intro:** Icons typically are used in tandem with an action that the user takes, but occasionally they can be used in an illustrative manner. The recommended usage below is meant to help frame when to use the icons when in the context of an action. When using the icon as an illustration

**Usage:**
	• Facebook - The Facebook icon is used to link to that specific social media account for a given site.
	• Bell - The bell icon is used to highlight an important action that needs to be taken.
	• Calculator - The calculator icon is used to illustrate that a calculator is behind the click.
	• Calendar - The calendar icon is used to show that the user can choose a date to schedule an event.
	• Chat - The chat icon is used to show when the chat feature is available.
	• Check - The check mark is used to illustrate success.
	• Chevron - All the chevron's should be used to illustrate the direction an action can be taken or where the user will be taken after the action is taken.
	• Clock - The clock icon should be used to indicate when something is time sensitive.
	• Cloud Download - This icon should be used when something is available to be downloaded from the cloud.
	• Cog - The cog icon typically is used to illustrate where settings can be found.
	• Computer Screen - The computer screen icon is used to show when a client can share their screen.
	• Document - The document icon shows when a document is available to the user.
	• Download - The download icon is used to show when something is available to be downloaded.
	• Envelope - The envelope icon is used to indicate when there is a message available.
	• Exclamation - This icon is used to illustrate an error or when something goes wrong.
	• Home - This icon should be used to indicate when a user can return home in the context of their experience.
	• Info - The info icon should be used to indicate that there is extra information provided to aid in the experience.
	• Instagram -  The Instagram icon is used to link to that specific social media account for a given site.
	• Lock - This icon should be used to indicate security and safety.
	• Paper Plane - Typically the paper place icon should be used to indicate the ability to provide feedback.
	• Payment - The payment icon should be used to indicate some monetary transaction.
	• Pencil - This icons should be used to indicate when something is editable. 
	• Phone - The phone icon is used to show that a phone call can be made.
	• Play - The play icon is usually used to show when a video can be initiated.
	• Plus -  This icon usually indicates when there is an expandable action or when something can be added.
	• Print - When something is printable.
	• Question - This icon should be used to indicate that there is extra information provided to aid in the experience.
	• Rocket - Only use this in an illustrative manner.
	• Bars - This icon should be used to indicate when there is a menu present especially on mobile.
	• Times - The times icon is used to show that a close/dismiss action be taken.
	• Twitter - The Twitter icon is used to link to that specific social media account for a given site.
	• Update - The update icon typically shows when a refresh action can be take.
	• Upload - The upload icon is used to show when an upload action can be taken.
Youtube - The Youtube icon is used to link to that specific social media account for a given site.

**Comment by philrinke** [comment]
I would also like the sizing to show the icons in a horizontal layout rather then vertical to help illustrate the differences.
