### ISSUE TITLE
Filled Angular Icons

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#1592]
**User Story:**
Should we alter the docs to add sprk-c-Icon--filled to the additionalClasses input, or have the sprk-icon component look for -filled in the name and add it automatically?

**Notes:**
Requestor: Rob

**AC:**
alter the docs to add sprk-c-Icon--filled to the additionalClasses input???
or
have the sprk-icon component look for -filled in the name and add it automatically???
- Implement Answer

**Comment by yodasw16** [comment]
Closing this out. Icons will be updated from Brand this Quarter.
