### ISSUE TITLE
Add search input

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#16]
There is a search input in the Masthead component that needs to be added to Inputs. It should have no label, but "Search" as a placeholder and the appropriate aria role to replace the label and role="search"

**Comment by afebbraro** [comment]
Chatted with @philrinke  and we are going to have a regular old search input in the inputs section that does have the standard label associated with it. The masthead pattern will have its own specific stylized version of this.

**Comment by afebbraro** [comment]
merged
