### ISSUE TITLE
Update side navigation component

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1602]
We want to update the side navigation component from its current state to a new state.

The new state will have:
- Remove the createPage work in gatsby-node
- The components will link off to their respective storybook pages.

**Comment by RCopeland** [comment]
![Frame (1)](https://user-images.githubusercontent.com/412903/61801252-6e92f780-adfc-11e9-9684-a57291f08416.png)
![Frame](https://user-images.githubusercontent.com/412903/61801253-6e92f780-adfc-11e9-9950-5a040f26145b.png)

**Comment by 13protons** [comment]
Adding these lo-fis so we don't loose them again

<img width="677" alt="Screen Shot 2019-07-24 at 10 36 33 AM" src="https://user-images.githubusercontent.com/1456258/61973291-bc049580-afb1-11e9-804d-98f41cff8364.png">
<img width="763" alt="Screen Shot 2019-07-25 at 9 20 28 AM" src="https://user-images.githubusercontent.com/1456258/61973293-bc049580-afb1-11e9-923c-bee38483fb78.png">

**Comment by yodasw16** [comment]
The PR for this was merged. Can the issue be closed?

**Comment by afebbraro** [comment]
This has to be redone a little bit because of storybook no longer needing mdx files with the autogenerated documentation.
