### ISSUE TITLE
Find a way to show component code for Vanilla and Angular Storybook 

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1606]
DONE
Right now, the [info](https://github.com/storybookjs/storybook/tree/next/addons/info) addon that we use for to show the code (and provide a copy button) for Spark components in Storybook only works for React. We'll need to find a way to show the component code and a copy button in our Vanilla and Angular Storybooks.

**Comment by ssabo1** [comment]
This has already been completed.
