### ISSUE TITLE
Make a Footer component for Gatsby Site

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1611]
add the npm and github links

**Comment by 13protons** [comment]
Here's some content and lo-fi design guidance for the footer: 

<img width="551" alt="Screen Shot 2019-07-25 at 11 47 18 AM" src="https://user-images.githubusercontent.com/1456258/61888693-fe56a580-aed1-11e9-8ecc-ce6aa067da18.png">

And in context:

<img width="677" alt="Screen Shot 2019-07-24 at 10 36 33 AM" src="https://user-images.githubusercontent.com/1456258/61888631-e41cc780-aed1-11e9-89f9-3f007ceffa6c.png">

**Comment by 13protons** [comment]
@afebbraro good callout on npm - probably add it to the list at the bottom

**Comment by afebbraro** [comment]
merged
