### ISSUE TITLE
Follow/successfully pass Manual Test Plan for Links

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1624]
**User Story:**
As Spark we want to follow the Manual Test plan for Links so that we can confirm Manual Test plan is up to date.

**AC:**
- Successful complete Manual Test Plan for Links

**Comment by afebbraro** [comment]
We didn't touch links, but i want to retest them to make sure the external vs. internal routing still is okay in 6,7,8.
