### ISSUE TITLE
Add timer to auto-exit the wait modal in Spark Site

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#164]
**Example: the wait modal.** 
Currently the wait modal can not be closed by design. This poses a problem for users that trigger the modal in the docs. They are forced to refresh the page. We could potentially add a button to close the modal that is designed in a way that it communicates its clearly not a part of the component.

**Comment by kalisjoshua** [comment]
Another option would be to add a timer to close it for the use after a few seconds so they have time to read the message; the message could also include, "this modal will close shortly" or something like that.
