### ISSUE TITLE
[Build] Select Box HUGE - React

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1644]
**User Story:**
As Spark we need a Select Box HUGE so that it can be used for Single questions forms. 

**Notes:**
This is for Angular
Requestor: Brendan
- Eng Design Review with Brendan prior to Code Review.  

**AC:**
- i will see a Select Box HUGE
- Select Box will display Label
- Label will Align left
- Select Box HUGE, will function as Select Box does today 
- Select Box HUGE, Open State will function as Select Box does today
- Spacing will stay the same as HUGE input without icon.
- Sizing will all stay the same ad HUGE input without icon.
- On Dropdown Selection, Label will display aligned left inside components top left corner
On On Dropdown Selection, Selection will appear below label, aligned left.

RESTRICTIONS
This Select Box input is larger than base Select Box input.
The label is hidden, but important to include so it's still accessible to screen readers.
This should only be used in a form that asks for one input at a time.

![image](https://user-images.githubusercontent.com/46761151/61969984-d20e5800-afa9-11e9-97c9-de2f55d198ed.png)

**Comment by ssabo1** [comment]
Research and MVP captured here: https://codepen.io/alanguir/pen/qBWNbgy

**Comment by afebbraro** [comment]
Taking this one from Bob since he's focused on the percentage input task.
