### ISSUE TITLE
[Bug] Filled Icons will 'not look weird' - Angular

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1672]
**User Story:**
As Spark, we want our filled icons to look cleaner than they do today so that they no longer look weird.

**Notes:**
 - This is for Angular. While upgrading Spark Angular 6 to 7, the following issue came up that are unrelated to upgrade.

**AC:**
 - Angular Filled Icons will 'not look weird'

**Comment by yodasw16** [comment]
Is this just in certain browsers? Only in Angular? Screenshots might be helpful for this one.

**Comment by ssabo1** [comment]
Closing this out. Icons will be updated from Brand this Quarter.
