### ISSUE TITLE
[Bug] Masthead content in the doc site is overlapping masthead - Angular

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1680]
**User Story:**
Masthead content in the doc site is overlapping that masthead.

**Notes:**
- This is for Angular. While upgrading Spark Angular 6 to 7, the following issue came up that are unrelated to upgrade.

**AC:**
- Masthead content on the Doc Site will not overlap masthead

**Comment by yodasw16** [comment]
Applies to the old site
