### ISSUE TITLE
[Bug] IE11 promo component - images are squished

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1682]
**User Story:**
Angular: IE11 promo component images are squished - ratio is wrong

**Notes:**
This is for Angular. While upgrading Spark Angular 6 to 7, the following issue came up that are unrelated to upgrade.

**AC:**
- Promo Component images will not be squished

**Comment by yodasw16** [comment]
This isn't an incorrect ration, it is because we are using `object-fit`, which isn't supported in ie11. I'm closing this. It's unlikely that this will become a high enough priority before ie11 support is dropped.
