### ISSUE TITLE
[Bug] Fix issue in Angular 7 / 8 with Animations (toggle, accordion, masthead accordion)

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1683]
This is a follow up from Research Bug Issue #1320 

**User Story:**
As Spark, we need to create a class to add and remove when it shows/hide. Currently In IE11, animations using @angular/platform-browser/animations are not working correctly This affects Toggle, Masthead, Accordion. 

**Notes:**
Requestor: Rob/Servicing/ Jason Neal (MS Edge)
https://angular.io/guide/browser-support#suggested-polyfills

**AC:**
- In IE11, animations using @angular/platform-browser/animations will be working.
- Toggle will be working
- Masthead will be working
- Accordion will be working

**Comment by afebbraro** [comment]
Tested in angular 7 and angular 8! Ready for code review and merge.
