### ISSUE TITLE
Build MVP for HUGE Select Box

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1686]
**AC:**
- build MVP for HUGE Select Box.

**Comment by 13protons** [comment]
MVP is here: 
https://codepen.io/alanguir/pen/qBWNbgy

and looks thusly:

![huge input](https://user-images.githubusercontent.com/1456258/63199043-987db980-c04a-11e9-9083-acf3344510e6.gif)
