### ISSUE TITLE
React floating label example missing from dev app

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1712]
**User Story:**
React floating label example missing from dev app

EDIT: This is actually netlify not deploying the latest.
### Steps to fix:
Netlify Deploy -> Settings -> Build & Deploy -> Deploy Contexts -> Make sure the staging branch deploys.

**Notes:**
This came up while testing for the 8/21/19 Release

**AC:**
- I will see React floating label example in dev app

**Comment by RVMendoza** [comment]
This is actually a netlify problem, staging is not deploying (nothing is)

**Comment by afebbraro** [comment]
@RVMendoza thanks for tracking that down. What steps did you take next to fix the deploys?

**Comment by RVMendoza** [comment]
@afebbraro updating the description!
