### ISSUE TITLE
 Accordions page in react dev app doesn't load, throws console error in ie11

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1713]
**User Story:**
Accordions page in react dev app doesn't load, throws console error in ie11

**Notes:**
This came up while testing for the 8/21/19 Release

**AC:**
- Accordions page in react dev app will load
- will not throws console error in ie11

**Comment by afebbraro** [comment]
fixed by Rob's other issue that merged.
