### ISSUE TITLE
Increase Body One/Two/Three Font Size - Typography

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1729]
**User Story:**
As Spark we want to increase our font size for Body Two so that we meet accessibility standards.  

**Notes:**
Requestor: Tommy on 8/21/19
Because of accessibility Body Two needs to be a minimum of 16px, currently state today is 15px.

**AC:**
- Body One will be 16px  
- Body Two will be 16px 
- Body Three will be 16px 
- Test Inputs
- Test doc Site Content
- Update Release Notes, not breaking but make users aware of the change.

**Comment by yodasw16** [comment]
This should also apply to Body One and Body Three.
