### ISSUE TITLE
[Bug] Fix Site Search - Chrome, Windows 10

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1731]
**User Story:**
As a Spark user, when i am on using Chrome on a Windows 10 computer then i want Algolia search to be visible. (see screenshot)

**Notes:**
- This came up during our Release demo on 8/27/19.

**AC:**
- site search will be visible when using chrome on Windows 10 on 

![image](https://user-images.githubusercontent.com/46761151/63800008-4145d780-c8db-11e9-8e35-4723725cf90c.png)

**Comment by yodasw16** [comment]
Not an issue in the new docs site
