### ISSUE TITLE
Collect Percent Icon svg

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1743]
**User Story:**
As Spark we want an engineer to get the Percentage svg from Rocket Pro typeface so that it can be used in the Spark Percentage Input. 

**Notes:**
Icon will be used for Spark Percentage Input

**AC:**
- Create Percentage Icon for Spark

**Comment by 13protons** [comment]
Let's bounce these off the design team

![percent-icon](https://user-images.githubusercontent.com/1456258/64454279-95f60900-d0b8-11e9-95f2-e4fb3ce69f3e.png)
![percent-icon@2x](https://user-images.githubusercontent.com/1456258/64454281-95f60900-d0b8-11e9-96a8-3ef7b1b51e54.png)
<img width="1354" alt="Screen Shot 2019-09-06 at 3 10 38 PM" src="https://user-images.githubusercontent.com/1456258/64454282-95f60900-d0b8-11e9-844b-dd50d5c7c28f.png">

**Comment by ssabo1** [comment]
After talking to Design we will stay consistent and use the Rocket Sans dollar sign within Sparks Percentage Input.
