### ISSUE TITLE
[BUG] React Huge Text Input in Edge doesn't check for an initial input value

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#1766]
**User Story:**
Bug: The initial value of the Huge Text Input is not checked and cached values are causing a display issue with the label because the floating label class is only added on 'input' and previously did not check for an initial value

**Notes:**
Bug in PROD with Huge Text Input. 

**AC:**
- initial value of the input will be checked
- cached values will not cause a display issues

**Comment by ssabo1** [comment]
This will be taken care of in #1767
