### ISSUE TITLE
[Write] Dictionary Docs for NDS

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#1828]
**User Story:**
As a Spark we want to write Dictionary Docs in Sharepoint Word so that we can get reviews completed and then once reviews have been completed, we can create PRs for Gatsby and Storybook and users will see helpful documentation on the New Doc Site.

**Notes:**
See Sharepoint for Content Creation and Review

**AC:**
- Review Current Documentation
- Write detailed Component Documentation in Sharepoint Word
- Framework Specific 
- Prerequisite 
- Restrictions
- Implementation 
- Links
- Component Name
- Component Description
- What the Component is used for - Usage
- What the Component is not used for - Guidelines (Info + Restrictions)

**Comment by RVMendoza** [comment]
this looks good to me, just changed some words for clarity
