### ISSUE TITLE
add code of conduct (CODE_OF_CONDUCT.md)

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#19]
`

> Adopt a code of conduct to define community standards, signal a welcoming and inclusive project, and outline procedures for handling abuse.

`
https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

**Comment by RCopeland** [comment]
@afebbraro want to try out writing a first draft?

**Comment by afebbraro** [comment]
Started a PR, waiting approvals https://github.com/sparkdesignsystem/spark-design-system/pull/56

**Comment by RCopeland** [comment]
merged.
