### ISSUE TITLE
Add information on component pages to show if we supply HTML, CSS or JS for that particular component

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#199]
ex. would be to add the "tag" with "JS" in it or maybe in the future we would add "Angular" or "React"

**Comment by afebbraro** [comment]
We will have a global site piece that shows vanilla js, angular, and react indicator of what the component is in. Once thats built out we can discuss if that fulfills this idea.

**Comment by yodasw16** [comment]
Does the code switcher close this?
