### ISSUE TITLE
[Research] Load Icons to Storybook - React

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2065]
AC:
Icons will be in Storybook

**Comment by guern1kn** [comment]
Merged PR

**Comment by afebbraro** [comment]
hey @guern1kn , I'm working on SB in IE11 and I noticed none of the icons are loading there. There aren't any console errors and I can see the <div id="sprk-icons"></div> but its empty. I'm going to reopen this issue. Can you take a look?
![Screen Shot 2019-10-11 at 8 41 13 AM](https://user-images.githubusercontent.com/2117593/66652167-0554a080-ec03-11e9-8301-e3b2e31e09db.png)

**Comment by afebbraro** [comment]
@guern1kn  hey, I remember we all talked about this issue and discovered it had something to do with accessing the netlify deploy on a computer that wasn't our dev machines. Can you paste what happened with this here? Then we can decide if we should close this issue to make a new one or if our problem is solved and we don't need this issue.
