### ISSUE TITLE
[BUG] Any Spark Input using sprk-icon-input-container goes over Masthead - Angular

### ISSUE THREAD

**Issue by guern1kn** [sparkdesignsystem/spark-design-system#2089]
## Describe The Bug
Any angular spark input using the `sprk-icon-input-container` is appearing on top of the masthead when scrolling down the page. 

## Expected Behavior
As a user, I expect the monetary input to appear under the masthead when scrolling.

## Screenshots
![image](https://user-images.githubusercontent.com/15703773/66069121-baf56480-e51c-11e9-9cd6-1841ab9e02b8.png)

## Additional Context
Potentially, the z-index is higher than the masthead.

**Comment by afebbraro** [comment]
Hey @guern1kn, I saw your comment about the z-index and wanted to share my thoughts early on while you're looking into this. None of our inputs should have explicit z-indexes set on them as there's no need for a different value other than the default. Lets sync up today and chat on this.

**Comment by afebbraro** [comment]
@guern1kn  confirmed this is ONLY happening in our most recent release in Angular.
