### ISSUE TITLE
The submenus in the wide version of the main nav dont line up right with the list item content

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#21]
<img width="289" alt="screen shot 2018-01-18 at 10 25 43 am" src="https://user-images.githubusercontent.com/412903/35105563-f4acae2c-fc39-11e7-9177-9f525cd72263.png">

**Comment by yodasw16** [comment]
I think I knew this, but chose to ignore it at the time because it was only an issue on wider max-widths than we use, but I might be wrong. This is has some tricky styles that probably need some revisiting.
