### ISSUE TITLE
[Research] When a component does not have knobs...

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2137]
**User Story:**
As Spark we need to figure out how we want to handle components that do not have knobs.

What should it look like?
Hid the Knobs Tab if there are no knobs?

**AC:**
How will Spark handel components that do not have Knobs?

**Comment by 13protons** [comment]
@ssabo1 do we have an example? Probably divider?

**Comment by ssabo1** [comment]
@13protons no example at this moment. This came up while RV was working on Card.

**Comment by 13protons** [comment]
Ok. I think we should only come up with an answer if we actually come across a use case. Otherwise, YAGNI

**Comment by RCopeland** [comment]
imho, we should leave the knobs panel visible but empty
dont like the idea of conditionally hiding nav

**Comment by RVMendoza** [comment]
![image](https://user-images.githubusercontent.com/4342363/66333016-0ab0a300-e904-11e9-933b-9425adb04315.png)
This is what it looks like right now if there aren't knobs. It's a storybook link that may confuse users.

**Comment by bobwise** [comment]
Also Actions. I think Divider has no Actions and no Knobs.

**Comment by ssabo1** [comment]
ANSWER:
If we dont have knobs, hide knob tab
If we dont have actions, hide actions tab
