### ISSUE TITLE
[bug] react SprkAlerts don't close in storybook

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#2150]
When clicking a sprkalert in react storybook it doesnt close. We need to go in and add the onDismiss prop like we have in the react dev app and in our sparkdesignsystem.com docs.

**Comment by guern1kn** [comment]
@ssabo1 Closing this out after the discussion in meta about Storybook not managing state and needing the user to pass a function to create the "close" action.
