### ISSUE TITLE
[Bug?] Take a look into accessibility check results for search input vanilla

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#2164]
<img width="1068" alt="Screen Shot 2019-10-16 at 2 42 14 PM" src="https://user-images.githubusercontent.com/2117593/66948724-3da11800-f023-11e9-9a4d-62b63abc3849.png">

**Comment by yodasw16** [comment]
#2445 is the same thing, but more broad. Closing this one.
