### ISSUE TITLE
Research: SVG Stroke Alignment

### ISSUE THREAD

**Issue by 13protons** [sparkdesignsystem/spark-design-system#2171]
## Proposal Title
Explore the mechanisms available to control SVG stroke alignment. 

What is stroke alignment, you ask? Material explains it well:

<img width="806" alt="Screen Shot 2019-10-18 at 11 39 04 AM" src="https://user-images.githubusercontent.com/1456258/67108418-6f89ba00-f19c-11e9-84a2-c0cd85c14547.png">

## Why?

Icons are being re-illustrated for use inside buttons. This involves us setting explicit stroke weights and alignments, although some quick research seems to indicate that alignment is not possible with CSS. 

We want to know if:

  1. is it possible? and
  2. how can we do it?

So that a decision can be made whether icons need their strokes to be explicitly drawn (harder) or if they can be rendered at runtime (easier for designers). 

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [x] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [x] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

**Comment by ssabo1** [comment]
Stoke Alignment are always Centered.
