### ISSUE TITLE
Enhance/Add Docs for Getting Started - HTML

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2173]
**User Story:**
As a Spark Vanilla User on the New Doc Site, I want to see HTML Docs in Gatsby so that I can read all the great documentation on the New Doc Site

**Notes:**
See Sharepoint for Content Creation and Review

**AC:**
- Review/Enhance HTML Documentation for Vanilla Getting Started
- I will see Getting Started HTML Docs in Gatsby
- Will be written as markdown.

**Comment by afebbraro** [comment]
I'm ready to review this one. Where can I find it? @bobwise @ssabo1
