### ISSUE TITLE
[Add] Docs for Getting Started - Design Principles to Gatsby

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2175]
**User Story:**
As Spark we want to add https://sparkdesignsystem.com/gettingstarted/design-principles to Gatsby. 

**Notes:**
- Dave talked to Jenn Parker both of them are on the same page to keep this page.
- no need to rewrite

**AC:**
- I will see design principles in Gatsby as it reads today.

**Comment by yodasw16** [comment]
Moving this to 2.0
