### ISSUE TITLE
[Research] Look into accessibility errors on cards from SB checker

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#2189]
**User Story:**
As Spark we want to look into accessibility errors on cards from Storybook so that we can see if there is anything we can do to clean up the errors.

**Notes:**
- Requestor: Amber, SB is reporting some accessibility errors with some of the card variants. We should take a look into these and see if there's anything we could do. Some appear to be issues with the color contrast and might require work with a designer. I wanted to log this issue so we don't lose sight of it. 
- This is a research issue. If the fix is longer than the day of research, work with PO for future issue.  

**AC:**
- Research into Storybook Accessibility errors on Cards
- Document if there's anything we could do for the errors.
- Once research is complete, Work with PO to create a future issue to implement the fix.

**Comment by ssabo1** [comment]
this was completed with #2444
