### ISSUE TITLE
Remove Angular Buttons Dependency on Vanilla - NDS

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2197]
**User Story:**
As Spark we want to Remove Angular Buttons Dependency on Vanilla so that they are not dependent on one another.

**Notes:**
Requester: Amber 9/22 while adding Angular Buttons to NDS

**AC:**
- Remove Angular Button Dependency on Vanilla.

**Comment by afebbraro** [comment]
Rob did this earlier in the week.
