### ISSUE TITLE
Build out new Content Structure in Gatsby 

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2203]
**User Story:**
As Spark we want to build out the new Content IA in Gatsby 

**AC:**
- Gatsby site structure matches IA work
- Gatsby has context sensitive navigation
- Gatsby site is styled
- 4 context folders / sub context folders to place mdx content in
- mdx generated content is styled like spark

**Comment by RCopeland** [comment]
merged
