### ISSUE TITLE
Dictionary issue with long strings of text

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#221]
I just noticed this when the text is long. Is this the intended behavior?
<img width="597" alt="screen shot 2018-05-11 at 8 51 47 am" src="https://user-images.githubusercontent.com/308696/39925215-bdbab176-54f8-11e8-8bbd-8995a6d485cd.png">

**Comment by RCopeland** [comment]
It's behaving like its supposed to I think. We could do break-word or truncating, but it's not really for us to decide if that's appropriate for the content. We could provide some utilities to be used, maybe mention it in the docs?

**Comment by RCopeland** [comment]
created utility classes for break-word and for truncation
