### ISSUE TITLE
Implement SASS Docs for component pages in Gatsby

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2214]
**User Story:**
As Spark we want to implement SASS docs into the Gatsby Site so that we will have a single page with all the sass variables displayed 

**Notes:**
This is the Implementation from Research Issue: #1439
SASS DOC: a documentation system to build pretty and powerful docs in the blink of an eye
  
**AC:**
- Review #1439 
- Implement SASS doc
- Will have 1 page with all the sass variables will be there
- pages will live in gatsby
- write comments in all our sass files

**Comment by afebbraro** [comment]
Changed the estimate to a 3 because there are 1139 lines of code that I have to copy over from our old docs site to the settings.scss file where the sass comments will now live.

**Comment by afebbraro** [comment]
Otherwise, this task is going really well and was a lot of fun! And, I'm super stoked about it! Can't wait to show it off.

**Comment by afebbraro** [comment]
merged
