### ISSUE TITLE
Small screen masthead

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#222]
Some goofy stuff with the breakpoint and the points where the docs don't have enough room for the masthead.

<img width="582" alt="screen shot 2018-05-11 at 9 00 02 am" src="https://user-images.githubusercontent.com/308696/39925446-b6c82032-54f9-11e8-8307-9085df92bf7d.png">

Also, when you make the screen small enough to see the mobile nav it prevents scrolling when you expand the menu. Not an issue on mobile, but on desktop at a small screen size.

**Comment by RCopeland** [comment]
That's what supposed to happen when there isnt enough room. The secondary nav wraps on the left edge. For the docs I could bump up the size of the breakpoint, but then users wouldnt see that behavior.

**Comment by RCopeland** [comment]
Same for the scrolling, in an app it takes over the viewport, so we disable scrolling on the body. I could use a utility class or something to prevent it from happening in the docs maybe.

**Comment by yodasw16** [comment]
As long as that's the intended behavior, i'm fine with leaving the first bit. The second isn't a show stopper or anything, but on a desktop computer it felt a little weird to not be able to scroll down to actually see the menu because I clicked it while it was already way at the bottom.

**Comment by RCopeland** [comment]
yeah, i think thats weird too. The js for the masthead is what adds that behavior, so I'm not sure how to make it not happen on the docs site. Maybe a drizzle- utility class that overrides the overflow hidden or something. I'll take a look.

**Comment by RCopeland** [comment]
created an override so that on spark site pages, sprk-u-Overflow--hidden on body wont do anything.
