### ISSUE TITLE
Set up sprk-table to render correctly

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2222]
**User Story:**
As Spark, We want sprk-table to render correctly on the page so that our Image and Code sample are correct on the doc site.

**Notes:**
This is for NDS
Requestor: Katie 10/24
class name: boarder modifier, sprk-b-Table--bordered

**AC:**
- remove the extra table classes in the sprk-table angular component
- sprk-table will render correctly on the page

**Comment by ssabo1** [comment]
Design change or Bug Fix??? @yodasw16

**Comment by guern1kn** [comment]
Two follow up issues were created after discussion with Rob and Amber.
#2758 && #2759
