### ISSUE TITLE
Update Angular Code for Radio and Checkbox Inputs

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2223]
**User Story:**
As a Spark Input User, When I select the Radio Button Code and or the Check Box code then I want the code to include the ability to select the text on input selection (not just the Radio or Check).

**Notes:**
- Requestor: RV 10/24 
- https://github.com/sparkdesignsystem/spark-design-system/blob/mono-split/angular/projects/spark-angular/src/lib/components/inputs/sprk-input-container/sprk-input-container.component.ts#L50
- selection input container

**AC:**
- when i copy radio button code user will have the ability to select the icon or text to select. 
- when i copy checkbox code user will have the ability to select the icon or text to select.

**Comment by yodasw16** [comment]
I can't reproduce this.

**Comment by ssabo1** [comment]
fixed.
