### ISSUE TITLE
Build Search into the New Doc Site

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2226]
**User Story:**
As Spark we want to add a Search to the NDS that gives users the ability to search Gatsby and all 3 Storybooks.

**Notes:**
Research Issue: #2225 

**AC:**
- Search will be functioning on the New Doc Site
- Search on the NDS will search Gatsby and all 3 Storybooks.

**Comment by RCopeland** [comment]
merged
