### ISSUE TITLE
No way to dismiss the "Wait" modal in the docs

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#223]
Should think of a way to close it while making it clear that it isn't only closable in the docs.

**Comment by afebbraro** [comment]
I made this issue for this but i didn't relate it to modals specifically so thats probably why you missed it. But, I can't think of any other thing that would need this pattern right now. https://github.com/sparkdesignsystem/spark-design-system/issues/164

**Comment by yodasw16** [comment]
Ah yes. My bad.
