### ISSUE TITLE
Update Choice Modal - React 

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2264]
**User Story:**
As Spark we want React Choice Modal to function they way it does for Angular and Vanilla so that we are consistant.

**Notes:**
Requestor: RV
Works correctly in Vanilla and Angular.

**AC:**
- When I land on React doc page Choice Modal, then i will see a button 'Open Choice Modal'
- Once i select the button then the modal will display. 

Todays Current State:
![image](https://user-images.githubusercontent.com/46761151/67898195-3c4d1080-fb36-11e9-92f1-3a9b28a8b966.png)

**Comment by guern1kn** [comment]
@ssabo1 Closing this - not needed after further discussion about user interaction and managing state.
