### ISSUE TITLE
Fix Stepper in Storybook all 3 frameworks - NDS

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#2299]
**User Story:**
As Spark we want to fix Stepper iFrame Issue in storybook for all three frameworks.

**Notes:**
- iframe issue - katie has a fix for.
- Requestor Amber: Stepper in react is missing dark background story, Bob: "I set that up with hasDarkBackground as a knob and not a story because hasDarkBackground is a property, not a variant. https://spark-sb-react.netlify.com/?path=/story/components-stepper--with-step-descriptions
- Stepper in vanilla has a visual error with the dark background story
https://spark-sb-html.netlify.com/?path=/story/components-stepper--with-dark-background

**AC:**
- Stepper will not be broke in HTML
- Stepper will not be broke in Angular
- Stepper will not be broke in React
- React Stepper will have a Dark Background
- Vanilla Stepper will not have a visual error with the dark background.

**Comment by ssabo1** [comment]
Will be cover in #2446
