### ISSUE TITLE
Add copyright to NDS footer

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#2308]
**User Story:**
As Spark we want to add the following copyright information to our NDS footer.

AC:
* This text should be present in the footer of the NDS
    * ©2000 – 2020 Quicken Loans Inc. All rights reserved.

**Comment by ssabo1** [comment]
![image](https://user-images.githubusercontent.com/46761151/69966818-29d34780-14e5-11ea-84f5-a623553106cd.png)
Do we need address? 
Copywrite?

**Comment by yodasw16** [comment]
I reached out to Jenn about this and will update when I have an answer.
