### ISSUE TITLE
Improve documentation for accordions

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#232]
The use case for secondary accordions isn't super obvious. We should make it more clear.

**Comment by philrinke** [comment]
Here is the content I think should be added to the accordion page for usage:

The main difference between the primary and secondary accordion is highlighted by their visual design. Both share the same functionality and guidelines that have been included in the documentation. 

A primary accordion should be used when content needs to be broken down, but is still important enough to be of primary interest on the page. This accordion's design is used to give it some visual weight within the design and make it apparent that the content is important.

The secondary accordion is still used to break up content into more digestible chunks, but does not carry as much importance within the overall layout.
