### ISSUE TITLE
SSN Input Pattern

### ISSUE THREAD

**Issue by kalisjoshua** [sparkdesignsystem/spark-design-system#233]
I think you should make a small change to the SSN input pattern to enforce consistent separator use; as it is now, it will allow for a mix. The pattern:

```
(^(?!666|000|9\d{2})\d{3}[- ]{0,1}(?!00)\d{2}[- ]{0,1}(?!0{4})\d{4}$)|^$
```

... should be changed to:

```
(^(?!666|000|9\d{2})\d{3}([- ]{0,1})(?!00)\d{2}\1(?!0{4})\d{4}$)|^$
```

I made a CodePen to show this working; https://codepen.io/kalisjoshua/full/LmJpNd.

Let me know if I can help.

**Comment by RCopeland** [comment]
thanks, i'll take a look

**Comment by RCopeland** [comment]
@kalisjoshua adding the mismatched selectors to my tests. It fails on matched though, 123-23-1234 fails with this regex.

**Comment by RCopeland** [comment]
(^(?!666|000|9\d{2})\d{3}([- ]{0,1})(?!00)\d{2}\1(?!0{4})\2\d{4}$)|^$ 
adding in the second capture group again sorted it out

**Comment by RCopeland** [comment]
updated in staging.
