### ISSUE TITLE
Build Spacing into Storybook - NDS 

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2333]
**User Story:**
As Spark we want to Build Spacing into Storybook for the New Doc Site.

**Notes:**
Spacing will live in Storybook & Gastby #2302 
https://sparkdesignsystem.com/patterns/fundamentals/space

**AC:**
- Spacing will live in Storybook NDS

**Comment by RCopeland** [comment]
merged
