### ISSUE TITLE
[Research] Selecting Logo in Masthead will take user to 'homepage URL' - IE 11

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2338]
Do we have a workaround for them right now?? 

User Story:
As a Spark user using the Masthead Component in Internet Explorer, When I select the Logo in the masthead I will be taken back to the Homepage so that we are giving the user an expected experience.

Notes:
Requestor: Hayli Ziegler 10/30/19
This is Blocking: 

**AC:**
- Give PO Hayli Zigler a workaround

**Comment by afebbraro** [comment]
Steph said this is an issue with Angular and that Dave confirmed it is a Spark bug.

**Comment by ssabo1** [comment]
Amber 11/11/19: Dug into this a little bit and have some information for you for awareness around how long this has been a bug. What frameworks it affects and what is causing it.

Bug in production since: July 1st, 2019

What's causing it?: It is the addition of these two lines of code: https://github.com/sparkdesignsystem/spark-design-system/pull/1464/files#diff-c74d077e3981fdced5ed40320a8cc0bdR107, and https://github.com/sparkdesignsystem/spark-design-system/pull/1464/files#diff-c74d077e3981fdced5ed40320a8cc0bdR92, We can't use the flex shorthand settings because of unexpected results in IE11 when it comes to flex basis settings.

Additional Info: There's more to this bug than just this issue (although the other issue is visual and not functional) This has a bit of a ripple effect that causes the masthead selector to not be laid out correctly. See screenshot attached.

Fix for now (maybe? they would need to check it in their environment with their custom situation): Apply flex-basis: auto to the sprk-c-Masthead_branding div and the sprk-c-Masthead_nav-item div. This "fix" could not work depending on their situation. For us, we need to remove these custom flex CSS values and redo the layout using Stack which has been setup to work in IE11. The masthead already uses stack mostly besides these custom setting.
