### ISSUE TITLE
[Enhance] Spacing in Storybook

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2350]
**User Story:**
As Spark we want to update our SB Spacing Page to remove our doc specific classes from the rendered HTML users are copying

**Notes:**
Comes out of grooming 11/14/19

**AC:**
- Remove our doc specific classes from the rendered HTML users are copying
- link to utilities at the top of the page.

**Comment by RCopeland** [comment]
merged
