### ISSUE TITLE
Figure out displaying the prop config objects in SB component page docs

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2355]

**Comment by afebbraro** [comment]
PR is ready for review to solve this for React. For Angular, I created an issue on SB https://github.com/storybookjs/storybook/issues/8959 and in the meantime, we need to do a few things to Spark. 

One of them I talked about with Dave and Alan yesterday, and it involves creating types for Angular Inputs. Which, I identified as a necessary code improvement for our Design System. Right now we have our array Inputs marked as type `any[]` when we actually have a specific shape that we are looking for. I want to take on this task of creating these typescript interfaces and in looking through the Angular codebase, there are only are 7 - 9 of them that need to be created and I made one already (for testing). These are also only inside 4 different components that I see, Card, Masthead, Dropdown and Footer. I would like a task to add these interfaces to these four components. Then, if SB accepts my issue, all we have to do is update and we will get the documentation for the props automatically. In the meantime, I can add documentation for the shape of those 7 - 9 props manually in the Angular SB via some markdown. I suggest we add it to the bottom of the SB docs page OR at the top. 

One example I made here for review here:
```
export interface NarrowNavLinks {
  /**
   * The text for the link.
   */
  text: string;
  /**
   * The `href` value for the link.
   */
  href: string;
  /**
   * Optional sub-navigation for the link.
   */
  subNav?: Array <{
   /**
    * The text for the sub-navigation link.
    */
    text: string
    /**
     * The `href` for the sub-navigation link.
     */
    href: string
    /**
     * The icon name supplied will
     * be used to render
     * the specified icon to the
     * left of the sub-navigation link text.
     */
    leadingIcon?: string
  }>;
  /**
   * If `true`, denotes that the link
   * represents the current page.
   */
  active?: boolean;
  /**
   * The icon name supplied will
   * be used to render
   * the specified icon to the
   * left of the link text.
   */
  leadingIcon?: string;
}

```

**Comment by afebbraro** [comment]
This is done for React, for angular, see the new issue #2379
