### ISSUE TITLE
- Figure out how to pass a directive as the component in SB so that the component proptables can display for our inputs, buttons and other components that are built as directives in Angular.

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2356]

**Comment by afebbraro** [comment]
I got the research done for this one. Will chat IRL about it.

**Comment by afebbraro** [comment]
Made an issue on Storybook for this here: https://github.com/storybookjs/storybook/issues/8920

**Comment by afebbraro** [comment]
Just waiting till this gets reviewed. Moving this to this in review and then depending on what happens we can update this issues here.

**Comment by afebbraro** [comment]
PR has been approved by one reviewer and waiting on the second now!

**Comment by afebbraro** [comment]
Closing as this has been approved by SB!
