### ISSUE TITLE
Update Dependencies and README once more, then mark the release

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#236]
npm packages, not meaning drizzle.

**Comment by afebbraro** [comment]
Dep updated today per https://github.com/sparkdesignsystem/spark-design-system/pull/255

**Comment by afebbraro** [comment]
Deps updated today again and merged into staging.

**Comment by afebbraro** [comment]
updated today https://github.com/sparkdesignsystem/spark-design-system/pull/361/files

**Comment by afebbraro** [comment]
updated today again, https://github.com/sparkdesignsystem/spark-design-system/pull/368/files
