### ISSUE TITLE
[Research] Can we get rid of that "No component found" at the bottom there in SB docs panel?

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2385]
**User Story:**
As Spark, we want to see if we can get rid of the "No component found" at the bottom there in SB docs panel.

**Notes:**
- this was created after testing SB on 11/22

**AC:**
- Research if we can get rid of that "No component found" at the bottom there in SB docs panel.
- If we can, Work with PO to create new Issue.

**Comment by afebbraro** [comment]
In researching this, I couldn't replicate the issue anymore. In talking with @yodasw16, I mentioned another issue that I discovered while researching this thats similar to this one. Dave gave me the permission to submit a PR onto storybook to fix it and said to work with @ssabo1  to create an issue for it when she gets back into office. The issue and the details of the problem are here. https://github.com/storybookjs/storybook/pull/9268

**Comment by yodasw16** [comment]
Is there anything to review here or can this just be closed?
