### ISSUE TITLE
Add Error and Disable validation to each Input - Vanilla

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2387]
**User Story:**

**Notes:**
Implement Research from #2331 
This is for Vanilla
Angular + React = #2410 and #2409
Future Issue: guide: how to hook up our inputs (gatsby guide)

**AC:**
- Decouple 
- Add a story for Error for each Input
- Add a story for Disable for each Input

**Comment by RCopeland** [comment]
merged
