### ISSUE TITLE
Add comments to the scss files for the class modifiers - layout objects: box, stack, flag.

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2392]
**User Story:**
As Spark we want to add comments to the SCSS Files for Class Modifiers.

**Notes:**
Requestor: Katie after building #2374 

**AC:**
- add comments to the scss files for box class modifiers. 
- add comments to the scss files for stack class modifiers. 
- add comments to the scss files for flag class modifiers.

**Comment by afebbraro** [comment]
could break it out:
-     layout objects, box, stack, flag
-     accordions / alerts
-     button, card, dictionary and dropdown
-     highlight board, icons
-     inputs and links
-     lists, masthead, modal
-     pagination, promo, stepper
-     tabbed nav and table
