### ISSUE TITLE
[Research] Putting the documentation link in the config file

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2393]
**User Story:**
Research putting the documentation link in the config file. 

There is a link that reads
For design and usage information check out the [documentation.] and it links to the gatsby site. Currently, it has to be in every story file. Want to see if there's a way to add it to the config file and have it show up on every docs page. 

**Notes:**
Requestor: Katie 12/4/19
a start to the research https://github.com/storybookjs/storybook/blob/ead1e3d7ed78e1f1c4fccea4768064324c040d67/docs/src/templates/_docstemplate.jsx

**Comment by guern1kn** [comment]
Was able to get Title and link to show in the Docs page by adding it to the config, but could not figure out how to get the title from being shown by passing in the {children} value.
![image](https://user-images.githubusercontent.com/15703773/71623657-3c0bd880-2bac-11ea-81a6-dec53f9c1c25.png)
![image](https://user-images.githubusercontent.com/15703773/71623661-4037f600-2bac-11ea-8e2d-ccabaf1d390a.png)
