### ISSUE TITLE
Date Format 

### ISSUE THREAD

**Issue by danielgsims** [sparkdesignsystem/spark-design-system#240]
Should the date support short formats like 1/1/2018? 1/1/18? Short hand would only be able to work if the slashes were included to avoid ambiguous dates like 11/1/18 and 1/11/18?

Either way, we can improve the regex to include (mostly) valid dates. For example, currently 99/99/9999 is valid. This regex below improves what we already require, and doesn't address the optional 0 issue.

```
/^((0[1358]|1[02])\/?(0[1-9]|[12]\d|3[01])|(0[469]|11)\/?(0[1-9]|[12]\d|30)|02\/?((0?\d)|[12]\d))\/?[12]\d{3}$/
```

This regex covers that months have the correct number of days.

Breaking it up to make sense, the pieces mean:

```
(0[1358]|1[02])\/?(0[1-9]|[12]\d|3[01])
```
This covers months with 31 days. You have to have 01,03,05,08 with an optional /, followed by 01-31. 

```
(0[469]|11)\/?(0[1-9]|[12]\d|30)
```
This covers months with 30 days. You have to have 04,06,09,11 followed by 01-30, with an optional slash.

```
02\/?((0?\d)|[12]\d
```
This covers February. It requires 02, with an optional slash, followed by 01-29. We have to include the 29th for every year, or else require a lot more logic covering which years are leap years.

```
[12]\d{3}
```
This is the year bit. which covers 1000-2999. 

Here's a link to the regex with a bunch of test cases: https://regex101.com/r/DfAS9K/1

To generate a list of values for testing, which includes negative cases, you can run this php script.

```
<?php

function fmt($y) {
 return $y <= 9 ? "0" . $y : $y;
}

function sep($v) {
  return $v ? "/" : "";
}

for ($s = 0; $s <= 1; $s++) {
for ($m = 0; $m <= 99; $m++) {
  for ($d = 0; $d <= 99; $d++) {
	echo fmt($m) . sep($s) . fmt($d) . sep($s) . "2012" . PHP_EOL;
  }
}
}
```

**Comment by danielgsims** [comment]
@kalisjoshua - Do you know a good way to tackle consistent slash operators in this regex? I could only think to duplicate the regex and require slashes in one, and not the other, or use lookbehind assertions, which aren't supported until ES2018.

**Comment by kalisjoshua** [comment]
@danielgsims take a look at #233 for consistent separator syntax. It boils down to:

  1. Capture the first separator; technically this could be any character but for a date there should only be a few acceptable characters
  2. Use the captured character for the second place

**Comment by kalisjoshua** [comment]
That's a good point. Splitting up the matching groups might be problematic for enforcing consistent separators; conflicting restrictions maybe. For regex it is always advisable to have a robust set of tests and document any known limitations.

**Comment by RCopeland** [comment]
updated in staging, kept the two-digit date format.
