### ISSUE TITLE
Clean up horizontal space on our Doc Pages - NDS Mobile

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2405]
**User Story:**
As Spark we do not want to see so much horizontal space on our React Doc Pages - NDS Mobile

**Notes:**
Requestor Rob when testing NDS

**AC:**
- I will not see so much horizontal space on our React Doc Pages - NDS Mobile

**Comment by ssabo1** [comment]
@RCopeland need more deets. Is this because your phone is small?

**Comment by RVMendoza** [comment]
Put out an issue on storybook.
https://github.com/storybookjs/storybook/issues/9629

**Comment by RVMendoza** [comment]
@ssabo1 should we close this? It's a bug in storybook and I proposed an issue already storybookjs/storybook#9629
