### ISSUE TITLE
Add comments to the scss files for the class modifiers - inputs & links

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2416]
**User Story:**
As Spark we want to add comments to the SCSS Files for Class Modifiers.

**Notes:**
Requestor: Katie after building #2374 

**AC:**
- add comments to the scss files for INPUT class modifiers. 
- add comments to the scss files for LINK class modifiers.

**Comment by guern1kn** [comment]
Issue created for Input Table to render #2487
