### ISSUE TITLE
Replace/Update Spark Logos across NDS

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2435]
**User Story:**
As Spark we want to replace our currently logo with a new logo so that we can see if it looks better.

**Notes:** 
Requestor: RV while testing SB. "Not sure what we're going for there but our spark logo looks just thrown on on the top left." "that is a completely accurate description of the spark logo"
- Get 4 assets from Dave, 1 basic 3 framework specific

**AC:**
- search/document code for all places we use Our Spark Logo. Example: footer component uses it.
- Replace Spark Logo with a different Spark Logo across New Doc Site
- Does the new logo look better?
- Angular - will see Spark Angular Logo
- React - will see Spark React Logo
- HTML - will see Spark HTML Logo
- push up to netlify assets 
- update links in code to be the new netlify asset link.

**Comment by ssabo1** [comment]
Need to follow up with Jenn Hillard prior to creating new images.

**Comment by yodasw16** [comment]
This is now unblocked. I have all of the logos ready to go.

**Comment by guern1kn** [comment]
@yodasw16 Where might one find the assets for this?
