### ISSUE TITLE
Research/Implement: Fundamentals in HTML will live at the top of the nav - NDS Vanilla

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2436]
If this takes longer than 30min to research this will fall on the list of priorities. 

**User Story:**
As Spark, we want to move fundamentals in HTML to the top of the nav. 

**Notes:**
- Do this MVP if it's small enough to do.
- BIGGER ISSUE #2437: React & Angular are missing fundamentals. Find a solution and Implement.

**AC:**
 - fundamentals in HTML will live at the top of the nav.

**Comment by guern1kn** [comment]
Here is some information that I found on this. They added a way to sort the stories, which we currently use. But not a way to sort by the Root category. There seems to be interest in the community for it, so hopefully they will add it at some point. There were some hacky ways that people got it to work (I think?) but I couldn't get any of them to work. This seems to be the most promising, but the config wouldn't resolve the file when I tried it. 
https://storybook.js.org/docs/basics/writing-stories/#parameters

Here are related issues with discussion that I found but nothing that I could get to work.
https://github.com/storybookjs/storybook/issues/3730
https://github.com/storybookjs/storybook/issues/5827
https://github.com/axa-ch/patterns-library/issues/1444
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#storysort-option
