### ISSUE TITLE
[Research] Components with Actions and or Links

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2440]
**User Story:**
Current State: Clicking on a component that does an action, sends user to a new page where the component is by itself. 

**Notes:**
- Requestor: RV while testing SB
- Links that send user to specific URLs and the No go links 

**AC:**
- Figure out what components have Links
- Figure out what components have Actions 
- Document Components we will need to go in and fix. 
- Follow up with PO once completed to create the implement Issue.

**Comment by guern1kn** [comment]
HTML Components
- W/ Links that need to be fixed
    - Award
    - Button
        - As Link Element
    - Card
        - Teaser
        - Teaser w/ Different Element Order
        - Card Layout - Two Up
        - Card Layout - Three Up
        - Card Layout - Four Up
    - Dropdown
    - Footer
    - Highlight Board
    - Link
    - Masthead
    - Pagination
    - Promo 
        - Default
        - W/ Image
        - W/ Reversed Image

**Comment by guern1kn** [comment]
React Components
- W/ Links that need to be fixed
    - Award
    - Button
        - As A Link Element
    - Card
        - Teaser
        - Teaser With Different Element Order
        - Card Layout - Two Up
        - Card Layout - Three Up
        - Card Layout - Four Up
    - Dropdown
    - Footer
    - Highlight Board
    - Link
    - Masthead
    - Promo

**Comment by guern1kn** [comment]
Angular Components
- W/ Links that need to be fixed
    - Card
        - Teaser
    - Dropdown
        - Informational
    - Highlight Board
        - Default
    - Masthead

**Comment by guern1kn** [comment]
@ssabo1 The above comments outline what components need to have links updated/fixed.
