### ISSUE TITLE
Update Masthead selector, icon chevron down - Mobile/Angular

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2459]
This Issue can only been seen on a small viewport. If this can go down to 320px with out breaking then not an issue.

**User Story:**
Device: iPhone, safari 
Framework: SB Angular
Issue: Masthead selector, icon chevron down drops to second line in the center, there is enough room that should be to the right. 

**Notes:**
Requestor Amber while testing NDS

**AC:**
- Masthead selector, icon chevron down will drop to second line to the right (not center)

**Comment by RVMendoza** [comment]
closing this, @afebbraro mentioned we talked about this already and she reduced some of the padding, and it gets to a point where it's such a small viewport screen on docs page that we don't support below 320 anyways.

I checked this on my iphone xr and it looks fine as well
![IMG_8778](https://user-images.githubusercontent.com/4342363/73673482-ad8fe880-467c-11ea-8826-386e6c3dee6e.PNG)
