### ISSUE TITLE
Small screen fixed masthead issue

### ISSUE THREAD

**Issue by janinavelasco9** [sparkdesignsystem/spark-design-system#247]
Since the masthead is fixed to the top of the page and there is no padding on top of the body content to account for the height of the header, the content is just jumping to the top behind the header

<img width="395" alt="screen shot 2018-05-18 at 9 10 16 am" src="https://user-images.githubusercontent.com/23013396/40236526-dac5b5b2-5a7b-11e8-84d4-e54827af0546.png">
.

**Comment by RCopeland** [comment]
updated in staging
