### ISSUE TITLE
Write a Push Plan

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2556]
**User Story:**
As spark we want to write a push plan so that we have a smooth go live of the new doc site.

**AC:**
- Write Push Plan for 2/7/20 Release of New Doc Site

**Comment by RCopeland** [comment]
Before the push:

- create and deploy 'winter2020' docs site (drizzle)
- take down react and angular dev apps
- assign react. angular. and html. subdomains to sb deploys
- publish spark packages
- open master <- staging PR

During push:

- merge master <- staging PR (master build will fail, leaving existing master build in place)
- update build command
- redeploy failed build
