### ISSUE TITLE
Update Foundations and Components in Side Nav 

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2595]
**User Story:**
As Spark, 
In the side nav when you click Using Spark, we want to make Foundations and Components links. 

**AC:**
In the side nav 
when you click Using Spark, 
- Foundations and Components will be links. 
- - Foundations would just load Color
- - Components would just load Accordion.

**Comment by guern1kn** [comment]
@ssabo1 What's the use case for this? If we are going to build a Using Spark page as outlined in #2592  that opens when you click Using Spark in the main nav, which would still open the side nav with the components, what's the benefit of the Foundations link opening Color and the Components link opening Accordion?
