### ISSUE TITLE
bring flex grid into spark

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#26]
reference:
https://github.com/sparkdesignsystem/spark-design-system/blob/master/src/assets/toolkit/styles/objects/_flex-grid.scss

The sneak peek pattern doesn't work without this.

**Comment by yodasw16** [comment]
I wouldn't just bring it in. I wrote that really quickly for demo purposes and it's really fragile.

**Comment by yodasw16** [comment]
This issue is covered in https://github.com/sparkdesignsystem/spark-design-system/issues/97
