### ISSUE TITLE
[DevResearch] Components that are not on an 8 pt grid

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2625]
**User Story:**
As Spark we want to research our code to find any components/numbers that are not currently divisible by 8 so that we can make issues to update where needed to fit on an 8pt grid system.

**Notes:**
UX Request

**AC:**
Research what component are not on an 8pt grid.
- UX what are we seeing? Why the request?
- Search the code, all numbers should be divisible by 8 - height and width. 
- What is the lift to get each component (that is not) onto a 8pt grid?
- Spacing
- Padding
- Fonts

**Comment by guern1kn** [comment]
Files to look at further: 
_datepicker.scss

**Comment by guern1kn** [comment]
@ssabo1 We will need to go through these as a team and decide what we need to change and what needs design review before changing it.
