### ISSUE TITLE
Bug List NDS- from amber

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2656]
**Fix List:**
- the award images look weird, can we put in some other images for the award, can we get a generic award photo from content team. Dave said we can prob get an image from the DAM. But, could ask the designers or something?
- highlighted header card in NDS, the iframe is too short
- dictionary iframes not loading in NDS
- use other images in footer besides the dang spark logo repeatedly
- highlight board iframe needs a wider width in NDS
- default masthead iframe not loading in NDS

**Comment by guern1kn** [comment]
@afebbraro For the "highlighted header card" iframe issue - what browser/screen size? Mine seems to be auto height and fine.
