### ISSUE TITLE
Add Redirects for NDS

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2669]
**Notes:**
Requestor: Amber

**AC:**
- Make a List of what the Redirects are (list of URLs)
- Set up Catch Alls for Redirects
- keep reference to current Spark Site
- redirecting users using the old URLs on spark to the new URLs for spark.

**Comment by afebbraro** [comment]
Here's the netlify docs on redirects for more info!! https://docs.netlify.com/routing/redirects/
