### ISSUE TITLE
[Bug] Extra drop shadow on mobile

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2730]
**Bug:**
Look into the Spark Masthead for React.  An existing bug is adding an extra drop shadow on mobile. It's at least showing up in the spark react starter app.

**Notes:**
Requestor: Katie, 
Its occurring in spark-react versions 1.2.1 & 1.3 for sure. Haven't tested further back than that.

**Comment by RCopeland** [comment]
wasnt a bug in spark, was a setting in react starter app, fixed there.
