### ISSUE TITLE
[Bug] If formatted value has a comma in it, the input value is cleared and a console warning is logged.

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2764]
**User Story:**
There are two bugs when using sprkFormatterMonatery and pattern-based validation:

Bug 1: #2763 

Bug 2: If the formatted value has a comma in it, the input value is cleared and a console warning is logged. Try typing "1234.567" then tabbing out. Maybe something with the regex in the formatter not matching the regex in the validator?

**Notes:**
This from a Support Request that came in on 2/6/2020
This comes after Research Issue: #2756

**AC:**
- Research then work with PO for Fix Issue / points

**Comment by afebbraro** [comment]
I'm not able to replicate it currently by following this steps on this issue. I might be missing something. Will double check with @bobwise

**Comment by bobwise** [comment]
This one can be closed. This error was happening because the input was decorated with `type="number"`, which cannot display a formatted currency string. Our stories already have `type="text"`, but I also added a line to the docs to make it clear why `type="number"` is necessary in this case.
