### ISSUE TITLE
We need to confirm that a component that exists in spark is being exported.

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#2799]
**User Story:**
Issue: If the component is not exported, it's not truly usable by consumers, so we need protections against accidentally not exporting.

**Notes:**
ALL FRAMEWORKS

**AC:**
- how can we tell what we are exporting and what we are not exporting.
- auto run pre commit check
- figure out how to do this.

**Comment by guern1kn** [comment]
After research and discussion with @afebbraro @RCopeland and @bobwise the upfront work and maintenance of this tooling is more than the benefit. Closing the issue.
