### ISSUE TITLE
[DevReserach] Get Angular Input Validations working in Storybook

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2816]
**User Story:**

**Notes:**
Requestor: Spark during Stand Up prior to fixing validation bug. #2763
Once this is done, our Storybook environment will be set up to be a more useful development environment, and I will be able to use Storybook to debug and fix the Angular Monetary input

**AC:**
Min 
Max
...

**Comment by bobwise** [comment]
validators were already working; I was just using a broken regular expression
