### ISSUE TITLE
Bring Spark site (drizzle) test coverage up to 100%

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#285]

**Comment by afebbraro** [comment]
I have a PR up to add a new modals.js file to Spark site. The unit tests i wrote for it are at 100% and it brings spark site up to 64.04%. That PR also brings in Sinon. Please rebase this work once that PR is merged. PR is here https://github.com/sparkdesignsystem/spark-design-system/issues/164

**Comment by afebbraro** [comment]
done
