### ISSUE TITLE
Update Content for Inputs

### ISSUE THREAD

**Issue by philrinke** [sparkdesignsystem/spark-design-system#287]
I have written up some short descriptions for the inputs section so that each input has an explanation of how it is intended to be used. 

**Text Input:** This is the base input and be used to collect a wide variety of information from a user.
 
**Checkboxes:** This type of input should be used when the user has the ability to select multiple items at once from a list of items. The checkbox input component should be used when there is a minimum of 3 items to choose from.
 
**Radio buttons:** This type of input should be used when the user can only select one option from a list of items. The radio button component should be used when there is a minimum of2 items to choose from in the list. 
 
**Select Box:** This input type should be used when a user needs to select a single option from a large list of options.
 
**Text Area Input:** This input should be used to collect something that cannot be captured in a single line input field. Text should wrap within the input field as it is populated with text.
 
**SSN Input:** This specific input is specifically used to collect a user's Social Security Number and has a very specific set of rules in the section below.
 
**Search Input:** This input should be used when the client has the ability to search within their experience by a word or phrase to find a specific piece of content without the use of navigation. 
 
**Inline Search Input:** This style of the search input retains the same functionality as the "search input," but is styled in such a manner as to allow it to be used in the Masthead component or similar components.
 
**Monetary Input:** This input should be used to collect a monetary amount.
 
**Password Input:** This input should be used when it is required that a user input a password. The specific field requirements are below regarding password visibility.
 
**Helper Text:** Helper text should be used when a specific input type has special requirements that the user needs to be aware of so they can successfully enter the desired information.
 
**Phone Number Input:** This input should be used to collect a phone number. The input will auto format the phone number on blur.
 
**Date Input:** The date input component is used for collecting date information. Spark recommends that this component be used to collect information for the past.
 
**Date Picker:** The date picker component is a type of date input, but as the actual date picker feature with a calendar included to allow users to pick a very specific date on the calendar. Spark recommends that this component be used to select dates in the future.

**Comment by afebbraro** [comment]
@philrinke  - I think this one is worded incorrectly "Text Input: This is the base input and be used to collect a wide variety of information from a user."

maybe should be "Text Input: This is the base input and **is to** be used to collect a wide variety of information from a user."

**Comment by afebbraro** [comment]
fixed in https://github.com/sparkdesignsystem/spark-design-system/pull/294
