### ISSUE TITLE
[RESEARCH] Update to Side Navigation

### ISSUE THREAD

**Issue by philrinke** [sparkdesignsystem/spark-design-system#289]
The side navigation for the spark site does not remain on the selected item after it is navigated to. So whenever an item is clicked on, the experience loads that page and the side navigation jumps to the top. 

The intended functionality is that it remains on the selected item in the side navigation when loading that content on the page. Let me know if there are any questions about this.

**Comment by ssabo1** [comment]
No longer an Issue on the new doc site.
