### ISSUE TITLE
Update Design of Side Navigation

### ISSUE THREAD

**Issue by philrinke** [sparkdesignsystem/spark-design-system#290]
I would like to update the design of the side navigation to increase the visual difference between the components themselves and their category. I would like to make the category name a dark orange close to (#302E2E) and bold weight so that it passes the visual accessibility tests.

**Comment by afebbraro** [comment]
@philrinke , I'm noticing that #303E2E is closer to black than orange. Did you paste the wrong value by accident?

**Comment by philrinke** [comment]
@afebbraro yeah thats super the wrong color...it was late. try this one #FD6C45 for the orange.

**Comment by afebbraro** [comment]
fixed in https://github.com/sparkdesignsystem/spark-design-system/pull/294
