### ISSUE TITLE
Build Submission Spinner for Secondary Button - HTML

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2910]
**User Story:**
As a Spark user I want to be able to add a spinner inside of a secondary button.

**Notes:**
Requestor: Tommy/RV 1/10/20, Tommy & Jane talked 3/13/20
Current State: Primary Button is green with white spinner, cant use white spinner on a white secondary button.
- future, when we update buttons we will need a spinner for each of the sizes.
- before we can work on this? What is the function of a removal button? Who is using this, RMA?)
- component update for angular**

**AC:**
- Spinner for Secondary button will be #333333 (the color of what is inside the secondary button)
- dark spinner from red to #333333 
- add a story that shows a secondary button with dark spinner. 
- Create variable for Spark Spinner color dark.

**Comment by afebbraro** [comment]
@ssabo1 we have a dark submission spinner button, its "red" right now. Sounds like we need to update this to black? Or do we want to keep this one? I don't know why we added this. Would also be nice to know haha.
<img width="115" alt="Screen Shot 2020-03-16 at 8 33 56 AM" src="https://user-images.githubusercontent.com/2117593/76758864-f13c3e80-6760-11ea-8b67-b7ee6948ca17.png">
