### ISSUE TITLE
Flag Object doesn't stack in small viewports

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#296]
## Describe The Bug
Flag Object doesn't stack in small viewports.

## To Reproduce
1. Go to Spark on mobile device or small window size
2. Click on  fundamentals/layout
3. Scroll down to Flag Object

## Expected Behavior
The Flag Object image and content stacks.

## Desktop (please complete the following information):
 - OS: [e.g. iOS] all 
 - Browser [e.g. chrome, safari] all
 - Version [e.g. 22] all

## Smartphone (please complete the following information):
 - Device: [e.g. iPhone6] all 
 - OS: [e.g. iOS8.1] all 
 - Browser [e.g. stock browser, safari] all 
 - Version [e.g. 22] all

**Comment by afebbraro** [comment]
Need to add scales modifier

**Comment by yodasw16** [comment]
Scales has `.Flag--stacked` which has a variable to set the breakpoint where it is stacked.

**Comment by yodasw16** [comment]
I realized I misunderstood this after seeing the PR. Carry on...
