### ISSUE TITLE
Implement gatsby-remark-check-links plugin

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#2964]
**US**
- Implement the `gatsby-remark-check-links` plugin to check the documentation site for broken links

**Notes**

**AC:**
- gatsby will have a check for broken links when building

**Comment by guern1kn** [comment]
Closing this. There is a suspected issue with how `gatsby-plugin-mdx` returns the links to the `gatsbyRemarkPlugins` and the `gatsby-remark-check-links` plugin does not work. It looks in the parents and siblings for links, but `gatsby-plugin-mdx` wraps all of the links in paragraphs and type 'link' is never passed to the `gatsby-remark-check-links` plugin. Closing this issue. If this comes up again we can try and find a different solution.
