### ISSUE TITLE
Upgrade Spark to Angular 9

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3000]
**User Story:**
As Spark we want to upgrade to Angular 9.

**Notes:**
 - New Issues will come out of this during Component Testing, all issues will be added to the sharepoint doc and reviewed if its mvp or mvp +
 - All manual testing stories for upgrading to Angular 9 are dependent on this.
- When SB updates IE11 Patch Spark will implement patch here https://github.com/sparkdesignsystem/Backlog/issues/739

**AC:**
- Create a new branch of spark that uses Angular 9 (Try to follow the angular 9 upgrade guide https://update.angular.io/)
- Fix build time errors, but not run time errors at this stage
- Push branch up for others to test against
- Publish Alpha

**Comment by afebbraro** [comment]
This work has been completed but we are not ready to merge until storybook fixes angular 9 apps running in SB in ie11. I pushed up a branch to the team repo with this work. Once the storybook patch is merged,  we can merge this and upgrade. SB. https://github.com/sparkdesignsystem/spark-design-system/tree/angular-9
