### ISSUE TITLE
HTML Spacing: Inset, Inset Short and Inset Tall have the same sample implementation code with a bug

### ISSUE THREAD

**Issue by rohanthorat** [sparkdesignsystem/spark-design-system#3007]
Inset, Inset Short and Inset Tall have the same sample implementation code in html with a bug.
- The individual divs have the same css class "**spark-u-mbm**" (this is for the sample implementation code)
- When you actually inspect the Spark demo showing inset spacing example, the individual divs have the same css class "**spark-u-mbm**", and all of the divs are wrapped under box div with class "**sprk-o-Box sb-decorate**". When you select the individual div element, you can see in the styles section on the right, the padding for individual divs is changed to 4px (1 div), 8px (2div), 16px (3div), and so on, by the class "**.sb-inset-spacing-example div:nth-child(3)**"

## To Reproduce
1. Go to **[https://html.sparkdesignsystem.com/?path=/docs/foundations-spacing--inset-spacing]**
2. Click on '**Inset/Inset short/Inset tall**' show code button
4. See all the divs will have the same class

## Expected Behavior
The divs should have different classes based on their respective sizing

## Screenshots

![image](https://user-images.githubusercontent.com/24980024/78155463-7be09700-740b-11ea-9f78-216a3554db92.png)
![image](https://user-images.githubusercontent.com/24980024/78155589-a894ae80-740b-11ea-9900-f656376282fe.png)

## Desktop (please complete the following information):
 - OS: all
 - Browser: all
 - Version [e.g. 22]: all

## Smartphone (please complete the following information):
 - Device: all
 - OS: all
 - Browser: all
 - Version: all

**Comment by RCopeland** [comment]
Hey @rohanthorat we'll look into this, thanks!

**Comment by afebbraro** [comment]
hey @rohanthorat, I can totally see what you mean. We created that page as a way to show what the different Sass spacing settings look like in action. If you were to apply those Sass variables to a custom class that you are making. We use it in our docs site to also show designers. If you want to implement those check out the Box page https://html.sparkdesignsystem.com/?path=/docs/components-box--default-box -- It has all the available modifiers to be able to use any of those spacing sizes.

**Comment by rohanthorat** [comment]
@afebbraro Thanks for the update! I want to implement this spacing classes on the div level, not in my custom classes. I can see you have added this issue to your upcoming iteration work, I'll keep an eye on this and hopefully we are able to come up with a solution. Thank you for keeping this on priority!

**Comment by afebbraro** [comment]
Hey @rohanthorat no problem. To add them on <div> you would go to https://html.sparkdesignsystem.com/?path=/docs/components-box--default-box and check out the class modifier table and pick the spacing that you want and add it to the div.

Use this for medium spacing `<div class="sprk-o-Box"></div>`. This for inset short small spacing `sprk-o-Box--inset-short-small`. Theres about 20 different spacing configurations you can try. What one are you looking for?

**Comment by afebbraro** [comment]
Closing this issue, please let us know if anything else comes up! @rohanthorat
