### ISSUE TITLE
Should Spark implement an autocomplete component?

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#3049]
Some apps have been asking about Spark owning an autocomplete component, specifically about addresses. 

Questions:
- should spark provide an autocomplete component?
  - if so, should that component be tied to address or be generic?

Notes:
- take a look at Melissa API (http://wiki.melissadata.com/index.php?title=Express_Entry%3ASample_Code)
- Support: Requestor: 2/21 Rich Dudley (Enterprise Data Architect), Jess Lane (PO of Property Hub, implementing the new AVS services) and Justine Lauer (Data Engagement, the AVS purchasing contracts).

**Comment by ssabo1** [comment]
This was brought up to UX Design and UX Strategy today and it has been added to their backlog prior to being built into spark frameworks. https://github.com/sparkdesignsystem/Backlog/issues/949
