### ISSUE TITLE
Reach out to initial consumer apps, get browser analytics.

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#31]
We need to know if there's anybody supporting browsers outside our defined list:

https://github.com/sparkdesignsystem/spark-design-system/wiki/Pattern-Testing#supported-web-browsers-current-version--one-prior

**Comment by afebbraro** [comment]
Waiting on one email before finalizing that initial consumer apps are all good. @yodasw16 is getting browser analytics.

**Comment by yodasw16** [comment]
I went through RMA, RMO, RMS, QLMS, and QL. None of them have any outliers from our browser recommendation. We can go with this list we have and close this issue.
