### ISSUE TITLE
[Enhance] Sparks Input Border Outline and Placeholder text 

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3108]
**User Story:**
As Spark, we want our Grey Outline to be accessible so we want to update Sparks currently outline with an accessible color.

**Notes:**
SME: Jane/Olya 

/// Color value for black at 50%.
/// @group black
/// @type #808080
$sprk-black-tint-50: rgb(128, 128, 128);

**AC:**
- Inputs will use #808080 for their default outline to match accessibility guide. 
- Placeholder text will be #808080. 
- This will be updated for Branded Checkboxes and Radios 
(Jane will try to make a list of each spot it impacts)

**Comment by afebbraro** [comment]
Sent over my questions to @ssabo1!
