### ISSUE TITLE
[Research] Solve big picture components for react and angular. 

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3129]
**User Story:**
As Spark we want to solve the big picture around our React and Angular Componts  

**Current State:**
Problems with current variant prop on Card:
Storybook already includes proptype at bottom of description, so having it in the description is redundant.

**Notes:**
This is for Card 
Related Issue: https://github.com/sparkdesignsystem/Backlog/issues/398

![image](https://user-images.githubusercontent.com/46761151/80667324-de5d9f00-8a6c-11ea-9fb3-00dbedcd7b20.png)

**Comment by afebbraro** [comment]
Going to close this since the api work has been fleshed out besides for a few components that are in design review.
