### ISSUE TITLE
Update Design Principles for Content

### ISSUE THREAD

**Issue by philrinke** [sparkdesignsystem/spark-design-system#313]
The brand team had some thoughts and feedback on what we had written for the brand principles. I have the new content here that will need to be updated on the design principles page.

DESIGN PRINCIPLES – IN ORDER OF IMPORTANCE

Our design principles capture the essence of what good design means to our company and provide direction on how to achieve it.

Clarity
Eliminate ambiguity. Enable people to see, understand and act with confidence.

Consistency
Create familiarity and strengthen intuition by applying the same solution to the same problem every time.

Beauty
Every design decision should be purposeful. Build trust and further build confidence with an experience that looks beautiful and flows seamlessly.

Inclusive
Craft an experience that recognizes the varying abilities of all people. Designing for those with disabilities will result in a better experience for everyone. 

Delight
Enhance expressions through thoughtful and unexpected details that bring joy to every touchpoint.

**Comment by RCopeland** [comment]
@philrinke Inclusive or Inclusion?

**Comment by afebbraro** [comment]
fixed
