### ISSUE TITLE
[Enhance] Create new proptype for SprkTextInput and SprkInputElement - React

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#3142]
## Proposal Title
React
SprkInputElement contains the following proptypes, but SprkTextInput doesn't
- type (also needs to be a "oneOf" instead of string)

**Notes:**

**AC:**
- Create a new Prop for sparkinputlelment (so that we stop using type)
- Create a new Prop for spaktextinput
- I will see a warning log when trying to use type
- Update docs
- will depreciate in future

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
