### ISSUE TITLE
[Enhance] HTML Spacing SB Page - HTML

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#3155]
**User Story::**
Add message to HTML SB to see so you can visually see spacing

**Notes:**
first attempt at resolving issues with the use-fullness of this page.
https://fall2018.sparkdesignsystem.com/patterns/utilities/single-property#spacing

**AC:**
- Add message to HTML SB to see so you can visually see spacing
- show code button will be hidden
- link to list of all util classes https://sparkdesignsystem.com/using-spark/foundations/css-utilities/#css-utilities
- will explain spacing options and naming convention, will show examples.
https://fall2018.sparkdesignsystem.com/patterns/utilities/single-property#spacing

**Comment by ssabo1** [comment]
confirmed. added to team backlog
