### ISSUE TITLE
Inputs: Code / A11y / Design / Documentation Review

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#32]
Includes: 
* forms
* input
* validation-criteria

See the one note, also:
https://github.com/sparkdesignsystem/spark-design-system/wiki/Pattern-Testing

**Comment by afebbraro** [comment]
@philrinke is this one ready to go from design perspective?

**Comment by philrinke** [comment]
Design Input on Inputs
- change label text size to 1.21rem or (Body One in dark blue)
- decrease helper text size to 1rem
- change space between label and input field to 8px (sml)
- max width for all fields should be half of what you have or like 440px. they should also be full width on any mobile devices.
- label and error message length cannot be capped, we should just recommend that they are short and sweet. it will change based on the context so we'll have to have them wrap

**Comment by philrinke** [comment]
- i would also change the radio button options as well as the check boxes to not be bold in weight
