### ISSUE TITLE
[Enhance] Add Animation to Tooltip - All Frameworks

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3213]
**User Story:**
As Spark we want Animation to work with our Angular tooltip component.

Example: https://webdesign.tutsplus.com/tutorials/css-tooltip-magic--cms-28082

**Notes:**
This is a follow up from: https://github.com/sparkdesignsystem/spark-design-system/pull/3170
SME: Bob

**AC:**
- Angular Tooltip will use animation

**Comment by RVMendoza** [comment]
## Helping @bobwise with some research on tooltip transitions 🤩

Tooltips currently use`display:none` -> `display: inline-block` which doesn't transition.

I tried using `opacity: 0` -> `opacity: 1` with a `transition`

I think Bob will have best context for implementation, but wanted to help with some prelim research!

![tooltip](https://user-images.githubusercontent.com/4342363/89455552-8223ae80-d730-11ea-9687-304ec0099820.gif)

**Comment by RVMendoza** [comment]
## More help for different tooltip with different icon sizes, @bobwise 

An idea:
1. Use JS to measure the size of the icon
2. Add measures to attributes `data-tooltip-icon-width` and `data-tooltip-icon-height`  
3. Use the [CSS attr() function](https://css-tricks.com/css-attr-function-got-nothin-custom-properties/) to do all the math for positioning

![image](https://user-images.githubusercontent.com/4342363/89457310-2f97c180-d733-11ea-9693-64fafc0297d8.png)

**Comment by bobwise** [comment]
> ## More help for different tooltip with different icon sizes, @bobwise
> An idea:
> 
> 1. Use JS to measure the size of the icon
> 2. Add measures to attributes `data-tooltip-icon-width` and `data-tooltip-icon-height`
> 3. Use the [CSS attr() function](https://css-tricks.com/css-attr-function-got-nothin-custom-properties/) to do all the math for positioning
> 

I think this is spot on. Eventually we may want to support putting tooltips on different elements (buttons etc) and we'd want a generic positioning solution for those.
