### ISSUE TITLE
[Enhance] Add new variant prop to React Inputs

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3241]
**User Story:**
As spark we want to rename type prop for react inputs so that we are not supplying invalid HTML. 

**Notes:**

**AC:**
- add new prop
- depricate old proptype
- type=textarea will not be set on textarea element
- check all react inputs this could affect.

**Comment by afebbraro** [comment]
closing as this will be taken care of in the other react input issue
