### ISSUE TITLE
Spark-Angular: Javascript error on tab change. aria-control not being added

### ISSUE THREAD

**Issue by jrussr42** [sparkdesignsystem/spark-design-system#3246]
## Describe The Bug
A javascript exception is thrown `Cannot read property 'ref' of undefined` if tabs are re-rendered on the the page and then clicked.
![image](https://user-images.githubusercontent.com/67438539/85788046-586f7480-b6fa-11ea-9b5e-8ff2e290336b.png)
This occurs in our codebase when we wrap the content being display with an observable | async and call next on that observable.

After a quick look at the code it appears to be searching for 'aria-controls'

![image](https://user-images.githubusercontent.com/67438539/85788164-8654b900-b6fa-11ea-8016-9a131cf5bf49.png)
and it is no longer being added when it is re-rendered on the page. 

First time rendered: 
![image](https://user-images.githubusercontent.com/67438539/85788446-f9f6c600-b6fa-11ea-864c-458e5ce599f9.png)
Second time rendered: 
![image](https://user-images.githubusercontent.com/67438539/85788351-d469bc80-b6fa-11ea-88f7-271afa713dcb.png)

## To Reproduce
1. Wrap tab components with observable | async as <something>
2. Click on a tab
3. On click update the value of the observable with a next call. (exposed by Subject)
4. Click on another tab after update
5. See error

## Expected Behavior
No Javascript error. If element is no longer there fail gracefully. 

## Desktop (please complete the following information):
 - OS: Mac
 - Browser Chrome
 - Version 81.0.4044.113 (Official Build) (64-bit)

**notes:** 
SME: Jason Russel, Rocket Pro

**AC:**
- Fix Issue PR off Master
- Follow up with PO to create issue to update Kitchen Sink

**Comment by RVMendoza** [comment]
Talked with Justin and was able to recreate this bug

See this PR for recreation:
https://github.com/sparkdesignsystem/spark-design-system/pull/3263

Will pick back up after sprint critical tasks are done.

**Comment by RVMendoza** [comment]
@ssabo1 @afebbraro Jason also mentioned he wants to be able to trigger the active tab without needing a click event -- not sure if we should add this into the story or make a new issue
![image](https://user-images.githubusercontent.com/4342363/87173053-2be35d00-c2a3-11ea-92b5-1092cd6db0b6.png)
