### ISSUE TITLE
FONTS NEED UPDATING

### ISSUE THREAD

**Issue by philrinke** [sparkdesignsystem/spark-design-system#325]
Per feedback from Liz, she would like us to revisit some of our font sizes across Spark prior to first release. She wants to make sure that these are as full proof as they can be so we will also need to shore up the documentation since we are already seeing developers implementing them incorrectly.

I will set up a meeting for a handful of folks to dig into this.

**Comment by afebbraro** [comment]
Body 1: bold, 1rem/1.5
Body 2: 1rem/1.5
Body 3: 0.826rem/1.3

Display 1: 2.853rem/1.3
Display 2: 2.594rem/1.2
Display 3: 2.144rem/1.3
Display 4: 1.772/1.3
Display 5: 1.464rem/1.5
Display 6: 1.21rem/1.3
