### ISSUE TITLE
[Enhance] A11y: Accessibility improvements to code samples in guides

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3251]
**User Story:**
As Spark we want to make our code samples more accessibly.

**Notes:**
SME: Bob/Olya

**Current State:**
Axe error: Elements must have sufficient color contrast

Axe error: Ensure that scrollable region has keyboard accessscrollable code samples can't be fully viewed without a mouse
 
Code samples need to use a color theme with sufficient contrast and code samples need to be fully visible without the use of a mouse.

**AC:**
Getting Started Gudies, Gatsby
- Code samples will use a color theme with sufficient contrast
- Code samples will be fully visible without the use of a mouse

**Comment by ssabo1** [comment]
Follow up with Jane ideas.

**Comment by bobwise** [comment]
Completed in https://github.com/sparkdesignsystem/spark-design-system/pull/3731
