### ISSUE TITLE
[Enhance] Toggle - expand by default

### ISSUE THREAD

**Issue by charmis** [sparkdesignsystem/spark-design-system#3258]
## Describe The Bug
The spark Toggle component is collapsed by default when the page loads. It would be nice if it has a property to set it `expand`/`open` by default.

**User Story:**
As a Spark User I want Sparks Toggle Component to have a property to set it `expand`/`open` by default so that it's not always collapsed by default when the page loads.

**Notes:**
SME: Charmis & Amber

**AC:**
- Spark Toggle will have a property to set it `expand`/`open` by default.
- add property to Angular and React
- will be able to configure HTML to be default open or closed

**Comment by RVMendoza** [comment]
This seems to be accomplished is `isOpen`. Can we close this?


https://angular.sparkdesignsystem.com/?path=/docs/components-toggle--default-story

![image](https://user-images.githubusercontent.com/4342363/105070172-e8875980-5a50-11eb-9513-2119053520d0.png)
![image](https://user-images.githubusercontent.com/4342363/105070279-09e84580-5a51-11eb-84bb-9f35916e4ebe.png)

**Comment by charmis** [comment]
This work is completed. Closing.
