### ISSUE TITLE
Award Upgrades - Part 1 (Angular)

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3314]
**Angular Changes**
- Update the component to use `heading` as the prop name instead of `title`
- Add in string typings for the `splitAt` prop. (`tiny`,`small`, `medium`, `large` or `huge`.
- The `idString` is set on the `h2` inside the component. We need to move it to the outermost element (the stack).
- The `itemSpacing` input is not configurable by users and is hard-coded to be `medium`. We should add an input so it can be changed.
- `analyticsStringImgOne` should be changed to `imgOneAnalyticsString`
- `analyticsStringImgTwo` should be changed to `imgTwoAnalyticsString`
- `analyticsStringDisclaimer` should be changed to `disclaimerAnalyticsString`
- `additionalClassesImgOne` should be changed to `imgOneAdditionalClasses`
- `additionalClassesImgTwo` should be changed to `imgTwoAdditionalClasses`
- The images are always wrapped inside a `sprkLink` tag and only have the option to use href. So they can never use routerLink="/user/amber", for example. Add ability to use `routerLink`
 
**Notes:**
React Changes will be done in #3315

**Comment by bobwise** [comment]
`routerLink` functionality moved to new Issue https://github.com/sparkdesignsystem/Backlog/issues/1297
