### ISSUE TITLE
[Enhance] Tooltip to work with Different Size Icons 

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3357]
Release with New Colors:

**User Story:**
As Spark we want Tooltip to work with Different Size Icons 

**Notes:**
This is a follow up from: https://github.com/sparkdesignsystem/spark-design-system/pull/3170
SME: Bob

**AC:**
- Tooltip will work with different size icons
Medium
Large
Extra Large

**Comment by RCopeland** [comment]
merged
