### ISSUE TITLE
ESLint fix JS files for HTML

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3461]
Fix any eslinting errors in the JS files in the HTML directory

**Comment by devcshort** [comment]
Can I do this once hacktoberfest starts?

**Comment by bobwise** [comment]
Hello @devcshort !

You can absolutely work on this whenever you'd like :)

**Comment by devcshort** [comment]
Sounds great! Can you assign this one to me?

**Comment by devcshort** [comment]
I haven't heard anything back, so I'm going to drop out of this one. I also don't have much time anymore due to a new job. Thank you!

**Comment by motionsuggests** [comment]
I will take this one.

**Comment by motionsuggests** [comment]
So I'm not sure what to do about these `max-len` errors. Breaking them feels weird. Should I just put in `// eslint-disable-next-line max-len` so it stops complaining?

Example
```
<div class="sprk-o-Stack sprk-o-Stack--split@xs">
      <div class="sprk-o-Stack__item sprk-o-Stack__item--fourth@xs sprk-u-AbsoluteCenter"> // complaining here
        <p class="sprk-b-TypeBodyOne">
          fourth
        </p>
      </div>
      <div class="sprk-o-Stack__item sprk-o-Stack__item--half@xs sprk-u-AbsoluteCenter"> // complaining here
        <p class="sprk-b-TypeBodyOne">
          half
        </p>
      </div>
      <div class="sprk-o-Stack__item sprk-o-Stack__item--fourth@xs sprk-u-AbsoluteCenter"> // complaining here
        <p class="sprk-b-TypeBodyOne">
          fourth
        </p>
      </div>
    </div>
```
