### ISSUE TITLE
ESLint the React JS files in the react directory

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3462]
Submit a PR that fixes any eslint issues that you find in the React directory

**Comment by Tomekmularczyk** [comment]
I'll take it :)

**Comment by Tomekmularczyk** [comment]
😮
![image](https://user-images.githubusercontent.com/12544704/94261684-8ef3a000-ff32-11ea-8724-633f599b8339.png)

**Comment by afebbraro** [comment]
Hey @Tomekmularczyk, that is a lot of errors haha! This issue is just for the react/ directory itself and not everything inside of the spark-design-system repo. So it would be spark-design-system/react where you want to run eslint.

**Comment by officialpm** [comment]
I would like to take this @afebbraro

**Comment by g-ravity** [comment]
I would also like to work on this issue, if this is still up for grabs.

**Comment by Tomekmularczyk** [comment]
I don't work on this

**Comment by afebbraro** [comment]
thanks @officialpm! It is assigned.

**Comment by officialpm** [comment]
@afebbraro 
There are 300+ max len issues as limit is set to 80
Adding line breaks will also break the code!
So what you suggest to do?

**Comment by afebbraro** [comment]
hey @officialpm, yes, it is a lot of cleanup. If you'd like to only do a few files, I would happily accept that PR and could create an issue for it. Regarding the line breaks, the line breaks shouldn't break the code if added in a certain way. Thanks again.

**Comment by officialpm** [comment]
> hey @officialpm, yes, it is a lot of cleanup. If you'd like to only do a few files, I would happily accept that PR and could create an issue for it. Regarding the line breaks, the line breaks shouldn't break the code if added in a certain way. Thanks again.

I am trying to resolve as many as I can without breaking the code
Many max len issues are of comments I can break them !
Solving as many as I can there were about 600+ in total
Already done with 150 approx!!

**Comment by afebbraro** [comment]
Closing as its the first of December now but can absolutely re-open if PR is submitted. Thanks again!
