### ISSUE TITLE
Fix any Sass lint issues in the .scss files

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3463]
Go through and fix any Sass lint issues in the .scss files in the HTML directory.

**Comment by tanansatpal** [comment]
I will take this up @afebbraro

**Comment by afebbraro** [comment]
@tanansatpal  great! Let me know if you run into any issues.

**Comment by ssabo1** [comment]
Hi @tanansatpal touching base to see if you are still working on this issue?
