### ISSUE TITLE
Add a README to the HTML package

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3464]
The Spark package on npm's site should have a README. Can copy the existing README in the root.

https://github.com/sparkdesignsystem/spark-design-system/issues/3235

**Comment by diriquelme** [comment]
Hi team,
I can work on this issue.

**Comment by imkks** [comment]
assign it to me. I want to work on it please

**Comment by afebbraro** [comment]
Thanks @imkks , it is assigned. Let us know if you have any questions.

**Comment by ssabo1** [comment]
confirmed. added to team backlog
