### ISSUE TITLE
Add a README to the React package

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3465]
The Spark package on npm's site should have a README. Can copy the existing README in the root and make edits to customize it for React. Make PR against staging

**Comment by Ahmeed2m** [comment]
I can work on this one!

**Comment by afebbraro** [comment]
Thank you @Ahmeed2m  let me know if you have any questions

**Comment by guern1kn** [comment]
Hi, @Ahmeed2m ! How is this coming along? Do you have any questions?

**Comment by Ahmeed2m** [comment]
> Hi, @Ahmeed2m ! How is this coming along? Do you have any questions?

Sorry I totally forgot about this :sweat_smile: 
Working on it right now will let you know very soon.

**Comment by Ahmeed2m** [comment]
@guern1kn I have just created a PR for this.
