### ISSUE TITLE
Enhance the 404 page Design on Spark Design System 

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3467]
Right now our 404 page looks like this:
![Screen Shot 2020-09-23 at 12 10 46 PM](https://user-images.githubusercontent.com/2117593/94052210-d98be580-fd95-11ea-86c8-94088fbfd45d.png)

We could benefit from having a more enhanced design.

**Comment by ssabo1** [comment]
added to backlog - Design is looking into 404 page
