### ISSUE TITLE
[Bug in Safari desktop] Angular Toggle component content doesn't animate when toggled open

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3473]
## Describe The Bug
Angular Toggle component content doesn't animate when toggled open in Safari desktop. It works in Chrome.

## To Reproduce
1. Go to https://angular.sparkdesignsystem.com/?path=/story/components-toggle--default-story in Safari desktop
2. Click on the toggle 
3. See the content appear with no animation

## Expected Behavior
The toggle content should animate in just like it does in Chrome.

## Desktop (please complete the following information):
*please check when you work on this in other browsers
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] safari
 - Version [e.g. 22] - 12.1.2

## Smartphone (please complete the following information):
 - Device: [e.g. iPhone6] - please check when you work on this in other browsers
 - OS: [e.g. iOS8.1]- please check when you work on this in other browsers
 - Browser [e.g. stock browser, safari]- please check when you work on this in other browsers
 - Version [e.g. 22]- please check when you work on this in other browsers

## Additional Context
Not sure when this broke. I noticed while working on the toggle component and I started testing it.

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
