### ISSUE TITLE
[Docs] Add proptypes for children prop in the src/components/layouts/InstallingSparkLayout.js file

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3474]
Please make the PR against the Staging branch.

**Comment by danzerca** [comment]
I would like to work on this for Hacktoberfest. Can you assign it to me?

**Comment by afebbraro** [comment]
Thanks @danzerca ! It is assigned. Let me know if you have any questions.

**Comment by motionsuggests** [comment]
I'll take this one.

**Comment by afebbraro** [comment]
Thanks @motionsuggests !
