### ISSUE TITLE
[Docs] Add proptypes for children prop in the src/components/layouts/PrinciplesLayout.js file

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3477]
Missing proptypes and needs eslint fixes.

**Comment by Ahmeed2m** [comment]
I can also work on this issue for hacktoberfest, let me know which branch the PR should merge too.

**Comment by imkks** [comment]
I want to work on it

**Comment by afebbraro** [comment]
@Ahmeed2m thank you! Please open PRs against the staging branch. Let me know if you need any help. I will assign to you since you commented first.
