### ISSUE TITLE
Update Toggle Component font size in Spark Footer

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3481]
**User Story:**
As Spark we want to update the font size of the Toggle component in the Footer 

**Notes:**
Requestor: SME, Erik Woods/Dave

**Current State:**
The hover color of purple on the black background passes color contrast, but only if the text is 14px. Ours is 13px. 

The class we are using to make the Toggle smaller is sprk-c-Toggle__trigger--small. It's currently set to font-size: .8125rem but would need to be changed to .875rem. This was spotted by Erik Woods.

![image](https://user-images.githubusercontent.com/46761151/94209812-31f8db00-fe9b-11ea-839c-65310b795515.png)

Olya, Confirm?
Jane, any issue? No Issuse this seems liek a good change. 9/25/20

**AC:**
- sprk-c-Toggle__trigger--small will be updated to font-size: .875rem.

**Comment by davidleininger** [comment]
Happy to take this one @ssabo1.

**Comment by ssabo1** [comment]
Closing this issue because this  passes WCAG AA for regular text. Confirmed with Olya.
