### ISSUE TITLE
[Enhance] Top Navigation will use same link style as side Navigation

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3491]
**User Story:**
As Spark we want our Top Navigation to use same link style as Side Navigation so they are both using the red underline.

**Notes:**
Requestor: Jane 9/16 when testing Updated Colors across the doc site.

**Current State:**
The top nav items, are they using a custom link style? If so, we should probably just switch them to the same link style the side nav is using with the red underline. 

Top Nav: ![image.png](https://images.zenhubusercontent.com/5c98da1df75c1c000158e457/a03e4ad3-479e-4ccc-9a87-728c35312077)

Side Nav: ![image.png](https://images.zenhubusercontent.com/5c98da1df75c1c000158e457/48b62e03-6dcf-41e1-802a-e92506418e18)

**AC:**
- Top Navigation to use link style with red underline (like side nav)
- Mark PR against Staging
- Take a look at Links.scss to find the right link style.

**Comment by motionsuggests** [comment]
I'd like to work on this one.
