### ISSUE TITLE
[Request, Bug] docs - add data-sprk-input="date" to date input SB docs page so users can use formatter

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3497]
**User Story:**
As Spark we want to add data-sprk-input="date" to date input Storybook docs page so users can use formatter.

**Notes:**
Requester: SME Amber, Brought up by Janina in support chat. Need to add it to the SB page for HTML.

**AC:**
Docs 
- add data-sprk-input="date" to Date Input Storybook Docs Page

**Comment by ssabo1** [comment]
This needs to be documented in our SB.

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
