### ISSUE TITLE
Buttons: Code / A11y / Design / Documentation Review

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#35]
see the one note, 
also: https://github.com/sparkdesignsystem/spark-design-system/wiki/Pattern-Testing

This should include buttons, button-secondary-action

**Comment by afebbraro** [comment]
What do we think about having our `sprk-c-Button` be the primary button styles as opposed to what is currently in the system of `sprk-c-Button sprk-c-Button--primary`. Having `sprk-c-Button` as the primary would reduce code from a technical perspective. On a user-friendly perspective of the design system it would make sense that `sprk-c-Button` implies primary button styles and modified versions would then be modifiers off that.

**Comment by RCopeland** [comment]
same issue for sprk-b-Heading and a bunch of other stuff too.
This is a BEM philosophy question i think.

**Comment by afebbraro** [comment]
I think I might of worded that weird but I’m not questioning the naming. Asking why do write primary styles under a modified class instead of writing them under the main button component. The default is primary and plain button isn’t used.

**Comment by afebbraro** [comment]
I think I might of worded that weird but I’m not questioning the naming. Asking if we should write the primary styles under the default component instead having a modified class for it. Because sprk-c-Button should be the primary default button block.

**Comment by yodasw16** [comment]
Honestly the naming there was more about semantics (not html semantics, just..uh..regular semantics) than practicality. If we have sprk-c-Button--secondary, but not primary it makes me feel weird.

From a more technical perspective, sprk-c-Button isn't actually primary by default. That class has all of the Scales stuff on it setting up the base for buttons so it will be gray and have square corners and stuff. --primary in Spark brings all the things that make it a Spark button. Now, we could set the Scales variables to make the default button look like a Spark button then there would be no need for --primary, other than my original thing with having a secondary without a primary and how that just feels weird. I'm not going to die on that hill, but it's worth talking about if we like it that way.

**Comment by afebbraro** [comment]
Awesome response Dave! Yeah, it’s worth talking about I think. I relate it to other things in the software eng and even the real world when I think about it. Like, if I have one vehicle then it’s viewed as my primary vehicle. Same goes for housing. The primary is implied and makes for shorting phasing and easier comprehension. I think this would be a good conversation and I’m not convinced I’m right at all haha but want to discuss nonetheless.

**Comment by afebbraro** [comment]
I went through and did the code refactor, review and documentation update. That's been merged to beta. Created a test page for the buttons as well. Next, need to review the button "rules" and add those rule test variations to the test page.
