### ISSUE TITLE
Convert ComponentPreview.js into a functional component

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#3502]
`src/components/ComponentPreview.js` is a class component when it doesn't need to be.
Convert it to a functional component.

pure component would essentially look like this:
```
const ComponentPreview = (props) => {
  const {componentName, hasReact, etc} = props;
  return (
    <component code here>
  )
}
```

This is done similarly in this file: https://github.com/sparkdesignsystem/spark-design-system/blob/d950981d1165033359aaae04b0fe2e6890c78e86/src/components/DevDocLinks.js
(currently part of an open PR)

### AC:
1. Converted `ComponentPreview` into a functional component
2. Remove useless constructor
3. Make a PR off of `staging` branch

![image](https://user-images.githubusercontent.com/4342363/94934137-55261a80-0499-11eb-9812-9ddae42a3eb8.png)

**Comment by vivek32ta** [comment]
Hi @RVMendoza 

I'd love to take this up

**Comment by RVMendoza** [comment]
@vivek32ta go for it!

**Comment by vivek32ta** [comment]
Hi @RVMendoza 

I'm getting this error since yesterday cloned it as it is. I haven't changed anything. 

```
ERROR #85923  GRAPHQL
There was an error in your GraphQL query:
Cannot query field "allSassUtilitiesJson" on type "Query".
If you don't expect "allSassUtilitiesJson" to exist on the type "Query" it is most likely a typo
File: src\components\CssUtilityTable.js:10:9

Cannot query field "allSassVarsJson" on type "Query".
If you don't expect "allSassVarsJson" to exist on the type "Query" it is most likely a typo.
File: src\components\SassVarTable.js:10:13

// Same error as the one above but in this file
File: src\hooks\use-color-data.js:7:9

```

I use VS Code with a Windows 7 machine.
