### ISSUE TITLE
Update isValidDate to be an arrow function

### ISSUE THREAD

**Issue by guern1kn** [sparkdesignsystem/spark-design-system#3504]
Update isValidDate.js in the html/utilities/validation directory to be an arrow function.

**Comment by saideepesh000** [comment]
can i work on this

**Comment by guern1kn** [comment]
Sure can! I'll assign you. If you need any assistance, let me know. PRs should be made against the staging branch.

**Comment by adrikagupta** [comment]
Hello, I have already worked on this. Please review:)

**Comment by saideepesh000** [comment]
> Hello, I have already worked on this. Please review:)
> 

@adrikagupta, @guern1kn Actually I was assigned to this issue.
