### ISSUE TITLE
Update isValidPhone to be an arrow function

### ISSUE THREAD

**Issue by guern1kn** [sparkdesignsystem/spark-design-system#3507]
Update isValidPhone.js in the html/utilities/validation directory to be an arrow function. 
PRs should be made against the staging branch.

**Comment by mkamranhamid** [comment]
Its currently a function with `function` keyword

**Comment by mantasio** [comment]
hey @guern1kn could I work on this?

**Comment by guern1kn** [comment]
@mantasio Yup! I'll assign you. Please let me know if you need any help.

**Comment by codeShaurya** [comment]
did it in #3515
