### ISSUE TITLE
Update setValidSelect to be an arrow function

### ISSUE THREAD

**Issue by guern1kn** [sparkdesignsystem/spark-design-system#3509]
Update setValidSelect.js in the html/utilities/validation directory to be an arrow function.
PRs should be made against the staging branch.

**Comment by joanwanjiku** [comment]
Hey!, please assign me this issue.

**Comment by guern1kn** [comment]
Sure thing, @joanwanjiku ! Please let me know if you need any assistance.

**Comment by mantasio** [comment]
hey @guern1kn, made a PR (#3559) for this, could you please review it? thanks!
