### ISSUE TITLE
Update setValidTextInput to be an arrow function

### ISSUE THREAD

**Issue by guern1kn** [sparkdesignsystem/spark-design-system#3510]
Update setValidTextInput.js in the html/utilities/validation directory to be an arrow function.
PRs should be made against the staging branch.

**Comment by raydwaipayan** [comment]
Hi, it's already an arrow function.
/html/utilities/validation/setValidTextInput.js: 28

```
const setInvalidTextInput = (inputContainer, defaultErrorMessage) => {
  const overrideErrorMessage = inputContainer
```

**Comment by guern1kn** [comment]
Hi, @raydwaipayan ! That's actually the setInvalidTextInput.js. There is another file - setValidTextInput.js - that needs to be updated.

**Comment by felipedotcom** [comment]
can i take this one?

**Comment by guern1kn** [comment]
@felipedotcom Sure can! I'll assign you. If you need any assistance, please let me know.
