### ISSUE TITLE
Footer.js needs all of its prettier warnings addressed

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#3512]
`src/components/Footer.js` needs all of its prettier warnings addressed

AC: 
1. Address prettier recommendations passed through our `.prettierrc` config (
1. PR on `staging` branch

![image](https://user-images.githubusercontent.com/4342363/94937977-4857f580-049e-11eb-86b6-b40d2b543303.png)

![image](https://user-images.githubusercontent.com/4342363/94938419-cb794b80-049e-11eb-969e-15d6dc7c2161.png)
![image](https://user-images.githubusercontent.com/4342363/94938435-d46a1d00-049e-11eb-95bf-40b33b73b287.png)

**Comment by crs2here** [comment]
I can pick this up

**Comment by RVMendoza** [comment]
@crs2here go for it!

**Comment by crs2here** [comment]
thank you
