### ISSUE TITLE
Every Input in Angular Storybook is flagged as Required

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/spark-design-system#3513]
## Describe The Bug
Every Input on every Component in Spark Angular is flagged as Required in Storybook.

Angular Alert (Incorrect)
![image](https://user-images.githubusercontent.com/1424560/94938771-4b071a80-049f-11eb-8f97-e0f68f8d7fcf.png)

React Alert (Correct)
![image](https://user-images.githubusercontent.com/1424560/94938791-522e2880-049f-11eb-9ffc-bd9e0834d3d9.png)

## Expected Behavior
Only Inputs that are actually required should be indicated as such.

## Additional Context
This is possibly an issue with how Angular Storybook is configured.

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
