### ISSUE TITLE
Header.js needs all of its prettier warnings addressed

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#3514]
`src/components/Header.js` needs all of its prettier warnings addressed

AC: 
1. Address prettier recommendations passed through our `.prettierrc` config (
1. PR on `staging` branch

![image](https://user-images.githubusercontent.com/4342363/94938982-83a6f400-049f-11eb-9c56-051618c881a6.png)

![image](https://user-images.githubusercontent.com/4342363/94938419-cb794b80-049e-11eb-969e-15d6dc7c2161.png)
![image](https://user-images.githubusercontent.com/4342363/94938435-d46a1d00-049e-11eb-95bf-40b33b73b287.png)

**Comment by sambhavjain9138** [comment]
Heyy @RVMendoza 
I would like to contribute to the issue. Can you give me an idea of what all tech stacks are required to contribute?

Regards,
Sambhav Jain

**Comment by RVMendoza** [comment]
Hey @sambhavjain9138 please take look at our readme to get started and let me know if you're still interested and I'll officially assign you to this task!

**Comment by slavakr** [comment]
Hey, I have added PR, but it's not coming up under "Linked pull requests". Do I need to do anything more? First time making PR here :)

**Comment by RVMendoza** [comment]
@slavakr your PR was merged by @guern1kn ! Thank you so much for contributing!
