### ISSUE TITLE
InstallingSparkDocsMenu.js needs all of its prettier warnings addressed

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#3516]
`src/components/InstallingSparkDocsMenu.js` needs all of its prettier warnings addressed

AC: 
1. Address prettier recommendations passed through our `.prettierrc` config
1. PR on `staging` branch

![image](https://user-images.githubusercontent.com/4342363/94939270-e13b4080-049f-11eb-9e1d-5464f899d0f8.png)

![image](https://user-images.githubusercontent.com/4342363/94938419-cb794b80-049e-11eb-969e-15d6dc7c2161.png)
![image](https://user-images.githubusercontent.com/4342363/94938435-d46a1d00-049e-11eb-95bf-40b33b73b287.png)

**Comment by KaylaKremer** [comment]
@RVMendoza 

I'll work on this!
