### ISSUE TITLE
Allow a user to specify a default shown in a dropdown (sprk-angular)

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#3529]
## Description

Currently, text that, by default, reads 'Make a selection' is rendered in the dropdown on load. We'd like to allow setting default: true on a supplied choice, that would let one of the choices be the rendered one on load.

See [Angular Informational Dropdown](https://angular.sparkdesignsystem.com/?path=/docs/components-dropdown--informational) for existing component use. 

Default render today: 

![Screen Shot 2020-10-02 at 1 19 24 PM](https://user-images.githubusercontent.com/412903/94951260-f5883900-04b1-11eb-811e-25d531d42698.png)

Default render with default option supplied:

![Screen Shot 2020-10-02 at 1 19 35 PM](https://user-images.githubusercontent.com/412903/94951267-f8832980-04b1-11eb-9472-77fdf43e3de3.png)

## Acceptance Criteria

- The choice object, detailed in [this interface](https://github.com/sparkdesignsystem/spark-design-system/blob/staging/angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.interfaces.ts) will need an additional field, 'default: boolean'. 
- The [component](https://github.com/sparkdesignsystem/spark-design-system/blob/staging/angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts) will need to make use of the input and render the default choice correctly. If there is no default choice, the component should continue to render the text that reads 'Make a selection' by default.
- There should be additional [unit tests](https://github.com/sparkdesignsystem/spark-design-system/blob/staging/angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts) to cover this case, and they should pass.

**Comment by basters** [comment]
@RCopeland I'm just thinking... Do I need to automatically set isActive: true flag for item what was marked with default: true? 
Should those options (default and isActive) be related somehow?
What if I have case like:

```javascript
items: [
  {
    name: 'First',
    value: 'first',
    isActive: true,
  },
  {
    name: 'Second',
    value: 'second',
    isActive: false,
    default: true,
  }
]
```

I just want to prepare qualitative PR for you and my mistake that I didn't answer those questions before.

**Comment by RCopeland** [comment]
@basters I didnt think of that either, good catch! I isActive adds some styling to the active choice in the dropdown and applies aria-selected. I think that when the default is set up, isActive should also be true for that choice.
