### ISSUE TITLE
Allow a user to specify a default shown in a dropdown. (sprk-react)

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#3530]
## Description

Currently, text that, by default, reads 'Make a selection' is rendered in the dropdown on load. We'd like to allow setting default: true on a supplied choice, that would let one of the choices be the rendered one on load.

See [React Informational Dropdown](https://react.sparkdesignsystem.com/?path=/docs/components-dropdown--informational) for existing component use. 

Default render today: 

![Screen Shot 2020-10-02 at 1 19 24 PM](https://user-images.githubusercontent.com/412903/94951260-f5883900-04b1-11eb-811e-25d531d42698.png)

Default render with default option supplied:

![Screen Shot 2020-10-02 at 1 19 35 PM](https://user-images.githubusercontent.com/412903/94951267-f8832980-04b1-11eb-9472-77fdf43e3de3.png)

## Acceptance Criteria

- The choice object, as used in the [component](https://github.com/sparkdesignsystem/spark-design-system/blob/staging/react/src/components/dropdown/SprkDropdown.js), should allow a new property: 'default'.
- The [component](https://github.com/sparkdesignsystem/spark-design-system/blob/staging/react/src/components/dropdown/SprkDropdown.js) will need to make use of the new property and render the default choice correctly. If there is no default choice, the component should continue to render the text that reads 'Make a selection' by default.
- There should be additional [unit tests](https://github.com/sparkdesignsystem/spark-design-system/blob/staging/react/src/components/dropdown/SprkDropdown.test.js) to cover this case, and they should pass.

**Comment by sanchitgupta001** [comment]
Hey! can I take this up ?

**Comment by RCopeland** [comment]
@sanchitgupta001 Sure, I assigned it to you, thanks! Let me know if you have any questions.

**Comment by sanchitgupta001** [comment]
@RCopeland Have raised Pull Request wrt this.
https://github.com/sparkdesignsystem/spark-design-system/pull/3536
Do let me know if any change is required for the same.

**Comment by basters** [comment]
wOOoops. Sorry, I didn't see pictogram that PR for that issue already exists and made extra work :( 
Close my PR if you think that it have no chance to be merged.
