### ISSUE TITLE
React Modal does not trap focus

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/spark-design-system#3531]
## Describe The Bug
The React Modal does not trap focus when the modal is open.

## To Reproduce
1. Go to 'https://html.sparkdesignsystem.com/?path=/story/components-modal--default-story'
2. Click in the modal to give it focus
3. Press Tab several times. Note that the focus indicator cycles within the modal while it is open.
4. Go to 'https://react.sparkdesignsystem.com/?path=/story/components-modal--default-story'
5. Click in the modal to give it focus
6. Press Tab several times. Note that the focus indicator is not trapped in the modal and is able to move into other parts of the UI.

## Expected Behavior
When a modal is open, focus should be "trapped" inside the control.

**Comment by KaylaKremer** [comment]
@bobwise I'll attempt to fix this bug!

**Comment by KaylaKremer** [comment]
@bobwise 

Here's the PR! https://github.com/sparkdesignsystem/spark-design-system/pull/3538
