### ISSUE TITLE
Angular Modal does not trap focus

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/spark-design-system#3532]
## Describe The Bug
The Angular Modal does not trap focus when the modal is open.

**Notes:**
Hacktober PR: https://github.com/sparkdesignsystem/spark-design-system/issues/3537

## To Reproduce
1. Go to 'https://html.sparkdesignsystem.com/?path=/story/components-modal--default-story'
2. Click in the modal to give it focus
3. Press Tab several times. Note that the focus indicator cycles within the modal while it is open.
4. Go to 'https://angular.sparkdesignsystem.com/?path=/story/components-modal--default-story'
5. Click in the modal to give it focus
6. Press Tab several times. Note that the focus indicator is not trapped in the modal and is able to move into other parts of the UI.

## Expected Behavior
When a modal is open, focus should be "trapped" inside the control.

**Comment by ssabo1** [comment]
added to backlog
