### ISSUE TITLE
Suggesting Semantic Typography Class Names

### ISSUE THREAD

**Issue by scottux** [sparkdesignsystem/spark-design-system#357]
## Proposal Title
Semantic Typography Naming

## Type of change
Please select only 1.
* [ ] New Component
* [X] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [X] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

## Description
The class names for Typography basically require going to the docs to remember what does what. By using the description of the use-case, I propose something like the following:

TypeDisplayOne -> TypeTitleHero or TypeTitleProminent
TypeDisplayTwo -> TypeTitlePrimary
TypeDisplayThree -> TypeTitleSecondary
TypeDisplayThree -> TypeTitleTertiary
...
TypeBodyOne -> TypeEmphasis
TypeBodyTwo -> TypeDefault or no class name.
TypeBodyThree -> TypeHelper or TypeInstructions
TypeBodyFour -> TypeSubdued

## Rationale
To reduce confusion as to which numeric type class to use in which cases.

## Live Examples
https://sparkdesignsystem.com/patterns/fundamentals/typography

**Comment by RCopeland** [comment]
Hey @scottux , we actually chose the names to purposefully decouple the style of the type from the structure of the document. Spark automatically maps the heading elements to what they should be set to by default. Using the actual classes is only necessary if building something custom (where the default settings for type arent working stylistically) or if you need the line-height collision functionality.

**Comment by scottux** [comment]
I wasn't trying to tie the class names to structure so much as meaning/purpose.

**Comment by afebbraro** [comment]
@scottux There will be cases where we decide to change styles for the headings. For example, remove the boldness from 'TypeEmphasis' stylistically. That would mean we would have to change the class name. We want to to try remove style description from the class names as much as we can help it so apps don't have to change out HTML sitewide whenever we change styles.  We will have some type style changes coming in the next two days. We're reducing font sizes, changing some line heights,  removing a few of the sizes that we offer. I think removing some of the options might help narrow things down a bit.

**Comment by afebbraro** [comment]
Closing
