### ISSUE TITLE
[REMOVE] Deprecated SprkStack API Deprecation - React

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/spark-design-system#3571]
**User Story:**
As Spark, In React Stack, we want to deprecate the `misc-a`, `misc-b`, etc. props in favor of `miscA`, `miscB`, etc.

**Notes:**
SME: Bob
Deprecation Strategy: http://shorty/designsystemplaybook

**AC**
- document which prop values are deprecated and make sure they aren't being used anywhere else in Spark components
- create an Issue to permanently remove the deprecated values in a later release, and put that issue number in a TODO comment near the deprecated values.
- create future issue to perma delete

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
