### ISSUE TITLE
[Bug] Dropdown - additionalIconClasses is only applied to the base variant - React

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/spark-design-system#3577]
**User Story:**
As Spark, we want React SprkDropdown to add `additionalIconClasses` to the icon in the Informational variant as well as the base variant so that its in Informational variant. 

**Notes:**
Requestor: SME, Bob

**Current State:** 
React, Dropdown Component
additionalIconClasses is only applied to the base variant 

**AC:**
- SprkDropdown will add `additionalIconClasses` to the icon in the Informational variant as well.

**Comment by bobwise** [comment]
Fixed in https://github.com/sparkdesignsystem/spark-design-system/pull/3794

**Comment by ssabo1** [comment]
This was fixed
