### ISSUE TITLE
Update Kitchen Sink - HTML

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3581]
**User Story:**
As Spark we want to update Sparks Kitchen Sink all components are up to date. 

**Notes:**
SME: Bob

**AC:**
- HTML will have navigation
- nav will work on narrow view ports
- New Components will be added to Kitchen Sink App
- all components that have been depreciated will be updated
- Kitchen Sink will be to date

**Comment by bobwise** [comment]
`kichen-sink` and `main` are on the latest spark version and components are updated.
