### ISSUE TITLE
Update Kitchen Sink - Angular

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3582]
**User Story:**
As Spark we want to update Sparks Kitchen Sink all components are up to date. Go back through Upgrade Guides and make sure everything in kitchen-sink is upgraded.

**Notes:**
SME: Bob

**AC:**
- main and kitchen-sink have the latest version of spark in package.json
- Any new Components will be added to Kitchen Sink App
- all components that have been deprecated will be updated
- redirects file for netlify

**Comment by afebbraro** [comment]
This would have been done with the most recent release stuff.

**Comment by ssabo1** [comment]
confirmed: added to team backlog
