### ISSUE TITLE
Update Kitchen Sink - React

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3583]
**User Story:**
As Spark we want to update Sparks Kitchen Sink all components are up to date. 

**Notes:**
SME: Bob

**AC:**
- Kitchen Sink will be to date
- all components that have been depreciated will be updated
- New Components will be added to Kitchen Sink App

**Comment by bobwise** [comment]
PR https://github.com/sparkdesignsystem/spark-starter-react/pull/38
