### ISSUE TITLE
[Enhance] Fix axe Error - React, Inputs

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3585]
**User Story:**
SprkSelectionInput is adding aria-describedBy to inputs even if they don't exist. This is an axe error in React. Possibly Angular/HTML as well.

**Notes:**
SME: Bob

**AC:**
- will not see Axe error in React
- will not see in HTML?
- will not see axe error in Angular??

**Comment by bobwise** [comment]
Closed with https://github.com/sparkdesignsystem/spark-design-system/pull/3784
