### ISSUE TITLE
[Design/Eng] Prototype Autocomplete Input

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3596]
**User Story:**
As Spark we want to create a prototype of Autocomplete input so that we can get an idea ​​how the Input will function once developed. Prototyping allows us to come across important interface elements.

**Notes:**
Requestor: Spark during the UX + Eng Overview of Autocomplete (10/22)

**AC:**
- prototype Autocomplete Input

**Comment by bobwise** [comment]
Our prototype: https://codepen.io/bobwise/pen/bGeLpzz

Example 1: https://codepen.io/trevoreyre/pen/bvwOeL?editors=1010
Example 2: https://codepen.io/ademcifcioglu/pen/xdOyXv?editors=1010

## Our prototype focused on these 5 areas of functionality:
1. A text input with a hidden popup
2. Typing in the input filters the results
3. what do the various aria-* properties do?
4. aria-live section to announce changes in the displayed results
5. Use the arrows keys to move "visual focus" separately from "focus". eg press up and down to highlight rows and press left and right to navigate the text input.

## Next steps in research/prototyping:
1. role="combobox" makes VoiceOver say something about "Ctrl + Option + Space", which is a Mac-only key binding. Should we support this keybinding? What does JAWS say instead?
2. should list items be a li or a div with role="option"? seems like they have the same result
3. Should we use autocomplete="off" and/or autocapitalize="none"? These have to do with suppressing default browser autofill behavior
4. aria-live is sometimes beeping when it updates? Is that expected? Is the beeping maybe coming from somewhere else?
5. VO is lagging/overlapping itself/interrupting itself when I'm typing and it has an aria-live. Not a smooth experience.
