### ISSUE TITLE
Datepicker: Code / A11y / Design / Documentation Review

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#36]
Does this belong in core?

see onenote, also: https://github.com/sparkdesignsystem/spark-design-system/wiki/Pattern-Testing

**Comment by afebbraro** [comment]
@philrinke is this one ready to go from design perspective?

**Comment by philrinke** [comment]
Spoke with our UX Researchers about creating a minimum/maximum for the date picker. They suggested leaving it unbounded as we do not want to prescribe when it can be used. If we programmatically need a boundary then 100 years forward and backward should cover all our bases.
