### ISSUE TITLE
Refactor Angular Award to use a more compositional API

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/spark-design-system#3617]
**User Story:**
As Spark, The original goal was to add support for `routerLink` to the links in Angular Award. The images are always wrapped inside a `sprkLink` tag and only have the option to use `href`. So they can never use `routerLink="/user/amber"`, for example.

After doing some initial research we decided the best approach was to refactor the component to support a more compositional API.

Something like this:
```
<sprk-award title="Our Awards" disclaimerTitle="My disclaimer title" disclaimerCopy="lorem ipsum...">
  <a sprkLink href="/some-link"><img src="somesrc.png" alt="desc text" /></a>
  <a sprkLink routerLink="/some-link"><img src="somesrc.png" alt="desc text" /></a>
</sprk-award>
```

**AC:**
-- new for all API work, must support router links
- refactor component so that it will use compositional in place of configuration 
- unit test will still pass
- router links will work 
- Deprecate old inputs

**Comment by ssabo1** [comment]
Component Currently not being used.

**Comment by ssabo1** [comment]
confirmed: added to team backlog
