### ISSUE TITLE
[REMOVE] Deprecated props from loading and disabled Button

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#3636]
**User Story:**
As spark we want to Remove deprecated props from Button on next release (loading, disabled)

**Notes:**
Deprecation Strategy: http://shorty/designsystemplaybook 
Issue: https://github.com/sparkdesignsystem/spark-design-system/issues/3317
Pr: https://github.com/sparkdesignsystem/spark-design-system/pull/3552

**AC:**
- Look at PR and follow all TODOs
- Add to release/upgrade guide (breaking change)

## Type of change
Please select only 1.
* [x] Enhancement to existing component
* [x] Substantial documentation change

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
