### ISSUE TITLE
[Enhance] Take Inputs formatters from HTML javascript and add them as utilities to React package

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3646]
**User Story:**
As a Spark React and Angular user, I want Input formatter utilities that i can import as needed so that i do no need to import the HTML package only for the utilities.

**Notes:**
SME: Amber 
Request: 11/3
Design Tokens

**AC:**
Duplicate/Copy do not Remove
take Inputs formatters that we have in HTML javascript and add them as utilities to our React package
- Copy over wholesale as utilities
- Will be in ES6
- Copy Unit Test

**To Do:**
Look at HTML Formatter utilities 
Look at what Angular and React are missing

**Comment by afebbraro** [comment]
We have the formatters in angular so just needed to add them to React.
