### ISSUE TITLE
[Bug] Fix JS loading issue in HTML Starter App - IE11

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3712]
**User Story:**

**Notes:**
HTML - Kitchen Sick 

**AC:**
- javascript will be running in IE11

**Comment by afebbraro** [comment]
I researched this and it was because JS was written for autocomplete.js that does not work in IE11. I fixed it and have a PR here: https://github.com/sparkdesignsystem/spark-starter-html/pull/31. I added babel to the HTML starter repo.

**Comment by afebbraro** [comment]
merged!
