### ISSUE TITLE
[Enhance]  Autocomplete HTML to use role="listbox" 

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3713]
**User Story:**
role="listbox" is redundant but it is necessary to get Safari + VoiceOver to work. 

With this change the examples are all fully functional in all supported environments. Since the roles are still the same the user impact will be negligible, but Olya and Bob agree that this change would be the best practice.

**Notes:**
Research issue: https://github.com/sparkdesignsystem/spark-design-system/issues/3795 
This is for HTML Autocomplete

**AC:**
- Update Line 109 in autocomplete.js.
- datalist has display:none by default so we need to add display: block to the CSS.
- Update the HTML storybook stories to use the new HTML.
- Update all the examples in kitchen-sink to use the new HTML.

**Comment by bobwise** [comment]
The Firefox tab key issue can be fixed by setting `tabIndex="-1"` on the list and list items. This needs to be updated in our stories and in the `kitchen-sink` examples.

**Comment by ssabo1** [comment]
Recommendation

<datalist role="listbox">
    <div role="option"></div>
</datalist>

role="listbox" is redundant but it is necessary to get Safari + VoiceOver to work. With this change the examples are all fully functional in all supported environments. Since the roles are still the same the user impact will be negligible, but Kenney, Olya and I agree that this change would be the best practice.

 What does this change entail?

1. Update Line 109 in autocomplete.js.
2. datalist has display:none by default so we need to add display: block to the CSS.
3. Update the HTML storybook stories to use the new HTML.
4. Update all the examples in kitchen-sink to use the new HTML.
5. This can be included as AC on this Issue https://github.com/sparkdesignsystem/spark-design-system/issues/3713

**Comment by ssabo1** [comment]
Closing at this time after the research issue https://github.com/sparkdesignsystem/spark-design-system/issues/3795.
