### ISSUE TITLE
[Enhance] React text area will display field outline pink on Error

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3722]
**User Story:**
As Spark we want React Input text area to show error and turn the field outline to pink.

**Notes:**
Requestor: Doc Site Testing Colors, SME: Jane

**Current State:**
React text area is showing an error but not turning the field outline pink
![image](https://user-images.githubusercontent.com/46761151/97505576-833f3300-194f-11eb-8906-e61b4b581534.png)

**AC:**
- React Invalid Text Area will have pink outline
![image](https://user-images.githubusercontent.com/46761151/97505630-98b45d00-194f-11eb-9ff6-c3da5ca4794a.png)

**Comment by afebbraro** [comment]
I fixed this a few weeks ago as part of react inputs.
