### ISSUE TITLE
will break this out

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3751]
1. `<SprkInputContainer>`
- Create SprkInputContainer
-  Needs variant="huge"
- Needs idString
- Needs additionalClasses
- For and ID logic

```
  <SprkInputContainer>
    <SprkLabel>Percentage</SprkLabel>
    <SprkIcon
      iconName="percent"
      additionalClasses="sprk-b-InputContainer__icon sprk-c-Icon--m sprk-c-Icon--stroke-current-color sprk-b-InputContainer__icon--right"
    />
    <SprkTextInput id="amber-test-id" type="tel" isNarrorWidth hasIconRight/>
    <SprkCheckboxItem isTextToggle>Show SSN</SprkCheckboxItem>
  </SprkInputContainer>
```

2. Create `<SprkLabel>` component and put in inputs directory
- additionalClasses
- hasIcon
- isMonetary
- isHidden (old one was hiddenLabel)
- Add `idString` prop
- Add `analyticsString` prop
- Update `disabled` to `isDisabled`
- Fix eslint errors

3. `<SprkRevealInput>` - New Isssue
- Add Deprecate message todo and create follow up issue and put issue number in comment.

4. `<SprkInputElement>`- New Isssue
- Add Deprecate message todo and create follow up issue and put issue number in comment.

5. `<SprkTextInput>`
- Fix eslint errors
- Remove empty default props
- Add deprecation message and new issue # to comment

6. Create `<SprkInput>`
- Add `isDisabled`
- Add legacy stories
- Add variant 
- idString
- analyticsString
- additionalClasses
- make sure to add ...rest
- formatter: value => value,
- forwardedRef: React.createRef()
- isValid prop it would add the styles sprk-b-TextInput--error
- make sure this is fixed https://github.com/sparkdesignsystem/spark-design-system/issues/3241

7. Deprecate `<SprkSelectionInput>`
- deprecate in favor of new SprkSelect
- add new comment todo and create deprecation issue #

8. Create new `<SprkSelect>`
- Create new component for selects.
- Add legacy stories for old SprkSelectionInput that was used for selects, radios and checkboxes
- idString
- analyticsString
- onChange
- additionalClasses
- variant - 'huge'
- will now use the `<SprkInputContainer>` and SprkLabel
- choices like it had before
- isDisabled
- needs hasBlankFirstOption for huge
- ...other
- isValid to add styles

9. `<SprkErrorContainer>`
- Remove empty default props
- Fix eslint errors
- add deprecation message todo and issue number

10. Create `<SprkFieldError>`
- - additionalClasses
- idString
- ..other
- additionalClasses
- leave as div
- Look into aria-describedby setting logic stuff and id 
- take in children icon and error message

11. 
`<SprkCheckboxItem>`
- add sprk-b-InputContainer__visibility-toggle as a prop named isVisibilityToggle

12. Deprecate`<SprkInputIconCheck>` - New Isssue
- Add Deprecate message todo and create follow up issue and put issue number in comment.

13. Deprecate`<SprkInputLabel>` - New Isssue
- Add Deprecate message todo and create follow up issue and put issue number in comment.

13. Deprecate`<SprkLabelLocationCheck>` - New Isssue
- Add Deprecate message todo and create follow up issue and put issue number in comment.

14. Deprecate `<SprkDatePickerInput>`
- Add Deprecate message todo and create follow up issue and put issue number in comment.

14. Create new `<SprkDatePicker>` to use SprkInput and update the stories to use the SprkInputContainer etc etc etc 
- uses new container composition
- just make sure it has all the sprkinput props
-  additionalClasses,
      analyticsString,
      children,
formatter
- forwardedRef
idString
- isDisabled
- isValid
...rest
- copy over datePickerConfig

**Comment by ssabo1** [comment]
This was broken down into smaller issues.
