### ISSUE TITLE
Deprecate <SprkInputElement>

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3755]
`<SprkInputElement>`

**User Story:**
As Spark we want to Add Deprecate message todo and create follow up issue and put issue number in comment.

**Notes:**
SME: Amber

**AC:**
- will see Deprecate message todo 
- will see a follow up issue with issue number in comment.

**Comment by guern1kn** [comment]
Follow up issue - https://github.com/sparkdesignsystem/spark-design-system/issues/3775
