### ISSUE TITLE
Create new <SprkDatePicker>

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3767]
**User Stroy:**
As Spark we want to Create new `<SprkDatePicker>` 

**Notes:**
React
SME: Amber

**AC:**
- Create new `<SprkDatePicker>` to use SprkInput and update the stories to use the SprkInputContainer etc etc etc
- uses new container composition
- just make sure it has all the sprkinput props
- additionalClasses,
- analyticsString,
- children,
- formatter
- forwardedRef
- idString
- isDisabled
- isValid
- ...rest
- copy over datePickerConfig

**Comment by guern1kn** [comment]
Research on how to add multiple refs to a component using hooks - https://www.davedrinks.coffee/how-do-i-use-two-react-refs/
