### ISSUE TITLE
[REMOVE] Deprecated <SprkLabelLocationCheck>

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3769]
**User Story:**
As Spark we want to Remove `<SprkLabelLocationCheck>`

**Notes:**
React
SME: Amber

**AC:**
- Remove `<SprkLabelLocationCheck>`
- This is the removal issue for this component.

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
