### ISSUE TITLE
icons: Code / A11y / Design / Documentation Review

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#38]
We need an icon set

see one note, also:
https://github.com/sparkdesignsystem/spark-design-system/wiki/Pattern-Testing

**Comment by afebbraro** [comment]
We're thinking we add a` sprk-core-icons.svg` file in the root of sprk-core that will include all the Spark Icons.

**Comment by RCopeland** [comment]
I got a list from the UI engineers on all the cp apps, cross-referenced it from the list from the designers. I worked with Tracy and Phil to remove duplicates and too app-specific icons, which resulted in this list:

- bars
- bell
- calendar
- calculator
- chat
- check
- chevron up
- chevron down
- chevron left
- chevron right
- cloud-download
- computer screen
- clock
- download
- exclamation
- document
- home
- info
- magnifying glass
- paper plane
- pencil
- phone
- play
- plus
- print
- question
- rocket
- security
- times
- update
- upload
- email
- facebook
- twitter
- instagram
- youtube

**Comment by afebbraro** [comment]
@RCopeland nice, should we check with internal apps next?

**Comment by RCopeland** [comment]
removed the spinner from the list, to be handled by whoever does spinners

**Comment by RCopeland** [comment]
added systems and fontawesome icons, creating a new issue for icon description text
