### ISSUE TITLE
[REMOVE] Deprecated Angular Dropdown API (BREAKING)

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#3800]
**User Story:**
As Spark we want to Remove the deprecated Angular Dropdown in a future release.

**Notes:**
Angular
SME: Bob/RV
linked to https://github.com/sparkdesignsystem/spark-design-system/issues/3495
PR That Deprecated: https://github.com/sparkdesignsystem/spark-design-system/pull/3801

**AC:**
Remove Angular Dropdown
This is the removal issue for this component.

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
