### ISSUE TITLE
Broken link on typography page

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#381]
## Describe The Bug
Broken link on typography page

## To Reproduce
1. Go to https://sparkdesignsystem.com/patterns/fundamentals/typography#typekit-setup
2. Click on link in "Please see Typography for font usage" sentence
3. Get 404

## Expected Behavior
link should go to "/patterns/fundamentals/typography" which is just the top of the page you are already on.

**Comment by afebbraro** [comment]
fixed in #382
