### ISSUE TITLE
[Request] Make way to programmatically trigger Toggle - Angular

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#3890]
## Proposal Title
As a user, I want to be able to affect Toggle's open/close state programmatically so I can trigger it in other ways other than click the toggle

Requester: Jonathan Ho. RMS

**Notes:**
- This is for Angular
- This will be Breaking.
- we have an isOpen Input
- React work will be done with https://github.com/sparkdesignsystem/spark-design-system/issues/3889 

**AC:**
- user will be able to programmatically add or remove isOpen.

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
