### ISSUE TITLE
[Request] Update the sass import path on spark install guide 

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#3893]
**Goal:**
Update Spark sass install docs so users don't get an error for missing spark sass file
Current State: It throws error for webpack builds: Module not found: Error: Can't resolve '@sparkdesignsystem/spark-styles/spark'

**Notes:**
Requestor: K Shabazz 1/25 Teams Engineering Support
SME: Amber

**AC:**
Either update the path to include the _spark.scss and not just spark or add in information that shows how they would need to setup their webpack build to account for the removal of the underscore and file ext.

This is the page where we need to add the part about needing to add .scss to the extensions

https://sparkdesignsystem.com/installing-spark/html-installation/

webpack configs would need, extensions: ['.ts', '.scss', '.js'] setup in their webpack config. The change being the addition of the .scss. This would allow them to remove the .scss extension.

I found that here and the person who reported this issue test it out and it works.
https://webpack.js.org/configuration/resolve/#resolveextensions

**Comment by afebbraro** [comment]
possible that webpack configs would need, `extensions: ['.ts', '.scss', '.js']` setup in their webpack config. The change being the addition of the .scss

**Comment by ssabo1** [comment]
confirmed. added to team backlog.
