### ISSUE TITLE
[SprkBuild] Blueprint Autocomplete Component - Angular

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/spark-design-system#3901]
**User Story:**

**Notes**

**AC:**
Autocomplete and Autocomplete Huge
- plan for Angular API component

**Comment by 13protons** [comment]
@bobwise  here's a start https://git.rockfin.com/alanguirand/pathfinder-autocorrect/pull/1

**Comment by ssabo1** [comment]
confirmed: added to team backlog
