### ISSUE TITLE
[Enhance] Remove Yellow and Pink from code base - DEC 13th

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#3913]
**User Story:**
As Spark we want to remove Yellow and Pink from Sparks code base so that it's no longer in the code.

**Notes:**
During Orbit Upgrades we updated Sparks Error Color to be Orange. At the time, we removed Yellow and Pink from the doc site but wanted to remove it from the codebase at a later date.  

## Proposal Title
Related: https://github.com/sparkdesignsystem/spark-design-system/issues/3887
Remove any instance of pink and yellow from code base
- Utilities.scss
- color.json 
- Regenerate style files

## Type of change
Please select only 1.
* [ ] New Component
* [ ] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [ ] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

## Description
Please describe the type of change you want to make. Be as detailed as possible.

## Rationale
Please explain your rationale for wanting to make this change.

## Live Examples
Please link to or attach any relevant documents to this proposal, including diagrams, illustrations, designs, code snippets, or other relevant documentation.

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
