### ISSUE TITLE
Modals: Code / A11y / Design / Documentation Review

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#40]
1. If modal content is tall on landscape mobile view then allow scroll bar
2. Expose click event for modals, a basic thing that they can use if they want. They have to add the data-attribute we suppy.
3. For no click event, they import our JS and use the exported functions we created
4. Add modal HTML in the DOM above the closing body tag
5. Three types of modals; Choice, Wait, and Info (no buttons, and a little close X?)
6. One file for modal functions utilities, and then one that is for binding UI which imports the modal utilities 
7. Have data-attribute for modal cancel button. Close modal if clicked otherwise they don’t use our data attribute 

see one note, also:
https://github.com/sparkdesignsystem/spark-design-system/wiki/Pattern-Testing

**Comment by afebbraro** [comment]
@philrinke is this one ready to go from design perspective?

**Comment by afebbraro** [comment]
Updated the description today based on planning.
