### ISSUE TITLE
TOC + Sticky Nav (UX concern)

### ISSUE THREAD

**Issue by erikwoods** [sparkdesignsystem/spark-design-system#401]
## Describe The Bug
On the Inputs page, the links in the table of contents jump to the correct sections, but the sticky header causes some of the content to be covered up. To see the section you've "jumped" to, you are required to scroll up to see the headline/text from the start of the section. I suspect this will happen with _any_ "deep links" we have like this now or in the future.

## To Reproduce
1. Go to [Inputs](https://sparkdesignsystem.com/patterns/components/inputs)
2. Click on "[Text Input](https://sparkdesignsystem.com/patterns/components/inputs#text-input)" in the Table of Contents (or even on the actual headline, further down the page).
3. Note that without touching any scrolling, the headline and description are covered by the sticky header.

## Expected Behavior
We shouldn't expect users of the documentation to instinctively know this. They should see the "top" of the content being linked to, without the need to scroll up.

## Screenshots
![jul-26-2018 15-26-03](https://user-images.githubusercontent.com/689000/43283930-4c800516-90e8-11e8-88f9-cdd9aba595d4.gif)

## Other Notes:
This could be fixed by calculating the height of the header and subtracting that from the position on the page that it scrolls to (but that's super gross). Or, maybe when the sticky nav sticks, it doesn't take up the full width of its parent element. Maybe there are better solutions but that's what I've got right now.

**Comment by yodasw16** [comment]
Are we using `position: sticky` for this? Doesn't that solve this issue without needing to calculate the height? I don't remember how that works or if we used it here.

**Comment by afebbraro** [comment]
@yodasw16  it is position: sticky but we'll have to dig in to see what's going on.

**Comment by bobwise** [comment]
Two options I've found:

1. Make a different element be the scroll target, and use CSS to offset it.

```
<h2  id="text-input" class="drizzle-b-h2">
    <a href="#text-input" class="drizzle-u-linkHidden drizzle-b-Link scrollTarget"></a>
    
    <a href="#" class="drizzle-u-linkHidden drizzle-b-Link">Text Input</a>
</h2>
```

```
.scrollTarget { top: -90px; }
```

2. Use a ```::before``` pseudoclass 
```
#text-input::before {
   content: "";
   display: block;
   height: 90px;
}
```

I have not tested these.

**Comment by afebbraro** [comment]
fixed and merged. thanks @bobwise
