### ISSUE TITLE
[Question] Update to angular 12

### ISSUE THREAD

**Issue by mathisloge** [sparkdesignsystem/spark-design-system#4018]
## Question

Currently the version is stuck to angular 9.1 if i'm correct. 

Do you plan to upgrade to the latest angular version (12)?

**Comment by ssabo1** [comment]
Hello @mathisloge Angular 11 is currently supported and we are exploring Angular 12 at this time but do no have plans to upgrade in priority at the moment.

**Comment by mathisloge** [comment]
thanks for clarification! Just saw the update to angular 11, too.
