### ISSUE TITLE
Hamburger Icon animation doesn't work right in IE11

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#402]
## Describe The Bug
In IE11, the middle bar of the icon disappears, but the upper and lower bars don't rotate.

## To Reproduce
1. Open in IE11, 
2. Click the Hamburger Icon

## Expected Behavior
The middle bar should disappear, the upper bar should rotate 45deg,
the lower bar should rotate -45deg

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: IE
 - Version: 11

## Additional Context

CSS Transform isn't supported in IE11 on svg elements.

**Comment by afebbraro** [comment]
merged
