### ISSUE TITLE
Deprecation Warning: Using / for division

### ISSUE THREAD

**Issue by jtneal** [sparkdesignsystem/spark-design-system#4022]
I recently ran an `npm update` on one of my projects and started seeing this error when I was running my unit tests. Apparently anywhere that we do division in Sass needs to be replaced with a call to math.div instead.

> 2294 │ $sprk-stepper-icon-radius: $sprk-stepper-icon-diameter / 2;
     │                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     ╵
    node_modules/@sparkdesignsystem/spark/settings/_settings.scss 2294:28  @import
    node_modules/@sparkdesignsystem/spark/_spark.scss 6:9                  @import
    src/app/styles/styles.scss 8:9                                         root stylesheet

> DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

> Recommendation: math.div($spacing, 2)

> More info and automated migrator: https://sass-lang.com/d/slash-div

**Comment by afebbraro** [comment]
hey @jtneal  thanks for the awareness. We aren't using dart sass and the next step would be to move away from the deprecated node sass. Going to close this issue since that is on our radar. Thanks again!
