### ISSUE TITLE
Remove references to xlink, deprecated

### ISSUE THREAD

**Issue by QualityRobD** [sparkdesignsystem/spark-design-system#4029]
## Describe The Bug
There are a number of references to `xlink` in the styling, which is deprecated.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

## To Reproduce
One example: https://github.com/sparkdesignsystem/spark-design-system/blob/339e10c75bae9baa3f97d6c2ca99094c11a6b423/html/components/tooltip.stories.js#L35

also: https://github.com/sparkdesignsystem/spark-design-system/search?q=xlink

## Expected Behavior
this:
```
<use href="#question-filled" />
```
instead of this:
```
<use xlink:href="#question-filled" />
```

**Comment by ssabo1** [comment]
Hello @QualityRobD - After talking with our team this is going to require a large testing lift and not something I am able to prioritize at this time for the team to take on. Closing the issue at this time we can readdress in the future as needed.
