### ISSUE TITLE
Layering of masthead isnt working right

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#403]
## Describe The Bug
In the docs site, the masthead is showing up on top of elements that should be covering it.
In IE11, the masthead shows up even if the z-index is set lower.

## To Reproduce
1. Open sparkdesignsystem.com/masthead with a narrow viewport
2. Open site nav

## Expected Behavior
The site nav should cover the masthead.

## Screenshots
<img width="443" alt="screen shot 2018-07-27 at 11 17 02 am" src="https://user-images.githubusercontent.com/412903/43329519-9b15d6aa-918e-11e8-8bd2-f569820d4204.png">

## Desktop (please complete the following information):
 - OS: macOS Sierra 10.12.6
 - Browser Chrome
 - Version 67

## Additional Context
Not sure if the layering problems are related.

**Comment by afebbraro** [comment]
- merged in "adding flag to prevent z-index minification #414"
