### ISSUE TITLE
Spark checkbox label issue

### ISSUE THREAD

**Issue by venkatesanmurali1991** [sparkdesignsystem/spark-design-system#4041]
## Describe The Bug
When a spark checkbox label has text running more than 1 line, the texts looks to be overlapping when they are highlighted. 

## To Reproduce

1. Go to Spark Documentation for checkbox
2. Update the label content to be something that is more than 1 line
3. Highlight the label

## Expected Behavior
Upon highlighting the content, the text should not be overlapping each other

## Screenshots
Without highlighting
![image](https://user-images.githubusercontent.com/77159717/126716023-4e28e799-aae9-42b7-b724-b74190764333.png)

With highlighting
![image](https://user-images.githubusercontent.com/77159717/126715680-0744493b-9e64-4e39-8b71-b166a5847ed8.png)

## Desktop (please complete the following information):
 - Any browser

**Comment by ssabo1** [comment]
Hello @venkatesanmurali1991 - Thanks for reaching out! As a we recommend to not have more than 1 line. 

Check out our docs to see our guideline recommendations for checkbox here https://sparkdesignsystem.com/using-spark/components/input#checkbox Closing this issue at this time.
