### ISSUE TITLE
[BUILD] Extract date picker into callable function

### ISSUE THREAD

**Issue by dotsonjb14** [sparkdesignsystem/spark-design-system#416]
## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [x] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

## Description
Extract the functionality contained with the [datepicker](https://github.com/sparkdesignsystem/spark-design-system/blob/staging/packages/spark-core/base/datePicker.js) into a callable function, that would take an optional parameter which would be passed through to the underlying datepicker. This function would then be called on [data-sprk-datepicker] by default on page load. 

## Rationale
This will make it easier (read possible) to retain the functionality spark adds to the datepicker, while still allowing access to the other options available to [TinyDatePicker](https://github.com/chrisdavies/tiny-date-picker/blob/master/src/date-picker-options.js)

## Live Examples
The biggest use case I have would allow me to use the inRange, and dateClass options described in the [documentation](https://github.com/chrisdavies/tiny-date-picker/blob/master/docs/tiny-date-picker.md#options) to perform the below actions.

1. Disable specific dates within the normally acceptable range (i.e. Sundays).
1. Highlight in red, days which would have an adverse effect if chosen, but that are still technically valid.

**Comment by RCopeland** [comment]
@dotsonjb14 good idea! I think about setting up like a config object for spark js. 
@philrinke what do you think about the design use cases joe has outlined there? Should spark handle those?

**Comment by philrinke** [comment]
@RCopeland @dotsonjb14  

I like the idea of disabling specific dates or blocks of dates and i think it would make a good addition to the datepicker component. I would need specific examples of the adverse effect dates part to understand if thats something that we would do from an experience standpoint.

**Comment by RCopeland** [comment]
merged into staging
