### ISSUE TITLE
Tabs: Code / A11y / Design / Documentation Review

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#45]
see one note, also:
https://github.com/sparkdesignsystem/spark-design-system/wiki/Pattern-Testing

**Comment by yodasw16** [comment]
Some interesting a11y requirements associated with tabs: https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html

There's also Heydon's version (http://heydonworks.com/practical_aria_examples/#tab-interface), but I think I like the W3C version better using buttons instead of a UL.
