### ISSUE TITLE
[BUILD] Fall Masthead Reskin

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#457]

**Comment by afebbraro** [comment]
@bbrown7 is going to take a look to provide direction.

**Comment by RCopeland** [comment]
![imgo](https://user-images.githubusercontent.com/412903/47658270-14b11a00-db69-11e8-9552-9e64fedf08e7.jpg)

**Comment by RCopeland** [comment]
![imgo-1](https://user-images.githubusercontent.com/412903/47658626-acaf0380-db69-11e8-9e22-a594b92a3aae.jpg)
