### ISSUE TITLE
[BUILD] Fall Tabbed Navigation Reskin

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#459]

**Comment by afebbraro** [comment]
We might be removing. Pending conversation per Brendan.

**Comment by RCopeland** [comment]
<img width="339" alt="screen shot 2018-10-25 at 1 53 30 pm" src="https://user-images.githubusercontent.com/412903/47520168-6d2ca280-d85d-11e8-8a9c-ad1f860fc60a.png">
