### ISSUE TITLE
[BUILD] Add a global site footer to Spark Docs

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#464]
It would be nice if I could get to the Spark github repo from the docs!

**Comment by yodasw16** [comment]
@RCopeland @afebbraro After talking to RV about this more I feel like maybe this doesn't make sense other than on the developer getting started page, since really only contributors will ever need to come to github. We already link to it there. Is there anywhere else you think we need it?

**Comment by afebbraro** [comment]
We would like a footer added to the Spark Documentation site that has these links:
- link to our github: https://github.com/sparkdesignsystem/spark-design-system
- link to our twitter account: https://twitter.com/sparkQL

Please open this PR against our Master branch!

**Comment by afebbraro** [comment]
@motionsuggests Thanks Jon!
