### ISSUE TITLE
[Research] Improve release notes

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#471]
**User Story:**
As Spark, We need a better system for creating release notes. Here are a few options Dave found with a mix of automated and manual options.
* https://github.com/semantic-release/semantic-release
* https://github.com/conventional-changelog/standard-version
* https://keepachangelog.com/en/1.0.0/
* https://github.com/zeit/release

**Comment by RCopeland** [comment]
closing as not needed for now
