### ISSUE TITLE
Logo Container for Masthead

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#475]
## Proposal Title
Create a logo container that constrains logo images to a scale to a certain size. 

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [x] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [ ] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [x] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

## Description
Right now, a variable `$mobile-masthead-height` sets how much an open menu needs to be pushed down so it's flush with the navigation bar. This becomes a problem when the logo is large or it changes size as it scales with the viewport.

To fix this, the implementor would need to set a fixed height on the logo.

It's an assumption, but I assume a majority of the use cases would cause implementors to have to do this.

In order to reduce implementation confusion and error, there should be a container for the logo that constrains anything inside it. The logo can get bigger or smaller but at the limits of the container.

## Rationale
This reduces implementation confusion because implementors no longer have to measure the mobile-masthead-height and eliminates the problem of the logo changing sizes at different viewport sizes.

If the implementor for some reason needs to make a custom implementation and they need their logo to be taller than our constraint, then they can opt out of using the container.

## Live Examples
Please link to or attach any relevant documents to this proposal, including diagrams, illustrations, designs, code snippets, or other relevant documentation.
![masthead](https://user-images.githubusercontent.com/4342363/45055439-c0eced80-b05d-11e8-97b0-a68abf315ee9.gif)

**Comment by afebbraro** [comment]
I created a logo container for the new masthead. This is done.
