### ISSUE TITLE
Typography: Responsive Type Display Size

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#479]
## Proposal Title
Create a way to change Type Display size based on set breakpoints.

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [x] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

## Rationale
Some type would be look better/more readable if its font-size changed based on viewport size. I saw engineers make custom classes that ended up changing the size from smaller to bigger, and it would make sense if we could just include it into Spark.

## Live Examples
`class="sprk-b-TypeDisplayThree sprk-b-TypeDisplayTwo@m` 
Text would be at a Three display by default (mobile first), and then as the viewport reaches the `m` (medium) breakpoint, it would increase in size to TypeDisplayTwo.

Rocket Mortgage currently does it to their website, albeit, not everything matches spark just yet, but I imagine this use case with many other sites.

**Comment by afebbraro** [comment]
i think @RCopeland  is covering this in the type stuff he's working on now.

**Comment by afebbraro** [comment]
Taken care of in https://github.com/sparkdesignsystem/spark-design-system/pull/947
