### ISSUE TITLE
Button @sm need to match Stack--split@s sizes

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#480]
## Proposal Title
Button @sm need to match Stack--split@s sizes

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [x] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

## Description
This is for a set of buttons inside a Stack--split layout component. When stacked, we want the buttons to become become full width.

Right now, a button that goes to full width only has one breakpoint: 30rem, which matches `breakpoint-xs` size.

![image](https://user-images.githubusercontent.com/4342363/45115909-42f11b00-b11f-11e8-8fff-30643e951ffb.png)

For the stacked split to work correctly where the buttons stack AND go full width at the same time, the breakpoint assigned on the Stack--split only has one option: xs

What if the implementor wants to stack them and make them full width at different breakpoints? It limits it quite a bit.

I suggest creating matching breakpoint classes for button to go full width at all different viewports.

## Live Examples
![split](https://user-images.githubusercontent.com/4342363/45116479-d70fb200-b120-11e8-8a91-49d11ae05455.gif)

## UPDATE 10/8/18
After further talking with @afebbraro it wouldn't make sense for a button to be full width much more than @xs size. Full width buttons start not looking like buttons after a certain point.

This task would basically change line 18 of buttons.scss  to @xs instead of @sm just so it's consistent with the breakpoint that's happening.

*Two sizes will be available –– xs and sm*
sprk-c-Button--full@sm should be sprk-c-Button--full@xs to match the xs breakpoint.
There should also be a new one for full@sm that matches the small breakpoint

**Comment by motionsuggests** [comment]
@RVMendoza I'm picking this up but I have a couple questions. 

1. how many sizes should there be?
2. should all the sizes match the `$split-breakpoint`'s

**Comment by RVMendoza** [comment]
@motionsuggests hey there!

So quick change on this! After further talking with @afebbraro it wouldn't make sense for a button to be full width much more than @xs size. Full width buttons start not looking like buttons after a certain point.

This task would basically change line 18 of buttons.scss  to @xs instead of @sm just so it's consistent with the breakpoint that's happening.

1. Just one –– `sprk-c-Button--full@sm` should be `sprk-c-Button--full\@xs` to match the xs breakpoint.
2. Yes, and there is only one, which will be fulfilled after doing #1.

Updating the task

**Comment by RVMendoza** [comment]
@motionsuggests I woke up this morning and realized I misspoke, I edited the comment above.

**Comment by motionsuggests** [comment]
@RVMendoza Got it, thanks!

**Comment by afebbraro** [comment]
done in #661
