### ISSUE TITLE
Hamburger menu closes on scroll

### ISSUE THREAD

**Issue by janinavelasco9** [sparkdesignsystem/spark-design-system#483]
## Describe The Bug
Hamburger menu closing on scroll

## To Reproduce
1. Go to https://staging.sparkdesignsystem.com/tests/masthead on a mobile device
2. Click on the hamburger icon
3. Scroll down
4. The hamburger menu closes

## Expected Behavior
Expect the hamburger menu to stay open when you scroll inside it

## Smartphone (please complete the following information):
 - Device: iPhoneX, iPhone7
 - OS: iOS11
 - Browser Safari

**Comment by yodasw16** [comment]
https://github.com/sparkdesignsystem/spark-design-system/pull/488

**Comment by afebbraro** [comment]
merged in https://github.com/sparkdesignsystem/spark-design-system/pull/488
