### ISSUE TITLE
Highlight Board: Code / A11y / Design / Documentation Review 

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#49]
see one note, also: https://github.com/sparkdesignsystem/spark-design-system/wiki/Pattern-Testing

**Comment by philrinke** [comment]
@RCopeland 

some content for the descriptions of the highlight boards

The Highlight Board component is used as a lead into an experience as a means to encourage engagement within the experience.

**Default**
The default highlight board is the base component used to encourage engagement with a strong imagery.

**No Image**
This variation of the highlight board component should be used when there is an alternative to a photograph behind the lead message and cta. Examples of this are a wash of color or pattern set behind the content. 

**Stacked**
The stacked variation of the highlight board allows for the image and content/cta to be separated to allow the subject matter of the image become primary focus.

**Full Width**
The full width variation allows the background image of the highlight board to span the entire width of the viewport. The caveat is that the image asset needs to be large enough to accommodate any viewport size and respond accordingly
