### ISSUE TITLE
Explain Dividers <hr /> better

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#492]
## Proposal Title
Divider documentation could be even more clear. It currently has code samples for divs that style something into an hr, but doesn't create a clear dichotomy that that html `hr` is still available and should be used where it's semantic.

## Type of change
Please select only 1.
* [ ] New Component
* [ ] Enhancement to existing component
* [x] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [ ] **Component** (Modifying the functionality of a component)
* [x] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

## Description
Needs some kind of quick explanation. If we're going to style our hrs, we should give a code sample. Unless we're styling by tag which is another conversation.

## Rationale
I was confused when considering how to implement it, and if I was confused, others will be as well.

> <hr>are more for thematic breaks, such as separating different topics within a section of prose, or between scenes in a novel. However you can use it anywhere you can use a `<p>`. 
[html5 Doctor](http://html5doctor.com/small-hr-element/)

From @yodasw16 : 

> `<hr/>` has our divider style by default, as in we apply our style directly to the HR element. The class on a span or whatever is for times when HR isn’t the correct semantic choice, though most people probably won’t think about when it is actually appropriate to use an HR

## Live Examples
https://sparkdesignsystem.com/patterns/components/dividers

**Comment by katehyland** [comment]
I'd like to work on this.

**Comment by yodasw16** [comment]
Awesome, thanks! Let us know if you have any questions.

**Comment by katehyland** [comment]
@yodasw16 So I have my rough draft- but I just want to make sure I add this to the right file. Can you direct me to the best place to insert this documentation into? Thank you!

**Comment by RCopeland** [comment]
lgtm, @RVMendoza, is the explanation here what you had in mind? For #748

**Comment by RCopeland** [comment]
merged
