### ISSUE TITLE
Spacing: Implementation / Code / A11y / Design / Documentation Review

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#50]
We need to define this so that it can be used the the other patterns.

**Comment by afebbraro** [comment]
Researching!

**Comment by yodasw16** [comment]
These are the articles I have around this topic.
- https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62
- https://medium.com/fed-or-dead/handling-spacing-in-a-ui-component-library-70f3b22ec89
- https://blog.prototypr.io/a-framework-for-creating-a-predictable-and-harmonious-spacing-system-8eee8aaf773c
- https://medium.com/@ethersystem/generating-design-system-spacing-aa69714160bc

**Comment by afebbraro** [comment]
Thanks @yodasw16 !

**Comment by afebbraro** [comment]
Initial spacing proposal reviewed, agreed upon, merged. I'll be working on the documentation and further integration now.

**Comment by afebbraro** [comment]
@philrinke  reviewed content and approved. Waiting final review from @yodasw16.
