### ISSUE TITLE
[Build] Number inputs should only accept numbers

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#584]
## Proposal Title
Right now you can type letters into an input exclusively made for numbers. Sure, validation will come through, but we should reduce potential user error by only limiting accepted input to numbers.
![imgpsh_mobile_save-1](https://user-images.githubusercontent.com/4342363/46153822-e1b1f880-c241-11e8-89bf-140cf6b7ee92.jpg)

We should do this for dates, and other number only fields like ssn.

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

**Comment by katehyland** [comment]
Also would like to work on this! Validation FTW

**Comment by yodasw16** [comment]
@RVMendoza In the docs I am seeing an error when letters are input. Was this fixed at some point? If so, need to close this issue. @RCopeland maybe you've know since you primarily worked on inputs.
