### ISSUE TITLE
[Bug] Jumplinks aren't working when the code switch is present

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/spark-design-system#593]
The pseudoclass in src/assets/drizzle/styles/components/_navigation.scss adds an offset to jumplink targets that is the same vertical size as the header. When we added the code switch to the header, we increased the header size without increasing the pseudoclass offset.

1. Go to Inputs
2. Click on "Text Input" in the Table of Contents (or even on the actual headline, further down the page).
3. Note that without touching any scrolling, the headline and description are covered by the sticky header.

**Comment by ssabo1** [comment]
This will get fixed in the Spark Restructure.
