### ISSUE TITLE
[Review] Contribution Workflow Diagram

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#596]
**User Story:**
As Spark, we want to review the Diagram Below so that we can make it accurate and update our site. 

**AC:**
- As a team sit down and walk through Diagram, is it accurate???

If Accurate:
- Remove Coming soon. https://sparkdesignsystem.com/docs/contributions
- Add Contribution workflow diagram to https://sparkdesignsystem.com/docs/contributions

**Comment by philrinke** [comment]
![spark_contribution_flow_v1](https://user-images.githubusercontent.com/8290964/46548285-a09e9180-c89c-11e8-99bc-c0d2e4fa1a5e.png)

**Comment by philrinke** [comment]
i also have an svg as well as a eps of this file depending on what is best for dropping this graphic on the site.

**Comment by afebbraro** [comment]
thanks @philrinke !

**Comment by ssabo1** [comment]
This will be completed in #2209 - New Doc Site 2.0
