### ISSUE TITLE
[DOCUMENTATION] The Inset Short example is using the Inset Tall CSS classes

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#598]
## Describe The Bug
On the Space page, the Inset Short example is using the Inset Tall code. So, it renders the example as the tall inset spacing one instead of the inset short spacing
## To Reproduce
1. Go to './patterns/fundamentals/space'
2. Scroll down to Inset Short

## Expected Behavior
The Inset Short example should show the Inset Short Spacing instead of the Inset Tall spacing.

## Screenshots
![screen shot 2018-10-02 at 3 36 08 pm](https://user-images.githubusercontent.com/2117593/46372360-ea973580-c658-11e8-9bc5-16187936708c.png)

## Additional Context
All the classes used in inset-short.hbs need to be changed from drizzle-c-Space-inset-tall-[size] to the drizzle-c-Space-inset-short-[size].

**Comment by briankabiro** [comment]
Hi @afebbraro. Would like to take a look at this.
