### ISSUE TITLE
Create testing plan

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#6]
What types of testing do we need to do?

**Comment by RCopeland** [comment]
So every component/pattern will have a visual part and an accessibility part. Some components will have a behavioral part too. 

In the case of a visual part, we'll need to test that the pattern behaves correctly at the edges of its restrictions. If we test at the edges, we can assume that all in-between values are also working correctly. We'll have to do this with manual testing at first, then we can incorporate automatic visual regression to verify changes don't break existing functionality

In the case of an a11y part, we'll need to verify that it meets our baseline a11y criterion, which we still have to define. We can do this with a combination of manual testing and automated testing using tools like deque's Axe.

In the case of a behavioral part, we'll need to test for the correct behavior manually, but we'll also have unit tests and automated functional tests. We'll need to write unit tests for the supplied JS, and selenium scripts for the functional testing. It's likely that the behavioral testing and the a11y testing will be run in the same set of tests.

Aside from these tests, we'll also need to run cross-browser and performance tests. I think these will both have to be done manually with baselines set on a case-by-case basis.

I think it'd probably be easiest to test it if each pattern had its own 'kitchen sink' page, where we could implement many variations and restriction edge tests in a real dom environment. It'll also give us an easy way to test cross-browser.

Thoughts?

**Comment by RCopeland** [comment]
The first draft of an official testing / refactor plan (for each pattern):

## Pattern Validation
1. Define all common restriction edge cases. 
2. Create an instance of the pattern representing the edges of each restriction and combinations of restrictions where necessary.
3. Refactor / Code Review / Write Sass / Javascript (ES6) where needed.

Once the instances of the pattern are written and smoke tested in the test suite, perform:

## Brower Testing
### Supported Web Browsers (current version / one prior)
1. Internet Explorer 11
2. Google Chrome (64 / 63)
3. Edge (41 / 40)
4. Firefox (58/57)
5. Safari (11/10)

## Mobile Testing
1. At least one Apple device
2. At least one Android device

## Responsive Web Design
1. Patterns must be functional at a minimum width of 320px.
2.Patterns must be functional at a minimum height of 320px.
3. Patterns spread to fill their containers.

## Accessibility
1. Patterns must be functional using Safari and Mac Voice Over
2.Pattern must be functional using only a Keyboard
3. Patterns must manage user focus appropriately, when necessary.
4. Patterns must pass browser-based a11y testing suites (Axe, WAV, etc)

## Performance
1. Patterns must remain under 60fps when changing the DOM.

## Unit Testing
1. Any supplied Javascript must be unit tested.

**Comment by RCopeland** [comment]
@afebbraro @yodasw16 take a look plz

**Comment by RCopeland** [comment]
Contrast ratio, @afebbraro

**Comment by RCopeland** [comment]
i'm going to take what I've got there as a base, we can obviously modify it later.
