### ISSUE TITLE
Update padding on Spark Site Code CSS class to make inline code look more readable

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#602]
The padding on the `drizzle-c-Command` class is too big to make it fit nicely in a sentence. 

![screen shot 2018-10-03 at 10 29 09 am](https://user-images.githubusercontent.com/2117593/46417236-30a2d680-c6f7-11e8-8a6b-298cca0763bb.png)

Would like it cleaned up and styled so that it's not so big.

**Comment by briankabiro** [comment]
Hey @afebbraro. I can take a look at this one. 😃

**Comment by afebbraro** [comment]
Thanks again!

**Comment by briankabiro** [comment]
Don't mention it - 😄
