### ISSUE TITLE
[DOCUMENTATION] Revamp Release Notes Page

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#636]
We would like the https://sparkdesignsystem.com/docs/release-notes page header to be changed to "Spark Releases". And all the other content on the page removed to be replaced with a list of links to the current and past Spark releases. The releases are here https://github.com/sparkdesignsystem/spark-design-system/releases

So, for example, the link for our current release would say "Fall 2018 - The Angular Release" and the link would be https://github.com/sparkdesignsystem/spark-design-system/releases/tag/v2.1.0.

Please open this Pull Request against our MASTER branch, Thank you so much! Happy Hacktoberfest!

**Comment by arshadkazmi42** [comment]
Taking this up

**Comment by arshadkazmi42** [comment]
I have made the requested changes, it looks something like this

<img width="1440" alt="screen shot 2018-10-04 at 11 43 16 pm" src="https://user-images.githubusercontent.com/4654382/46494001-69de6200-c82f-11e8-94ab-7fc5aab27d5d.png">

**Comment by afebbraro** [comment]
@arshadkazmi42  thank you! Will merge shortly!

**Comment by afebbraro** [comment]
Merged! Thanks again!
