### ISSUE TITLE
[DOCUMENTATION] Wrap code that is used in the component docs in CSS class

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#638]
Throughout our docs we refer to bits of code in component information sections. Sometimes, the code is properly styled with the `drizzle-c-Command` class and most times, its not. To ensure better readability we want all the spots where code is used in the doc information, restrictions and variant descriptions to be wrapped in an element with the `drizzle-c-Command` class. 

For example, see this [page](https://sparkdesignsystem.com/patterns/components/alerts). In the restrictions sections, role="alert" should be wrapped in our code style class so that it looks like  `role="alert"`.  Another example is on the buttons page,` <input type="submit">`  should be wrapped in the `drizzle-c-Command` class. For an example of where this is done correctly, see [the developers page](https://sparkdesignsystem.com/gettingstarted/developers) and the line of code `npm install --save-dev @sparkdesignsystem/spark-core`.

Please make this PR against our master branch. Thanks and Happy Hacktoberfest! 🎃

**Comment by adityatandon007** [comment]
@afebbraro I would like to pick this up

**Comment by afebbraro** [comment]
@adityatandon007  fantastic! Thank you!

**Comment by ssabo1** [comment]
This will be taken care of with Spark Redesign.
