### ISSUE TITLE
[BUG] Accordions Cut off the content when window is resized

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#642]
## Describe The Bug
When you toggle open the accordion on a large screen and then shrink your window, it cuts off the content. In staging branch.

## To Reproduce
1. Go to accordions page (https://staging.sparkdesignsystem.com/patterns/components/accordions)
2. Click on the accordion toggle
3. You can see the content cut off

## Expected Behavior
The content should always be readable and not be cutoff when the window changes size.

## Screenshots
![screen shot 2018-10-05 at 8 37 44 am](https://user-images.githubusercontent.com/2117593/46535602-f746a400-c879-11e8-9a9e-e212adec116f.png)

## Desktop (please complete the following information):
 - OS: all
 - Browser: all
 - Version: all

## Smartphone (please complete the following information):
 - Device: [e.g. iPhone6] all
 - OS: [e.g. iOS8.1] all
 - Browser [e.g. stock browser, safari] all
 - Version [e.g. 22] all

## Additional Context
This happens with the code in our STAGING branch.

**Comment by sudharsana-kjl** [comment]
Hey! I'd like to work on this issue.

**Comment by afebbraro** [comment]
Thank you!! @sudharsana-kjl  Happy Hactoberfest! 🎃

**Comment by afebbraro** [comment]
This has been resolved.

**Comment by sudharsana-kjl** [comment]
Can you please provide the link to the commit where the fix was made?

**Comment by afebbraro** [comment]
@sudharsana-kjl Hi, this was fixed by some design change that involves pulling in a third party tool. It’s here: 
https://github.com/sparkdesignsystem/spark-design-system/pull/662/files#diff-6192503bd504762f5c1ff7c3a9ae81c0R1
