### ISSUE TITLE
Narrow nav on wide viewports

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#652]
## Describe The Bug
When the narrow nav is open and the window is resized past the main nav breakpoint, 
components of the narrow nav are still visible and causing layout issues.

## To Reproduce
1. shrink browser window
2. open narrow nav
3. widen browser window

## Expected Behavior
The narrow nav container should not be visible.

**Comment by afebbraro** [comment]
i fixed this in the new masthead by hiding the narrow nav at larger viewports.
