### ISSUE TITLE
Masthead: navigation is optional; but bottom border isn't

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#654]
## Proposal Title

Masthead is sometimes implemented without a bottom nav.

The bottom border is coded into nav, but if the consumer doesn't need it, there is no longer a bottom border.

We need to think about how to fix this.

![screen shot 2018-10-08 at 3 24 45 pm](https://user-images.githubusercontent.com/4342363/46629349-91267f00-cb0e-11e8-99c2-b34ea9b18747.png)

![masthead questions line](https://user-images.githubusercontent.com/4342363/46629231-25441680-cb0e-11e8-8013-1c1919b072bf.gif)

## Suggestion
We move the border/divider outside of that nav area and code to show and hide independent of the optional nav.

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [x] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

**Comment by RVMendoza** [comment]
Currently solving it by overriding that border to always show up. :(

![image](https://user-images.githubusercontent.com/4342363/46629862-49a0f280-cb10-11e8-94c1-64229271e957.png)

**Comment by afebbraro** [comment]
Closing as we have new masthead.
