### ISSUE TITLE
Masthead: Remove unnecessary aria-control from standalone mobile nav items

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#655]
## Proposal
On the mobile menu of masthead, `aria-controls` is on unnecessary links. We need to remove unnecessary aria controls in navigation that isn't an accordion because aria-controls denotes that it's controlling something.

![screen shot 2018-10-08 at 4 06 37 pm](https://user-images.githubusercontent.com/4342363/46631059-46a80100-cb14-11e8-9a17-b3589b06ba2c.png)

Further reading on aria controls:
https://thesocietea.org/2016/09/aria-roles-and-attributes-how-to-actually-use-them/
![image](https://user-images.githubusercontent.com/4342363/46630988-0a74a080-cb14-11e8-8dd9-1a6f4718f209.png)

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [x] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [x] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

**Comment by vjwilson** [comment]
I submitted a small PR, #663, for this one.
