### ISSUE TITLE
npm sym link doesn't work probably because of relative paths

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#664]
## Describe The Bug
@RCopeland and I found that sym link doesn't work because of the relative paths listed in the scss. For some reason, they can't find any of the file references. We think it's because of the relative paths.

## To Reproduce
1. Make a symlink with a project and spark
2. Build the project
3. Notice it doesn't work

## Expected Behavior
Spark should successfully sym link with a project

**Comment by afebbraro** [comment]
@RCopeland  I think your build stuff fixes this. Can we close this?

**Comment by yodasw16** [comment]
This was also an edge case for working with new styles in a project that is still on a previous version. I'm not sure this is something worth spending a bunch of time to fix, if it isn't already.

**Comment by RCopeland** [comment]
I think that this is fixed with build updates, closing for now.
