### ISSUE TITLE
Accordion is not allowing HTML tags

### ISSUE THREAD

**Issue by DaleGardner** [sparkdesignsystem/spark-design-system#667]
## Describe The Bug
HTML tags are not working inside of spark accordion details element. 😢 

## To Reproduce
1. Use a sprk-c-Accordion
2. Add some HTML in a sprk-c-Accordion__details element
3. HTML tags will be stripped out or moved

## Expected Behavior
HTML should be allowed inside the accordion details. Such as an ordered list, or a telephone element, or link.

## Desktop (please complete the following information):
 - Browser: chrome
 - Version: 68

**Comment by afebbraro** [comment]
hey @DaleGardner  thanks for filing an issue. I can help you. 

The sprk-c-Accordion__details element is a `<p>` element and therefore, due to the HTML spec, you shouldn't be putting things like `<div>` in there. What you want to do is change the default `<p>` to a div (that allows what you need).

Something like this:
```
    <div id="details1" class="sprk-c-Accordion__details  sprk-b-TypeBodyTwo sprk-u-HideWhenJs" data-sprk-toggle="content"><div class="your-class">YOUR STUFF</div></div>
```

**Comment by afebbraro** [comment]
@DaleGardner  hey Dale, I'm going to close this issue. If you have further questions, please feel free to respond back on here if you'd like! Thanks!

**Comment by DaleGardner** [comment]
Thanks for the responses Amber! 👍 

We definitely were not throwing divs into a p element, that would have been naughty lol. 😅 

Switched to div's and everything is working fine now. But glad to hear that the default is going to change to div. There's a lot of need to put subelements in there like a tag (incl. tel/email), ol, strong, etc. So supporting that by default makes sense. 😃

**Comment by afebbraro** [comment]
@DaleGardner haha yay! No problem! Yeah, sorry about it being a p tag! It should of been a div all along! Will be released in a few weeks.
