### ISSUE TITLE
Scales: Convert flag to use flexbox instead of display: table

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#673]
This is an issue for the Scales CSS framework that Spark is built on. See the details in issue https://github.com/ScalesCSS/scalescss/issues/44

**Comment by lindajzhao** [comment]
I'd like to work on this please :)

**Comment by lindajzhao** [comment]
Update: Looks like I won't have any availability to start on this issue until end of Nov. If there's anyone else who'd like to take over, feel free!!! If not, then I'll do it... eventually...

**Comment by yodasw16** [comment]
@lindajzhao No problem! I think there is someone interested that will take it over.

**Comment by motionsuggests** [comment]
PR submitted !!

**Comment by afebbraro** [comment]
@motionsuggests  PR # is https://github.com/ScalesCSS/scalescss/pull/63

**Comment by yodasw16** [comment]
https://github.com/sparkdesignsystem/spark-design-system/issues/1169
