### ISSUE TITLE
Dictionary values not aligning properly in IE 11

### ISSUE THREAD

**Issue by brikabrak** [sparkdesignsystem/spark-design-system#711]
## Description
Dictionary HTML rows in IE 11 do not space correctly. Value portions of dictionary rows do not align correctly at any media breakpoint. Values either space out a short amount or are right next to their corresponding row keys.

## To Reproduce
1. Go to the dictionary component at [sparkdesignsystem](https://sparkdesignsystem.com/patterns/components/dictionary) in Internet Explorer 11
2. Scroll down to the Basic Dictionary preview
3. View that text `dd` tags with `sprk-c-Dictionary__value` class are improperly spaced with their corresponding `dt` tags compared to Chrome, Safari, or Edge

## Expected Behavior
Expect similar behavior to Chrome/Safari/Edge dictionary previews in that `dd` tags align properly with each other and are spaced out at equal distances from their corresponding `dt` tags.

## Desktop:
 - Windows
 - Internet Explorer 11

## Additional Context
Issue found when implementing dictionary component for a upcoming feature. May be caused by `display: flex` in the corresponding parent `div` with class `sprk-c-Dictionary__keyvaluepair`. Added the following to an additional class for IE10+ browsers as a workaround.

```css
@media screen and (-ms-high-contrast: active), screen and (-ms-high-contrast: none) {
   display: table !important;
}
```

**Comment by RCopeland** [comment]
@brikabrak This should be fixed in 3.0, publishing shortly.
