### ISSUE TITLE
[BUILD] Refactor Accordion and Navigation

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#738]
Accordion is used in Navigation. They no longer look the same and are causing weird css to be written. refactor Navigation to no longer use accordion.

**Comment by RCopeland** [comment]
this got done during the masthead work, navigation is removed

**Comment by yodasw16** [comment]
Wasn’t this issue about separating accordion from navigation? Are we still using accordions in the masthead for narrow nav?

**Comment by RCopeland** [comment]
Ahh yeah thats true, narrow nav is part of masthead now, but it still uses accordions. I'll reopen.

**Comment by afebbraro** [comment]
Accordion styles are no longer used in the Masthead. The masthead now has it's own styles for this and was released in v10.
