### ISSUE TITLE
[Research] Random Prelaunch Bugs

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#740]
- [x] alert borders
- [x] alert text size
- [x] alert icon size 
- [x] wide nav tabbing into sub menus is broken
- [x] exclamation and information icons look weird
- [x] accordion border top is too think when open
- [x] pagination has underlines
- [x] masthead links should be 18px
- [x] error icon in js should be exclamation-filled
- [x] new stroke-widths for icons
- [x] can tab through hidden narrow nav links
- [x] narrow nav subnav links should not be bold
- [x] masthead narrow height needs to be fixed
- [x] add X icon without circle
- [x] swap alert dismiss icon for no circle X

**Comment by RCopeland** [comment]
wide nav tabbing into sub menus is broken

**Comment by RCopeland** [comment]
exclamation and information icons look weird

**Comment by RCopeland** [comment]
pagination has underlines...

**Comment by yodasw16** [comment]
Should make these into a checklist
