### ISSUE TITLE
[Testing] Pre-release once over

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#747]
1. Read docs
2. Check all components vanilla / angular

## Browsers

- [x] Safari
- [x] Firefox
- [x] IE11
- [x] Edge
- [x] Chrome
- [x] Android (Samsung Galaxy S9, vanilla only)
- [x] iOS (iPhone X, vanilla only)
- [x] MacVO + safari
- [x] Keyboard only (safari)

### Critical
**Made issues for these, see:** 
https://github.com/sparkdesignsystem/spark-design-system/issues/763
https://github.com/sparkdesignsystem/spark-design-system/issues/762
https://github.com/sparkdesignsystem/spark-design-system/issues/761
https://github.com/sparkdesignsystem/spark-design-system/issues/760
https://github.com/sparkdesignsystem/spark-design-system/issues/759
https://github.com/sparkdesignsystem/spark-design-system/issues/758

ALL: Errored fields should keep the yellow underline when they focus out
ALL: footer icon links have underlines
ALL: toggle links have underlines
ALL: toggle text is red (notsureif)
ALL: card link underlines are too wide
ALL: wide nav underlines should be black, not red
ALL: masthead tabbing out of links doesnt unmark them
ALL: tabbed nav home and end keys activate multiple tabs
IE11 - All: narrow nav link alignment is weird
IE11 - Vanilla: award text doesnt wrap
IE11 - Vanilla: dictionary alignment is weird (see open issue)
FF - All : alert icons are red, should be currentColor
FF - All: inline search icon is red, should be black
FF - All: icons not observing overridden stroke-widths
FF - All: narrow nav icons are red, should be black
MacVO in safari: footer social icons dont read where they go
MacVO in safari: modals dont take focus, dont read the contents
MacVO in safari: pagination 'pager' needs text for links (Prev / Next)
MacVO in safari: promo clickable icon needs screen reader text

### Can be postponed

**Made an issue for these, see:** https://github.com/sparkdesignsystem/spark-design-system/issues/757
ALL - Drizzle : narrow nav tabbing wont allow going further than the first item with a subnav
ALL: the first time an input label is animated, its jerky
ALL: payment input alignment is weird
ALL: submission spinner button moves a little, visually, when clicked
ALL: Date picker selected date is gray on red if its outside the current month
ALL: grouped subheadings on tables border is weird
ALL: spark releases page links look weird
ALL: narrow nav, able to reverse the bold if i open and close subnav too fast
ALL - vanilla: info modal close icon is too small
ALL - Angular: accordion / narrow nav animation looks weird
ALL - Angular: phone number input lets you type letters after a number is formatted, but doesnt 
show them. still marks field error
IE11 and Edge - All: accordion / narrow nav animation is sluggish and looks weird
IE11 and Edge - All: hamburger icon doesnt animate
IE11 - Angular: first button example has flash of unstyled button
FF-Angular: link hover state is weird
FF-Angular: pagination outline on prev / next icons is too wide

**Comment by afebbraro** [comment]
@RCopeland #1 looks to be working for me. I'll cross it off, but wanted to check with you first that what  I'm seeing is what you were thinking when you entered that bug. Could you check #1?

**Comment by RCopeland** [comment]
@afebbraro i think i fixed #1 and forgot to mark it
#2 might have been because i was using a vm,
