### ISSUE TITLE
[Build] Critical Prelaunch Bugs: Firefox icons

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#759]
- [x] FF - All : alert icons are red, should be currentColor
- [x] FF - All: inline search icon is red, should be black
- [ ] FF - All: icons not observing overridden stroke-widths
- [x] FF - All: narrow nav icons are red, should be black

**Comment by afebbraro** [comment]
Done, but, with a new issue created for the last three icons that aren't observing stroke-width overrides, https://github.com/sparkdesignsystem/spark-design-system/issues/776
