### ISSUE TITLE
[BUG] IE11: narrow nav links should be the same height when they contain one line of text

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#773]

**Comment by afebbraro** [comment]
This might be acceptable to label this under progressive enhancement? @RCopeland

**Comment by yodasw16** [comment]
I think I agree, but I would have to see the example of the problem again. I might be thinking of a different issue.

**Comment by RCopeland** [comment]
i think this may have been worked on already, the text isnt centered in ie11, but the heights are roughly the same
ie:
<img width="829" alt="screen shot 2018-11-13 at 12 52 55 pm" src="https://user-images.githubusercontent.com/412903/48432792-6352dc80-e743-11e8-90d1-53218dce0b1f.png">
chrome:
<img width="1042" alt="screen shot 2018-11-13 at 12 55 08 pm" src="https://user-images.githubusercontent.com/412903/48432800-677efa00-e743-11e8-8acd-2c8c5753defc.png">

**Comment by afebbraro** [comment]
@yodasw16  @RCopeland  are we in agreement to close this or leave it open?

**Comment by afebbraro** [comment]
closing
