### ISSUE TITLE
[BUG] Inputs (specifically dropdown) has label length issues

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#804]
## Describe The Bug
It says in the docs there is a limit. Mostly because the animation would cause all sorts of trouble.

But with labels that don't have to move, or ones with placeholders, we could consider making it more flexible.

![screen shot 2018-11-09 at 1 33 30 pm](https://user-images.githubusercontent.com/4342363/48282616-2d061c00-e428-11e8-91b8-746073e2555e.png)

**Comment by afebbraro** [comment]
New design for inputs so this is outdated.
