### ISSUE TITLE
Inputs: Spark doesn't catch elements with the right data attributes when it's already loaded

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/spark-design-system#815]
## Describe The Bug
Input problem. Spark loads on page load and no other time.

When I "ADD ANOTHER ASSET", it creates new inputs in the DOM and Spark doesn't hook into it to add and remove classes.

![inpu](https://user-images.githubusercontent.com/4342363/48428320-c5f2ab00-e738-11e8-94b0-a41bc19af4b1.gif)

We should make binding work anytime an element appears with the right data attributes.

**Comment by RCopeland** [comment]
this can be fixed when #835 is merged, you can use the exported bindUIEvents to bind input events to the inputs created and added after the DOM is loaded.
