### ISSUE TITLE
[Research] Input spacing issues

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#827]
Review spacing on radio buttons. In this screenshot, there is a lot of vertical space (orange) around the radio buttons and a lot of horizontal space (blue) between the radio buttons and labels.

![image](https://user-images.githubusercontent.com/1424560/48720223-414ad580-ebed-11e8-94c8-e34a0187a246.png)

**Comment by RCopeland** [comment]
@yodasw16 has this been transferred to new issues?

**Comment by yodasw16** [comment]
I think this is just one issue. Just need to transfer the details from the email and chat messages we got

**Comment by RCopeland** [comment]
changing this to research to look into input spacing in general.
