### ISSUE TITLE
Should we move all component variables into the settings file?

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/spark-design-system#83]
amber: I like having all the available settings in the settings.scss file since it's easier to make design changes. It might also be advantageous as far as how user's expect Spark to work. They might get confused as to why some vars are in settings but then some are scattered throughout. How do you feel about making a new section under the other component sections in settings for the Dictionary settings?

**Comment by yodasw16** [comment]
As we discussed, I'd like to push this discussion out to when we start researching design tokens since it will have a big impact on that.

**Comment by RCopeland** [comment]
FYI, in angular apps, bringing in spark via the global styles pattern doesn't allow component styles to access the spark vars. Putting all vars in one file would allow angular components to import that file whenever a var is needed.

**Comment by yodasw16** [comment]
Hmmm, I need to understand this more and how it might relate to a multi-tiered design token approach. For example, if the button component has a variable `$primary-button-background-color: $green-medium` and `$green-medium` is set in a global tokens file. Something like that. In angular, would the component variable be able to get the value from the global file?

**Comment by afebbraro** [comment]
As we went along, we realized this was a good idea and it has been implemented.
