### ISSUE TITLE
Spark Swag (Stickers)

### ISSUE THREAD

**Issue by eenewbsauce** [sparkdesignsystem/spark-design-system#837]
## Dev Stickers
I think it would be awesome to get some dev stickers made for Spark!

## Type of change
Please select only 1.
* [ ] New Component
* [ ] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)
* [x] Other

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [ ] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

## Description
Endorse the project with stickers

## Rationale
Dev stickers are fun

**Comment by yodasw16** [comment]
We have some! 2 different ones actually. One that's the logo by itself and one with the logo and the name.

**Comment by yodasw16** [comment]
Let's remember to bring some next time we go to a React Community thing.
