### ISSUE TITLE
Chrome Autofill Issue with Spark Text Inputs

### ISSUE THREAD

**Issue by brianbond-rocket** [sparkdesignsystem/spark-design-system#872]
## Describe The Bug
Chrome autofill will populate the values of text inputs without triggering the event bindings that move the labels out of the input. As a result, the label is inside the box along with the text, until the user clicks something on the page.

## To Reproduce
1. Set up Chrome autofill for spark text inputs
2. Load page with Chrome filling in the values
3. Observe labels

## Expected Behavior
Inputs should set classes for labels to appear above input when a value is autofilled.

## Screenshots
![autofilllabels](https://user-images.githubusercontent.com/31017467/49158523-64157200-f2f0-11e8-9dfd-64963d6c6a42.png)

## Desktop (please complete the following information):
 - Device: MacBook Pro
 - OS: macOS Sierra 10.12.6
 - Browser: Chrome
 - Version: 70.0.3538.102 64-bit

**Comment by yodasw16** [comment]
I assume this same issue applies to other browser's autofill capabilities. Also probably popular password managers like LastPass and 1Password.

**Comment by OAndersonQL** [comment]
I'm seeing the same thing when populating input controls for an Angular reactive form. I'm testing with Spark/SparkNg 6.0.1.

**Comment by afebbraro** [comment]
Closing because the input design changed and this is no longer a concern.
