### ISSUE TITLE
Look into dom-slider

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#873]
Look into possibly switching out this package for something else. It's currently used for the Toggles in Spark. It was mentioned there's an issue with how this package modifies the Node.prototype and therefore is causing issues with JSDOM.

**Comment by afebbraro** [comment]
JSDOM issues were fixed but we can still look into this if we want.

**Comment by ssabo1** [comment]
Duplicate. Will be completed in #1409
