### ISSUE TITLE
Toggles are not fully functional in IE 11

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/spark-design-system#874]
Team is experiencing a javascript error when using Toggles in IE 11. The error is related to a Promise call in DOM slider.

Need to reproduce locally and isolate the issue.

![image](https://user-images.githubusercontent.com/1424560/49161948-e35a7400-f2f7-11e8-88e1-c42cd0e89746.png)

![image](https://user-images.githubusercontent.com/1424560/49161904-c887ff80-f2f7-11e8-8be4-06f6f53891ea.png)

**Comment by eenewbsauce** [comment]
You need to polyfill for Promise

**Comment by RCopeland** [comment]
merged
