### ISSUE TITLE
Define success metrics and how to track them

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#9]
## problems we're trying to solve with the design system:

1. Client-facing apps don't look like they belong to the same company / ecosystem.
2. Tons of UI code duplication across apps.
3. Wildly varying patterns across applications causes a lot of duplicate work, by Designers and UI Engineers.

## possible KPIs:

1. application adoption (how many apps are directly using Spark)
2. system completeness (how many patterns are implemented and ready for use)
3. ease of use (how long does it take an engineer level UI person to set their app up with spark-core)
4. documentation completeness (how many patterns have complete docs)
5. drizzle / spark guide pageviews ? (im not sure if > pageviews means its successful)

## possible ways to measure them:

1. survey, manual research
2. automated pattern count (possibly vs a target?)
3. surveys to UI Engineers
4. automated pattern count vs automated documentation section count
5. google analytics

Thoughts?

**Comment by RCopeland** [comment]
I think the easiest thing to start with is probably the survey. What questions should be on it?

Here's a rough list of the ones i was thinking of:

## Adoption

- Is spark-core currently installed in your application?
- Which version?
- How many core patterns are currently in use in client-facing code?
- Are any spark-extras patterns installed in your application?
- How many spark-extras patterns are currently in use in client-facing code?

## Convenience

- How would you rate the process of installing a pattern from spark (core or extras)?
- How would you rate the process of implementing a pattern from spark-core?
- How would you rate the process of implementing a pattern from spark-extras?

## Coverage

- Are there any specific patterns you need that are missing from spark?
- If so, which ones?
- Are there any patterns that you feel don't really belong in spark?
- If so, which ones?

## Contribution

- Have you ever contributed a pattern or pattern change to spark?
- How would you rate the contribution process?
- If you could change anything about the contribution process, what would it be?
