### ISSUE TITLE
New Sass variables

### ISSUE THREAD

**Issue by ptrkcsk** [sparkdesignsystem/spark-design-system#913]
## New Sass variables

I'd like to propose the addition of new Sass variables for setting:

- Color of hovered Masthead links 
- Color of active narrow nav items
- Color of hovered standalone links

## Type of change

Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category

Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

## Description

See summary above.

## Rationale

These three things are hardcoded to `$red`:

- [Hovered Masthead link](https://github.com/sparkdesignsystem/spark-design-system/blob/december-4-2018/packages/spark-core/components/_masthead.scss#L104)
- [Active narrow nav item](https://github.com/sparkdesignsystem/spark-design-system/blob/december-4-2018/packages/spark-core/components/_accordions.scss#L105)
- [Hovered standalone link](https://github.com/sparkdesignsystem/spark-design-system/blob/december-4-2018/packages/spark-core/base/_links.scss#L31)

## Live Examples

[Here's my use case.](https://codesandbox.io/s/7yzxnz7rz6) Try hovering over the phone number, big nav items and expanding the narrow nav.

**Comment by ptrkcsk** [comment]
Awesome! Thanks for the quick reply!

**Comment by afebbraro** [comment]
You’re welcome! @ptrkcsk

**Comment by afebbraro** [comment]
@ptrkcsk , i have the PR ready for this, but we are in process of updating links, so the standalone link that you mentioned will be updated with that PR. Thanks again for writing this up. https://github.com/sparkdesignsystem/spark-design-system/pull/951

**Comment by afebbraro** [comment]
merged, but the standalone links vars will be in a diff PR
