### ISSUE TITLE
[BUILD] Update inputs

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/spark-design-system#918]
## What does this PR do?
Updates input styling, removes JS that tests for focus / value.

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR
then please remove it.
### Documentation
 - [x] Update Spark Docs Angular
 - [x] Update Spark Docs Vanilla
 - [x] Update Component Sass Var/Class Modifier table

### Code
 - [x] Build Component in Spark Vanilla (Sass, HTML, JS)
 - [x] Build Component in Spark Angular
 - [x] Unit Testing in Spark Vanilla (100% coverage, 100% passing)
 - [x] Unit Testing in Spark Angular (100% coverage, 100% passing)

### Accessibility
- [x] New changes abide by [accessibility requirements](https://sparkdesignsystem.com/docs/accessibility)

### Browser Testing (current version and 1 prior)
  - [x] Google Chrome
  - [x] Google Chrome (Mobile)
  - [x] Mozilla Firefox (Mobile)
  - [x] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [x] Microsoft Edge
  - [x] Apple Safari
  - [x] Apple Safari (Mobile)

### Design Review
 - [x] Design reviewed and approved

### Screenshots
Add screenshots to help explain your PR if you'd like. However, this is not
expected.

**Comment by bbrown7** [comment]
![image](https://user-images.githubusercontent.com/37777173/50496881-488dac00-0a01-11e9-9a6f-5c24ef299dc3.png)
![image](https://user-images.githubusercontent.com/37777173/50496991-00bb5480-0a02-11e9-8468-f65a3b2df8af.png)

**Comment by bbrown7** [comment]
![image](https://user-images.githubusercontent.com/37777173/50497025-4c6dfe00-0a02-11e9-8149-2a04d5a850ae.png)
![image](https://user-images.githubusercontent.com/37777173/50497030-5b54b080-0a02-11e9-84d3-275c8accea64.png)

**Comment by bbrown7** [comment]
![image](https://user-images.githubusercontent.com/37777173/50519257-00fe3300-0a88-11e9-8621-6adac8061b9e.png)
![image](https://user-images.githubusercontent.com/37777173/50519392-b5985480-0a88-11e9-9e91-21e60fb98a1a.png)

**Comment by bbrown7** [comment]
![image](https://user-images.githubusercontent.com/37777173/50519440-ed9f9780-0a88-11e9-9903-c72e77aac325.png)
![image](https://user-images.githubusercontent.com/37777173/50519445-f09a8800-0a88-11e9-8815-a565a642c8fb.png)

**Comment by RCopeland** [comment]
@bbrown7 
Hey, I'm going to put questions as I'm working in this comment:

- On an errored input, does the border color stay yellow on focus?
- Should i use a transition when changing border color? or instant change?

**Comment by bbrown7** [comment]
@RCopeland 

- Yes stay yellow on focus until they type something
- fade the transition over 0.3s
- Inactive input
![image](https://user-images.githubusercontent.com/37777173/50597764-7dbd5280-0e76-11e9-9e2f-70b894075e96.png)
- line height of 16 should be good
- chevron - what is wrong with it other than the thickness?
- default of 32 px between each form field
- date picker modal 
    - 4 px rounded corners
    - green filled circle and hover
    - shadow (Shadow blur: 16 , Shadow spread: 0, Y Axis: 4, Opacity: 10%)
    - font size from 1rem to 0.9375rem
