### ISSUE TITLE
FontFaceObserver times out (fonts still load)

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/spark-design-system#929]
## Describe The Bug
User is experiencing a console error ~10 seconds after page load. The fonts are all loading, however.

## To Reproduce
1. Get login URL from Teams (Dec 13, 11:02 AM)
4. Wait ~10 seconds
5. In the console, you should see an error that looks like this:

![image](https://user-images.githubusercontent.com/1424560/49959389-6aecd900-fedb-11e8-8963-20ca88c11526.png)

## Desktop (please complete the following information):
 - Browser Chrome

## Additional Context
The fonts all appear to be loading and applying correctly. The URLs in the user's settings file all resolve to valid font files.

**Comment by bobwise** [comment]
See also
https://github.com/bramstein/fontfaceobserver/issues/100
https://github.com/bramstein/fontfaceobserver/issues/80

**Comment by RCopeland** [comment]
closing since we removed font face observer
