### ISSUE TITLE
[BUILD] Links Reskin

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/spark-design-system#933]

**Comment by afebbraro** [comment]
@bobwise , your PR for this should also satisfy the request to change the color of hovered standalone links. From here: https://github.com/sparkdesignsystem/spark-design-system/issues/913

**Comment by bbrown7** [comment]
![image](https://user-images.githubusercontent.com/37777173/50486728-398b0780-09c9-11e9-8d44-4745207d1bf4.png)

**Comment by bobwise** [comment]
Outstanding work for Links:

1. The `--plain` and `--muted` link variants are not documented.
2. We need to audit all other components that include links and make sure we're using them in ways we're good with. For example, Award includes a link that is styled as both `--standalone` and `--plain`, and Masthead includes its own `sprk-c-Masthead__link` class.
