### ISSUE TITLE
Create section in sprk docs on browser support

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/spark-design-system#98]
We'll need to let consumers of Spark know about what browsers the system supports.

**Comment by yodasw16** [comment]
Do we want to replicate the whole browser support recommendation here or just put simple numbers?

**Comment by erikwoods** [comment]
Opinion: I think it should be the whole recommendation, but re-written a little differently considering the circumstances (this is now public-facing, and our current documentation might have details that don't make sense outside of QL).

**Comment by RCopeland** [comment]
ahh duplicate issue, good catch. @erikwoods 
we decided to just list the browsers for now. Updated in staging.
