### ISSUE TITLE
[BUG] Pagination hover issue

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/spark-design-system#999]
## Describe The Bug
Numbers in pagination have a red circle outline that peek-a-boos in when you stop hovering.

## To Reproduce
1. Go to https://staging.sparkdesignsystem.com/patterns/components/pagination
2. Hover over a number that is _not_ active.
3. Move mouse away from hovering on the number.
4. You'll see a red circle appear for a second and then disappear.

## Expected Behavior
There should be no hover effect on non-active numbers.

**Comment by afebbraro** [comment]
Linking this to the reskin task so no work is duplicated in the same release. https://github.com/sparkdesignsystem/spark-design-system/issues/1002
